force-app/main/default/objects/Permission_Type__c/Permission_Type__c.object-meta.xml
<CustomObject>
    <label>Permission Type</label>
    <nameField>
        <displayFormat>PT-{0000}</displayFormat>
        <label>Permission Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Permissions Type</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Permission_Type__c/fields/MaxRecords__c.field-meta.xml
<CustomField>
    <fullName>MaxRecords__c</fullName>
    <defaultValue>0</defaultValue>
    <label>MaxRecords</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Permission_Type__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <label>Time</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Diario</fullName>
            </value>
            <value>
                <fullName>Semanal</fullName>
            </value>
            <value>
                <fullName>Mensual</fullName>
            </value>
            <value>
                <fullName>Siempre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Permission_Type__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UserId</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Permissions_Type</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RefreshRecordsProcessedBatchTest.cls
@IsTest(SeeAllData=True)
private class RefreshRecordsProcessedBatchTest {
  	@IsTest
    private static void testSchedulable() {
        RefreshRecordsProcessedSchedule objSchedulable = null;
        
        objSchedulable = new RefreshRecordsProcessedSchedule();
        objSchedulable.execute(null);
    }
    
    @IsTest
    private static void testBatch() {
        RefreshRecordsProcessedBatch objBatch = null;
        Test.setMock(HttpCalloutMock.class, new RESTMock());
        objBatch = new RefreshRecordsProcessedBatch([SELECT ID FROM REPORT LIMIT 50]);
        Test.startTest();
        Database.executeBatch(objBatch,50);
        Test.stopTest();
    }
    
    private static void initializeTest() {
        Permission_Type__c objPermissionType = null;
        List<Permission_Type__c> lstPermissionType = null;
        
        lstPermissionType = new List<Permission_Type__c>();
        
        objPermissionType = new Permission_Type__c();
        objPermissionType.MaxRecords__c = 100;
        objPermissionType.Profile_Id__c = UserInfo.getProfileId();
        objPermissionType.Time__c = 'Semanal';
        lstPermissionType.add(objPermissionType);

        objPermissionType = new Permission_Type__c();
        objPermissionType.MaxRecords__c = 100;
        objPermissionType.UserId__c = UserInfo.getUserId();
        objPermissionType.Time__c = 'Semanal';
        lstPermissionType.add(objPermissionType);

		insert lstPermissionType;        
    }
}