force-app/main/default/objects/Pilar360__c/Pilar360__c.object-meta.xml
<CustomObject>
    <label>Pilar360</label>
    <nameField>
        <displayFormat>P360-{00000000}</displayFormat>
        <label>Pilar360</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pilar360s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pilar360__c/fields/Citizen__c.field-meta.xml
<CustomField>
    <fullName>Citizen__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup con CONTACTS</description>
    <label>Citizen</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Pilar360s</relationshipLabel>
    <relationshipName>Pilar360s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PilarCitizenInteractions__c/PilarCitizenInteractions__c.object-meta.xml
<CustomObject>
    <label>PilarCitizenInteraction</label>
    <nameField>
        <displayFormat>PilarInteraction-{00000000}</displayFormat>
        <label>PilarCitizenInteraction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PilarCitizenInteractions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PilarCitizenInteractions__c/fields/Interaction_Date__c.field-meta.xml
<CustomField>
    <fullName>Interaction_Date__c</fullName>
    <description>Fecha interaccion mimuni</description>
    <label>Interaction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PilarCitizenInteractions__c/fields/Pilar360Citizen_SFID__c.field-meta.xml
<CustomField>
    <fullName>Pilar360Citizen_SFID__c</fullName>
    <description>M-D entre Pilar 360 ( Ciudadanos 360) y PilarCiudadanosActividades (sus actividades)</description>
    <label>Pilar360Citizen_SFID</label>
    <referenceTo>Pilar360__c</referenceTo>
    <relationshipName>PilarCiudadanosInteracciones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PilarCitizenInteractions__c/fields/PilarCiudadanoID__c.field-meta.xml
<CustomField>
    <fullName>PilarCiudadanoID__c</fullName>
    <label>PilarCiudadanoID</label>
    <precision>14</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PilarCitizenInteractions__c/fields/Programs__c.field-meta.xml
<CustomField>
    <fullName>Programs__c</fullName>
    <label>Programas</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>MiBarrio</fullName>
            </value>
            <value>
                <fullName>MiDocumentacion</fullName>
            </value>
            <value>
                <fullName>MiMascota</fullName>
            </value>
            <value>
                <fullName>MiSalud</fullName>
            </value>
            <value>
                <fullName>Otros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PilarCitizenInteractions__c/fields/Services__c.field-meta.xml
<CustomField>
    <fullName>Services__c</fullName>
    <label>Servicios</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Antigeno</fullName>
            </value>
            <value>
                <fullName>Contact Center</fullName>
            </value>
            <value>
                <fullName>PCR</fullName>
            </value>
            <value>
                <fullName>Turnos CDR DNI/Pasaporte</fullName>
            </value>
            <value>
                <fullName>Vacunate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Pilar360Controller.cls
public with sharing class Pilar360Controller {
    
    @AuraEnabled(cacheable=true)
    public static List<PilarCitizenInteractions__c> retrieveInteractions(String id) {
        return [SELECT Id, Name, PilarCiudadanoID__c, Interaction_Date__c, Programs__c, Services__c FROM PilarCitizenInteractions__c WHERE PilarCitizenInteractions__c.Pilar360Citizen_SFID__R.Citizen__c =: id ];
    }

    @AuraEnabled(cacheable=true)
    public static List<AggregateResult> retrieveStats(String id) {
        return [SELECT Programs__c, Services__c, COUNT(id) FROM PilarCitizenInteractions__c WHERE PilarCitizenInteractions__c.Pilar360Citizen_SFID__R.Citizen__c =: id GROUP BY Programs__c, Services__c ];
    }

    @AuraEnabled(cacheable=true)
    public static Pilar360__c retrievePilarRecord(String id) {
        List<Pilar360__c> objLst = [SELECT Citizen__R.Name FROM Pilar360__c WHERE Citizen__c =: id];
        if (!objLst.isEmpty())
            return objLst[0];
        return null;
    }

    @AuraEnabled(cacheable=true)
    public static List<String> retrievePrograms() {
        return HelperFunctions.retrievePicklistValuesToStringList('PilarCitizenInteractions__c', 'Programs__c');
    }
}