force-app/main/default/objects/Export__c/Export__c.object-meta.xml
<CustomObject>
    <label>Export</label>
    <nameField>
        <label>Export Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Export__c/fields/All_Data__c.field-meta.xml
<CustomField>
    <fullName>All_Data__c</fullName>
    <defaultValue>false</defaultValue>
    <label>All Data</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Export__c/fields/Callout_Message__c.field-meta.xml
<CustomField>
    <fullName>Callout_Message__c</fullName>
    <label>Callout Message</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Export__c/fields/Data_Extension__c.field-meta.xml
<CustomField>
    <fullName>Data_Extension__c</fullName>
    <label>Data Extension</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Export__c/fields/Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Date__c</fullName>
    <label>Order_Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Export__c/fields/Record_Count__c.field-meta.xml
<CustomField>
    <fullName>Record_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Record Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Export__c/fields/SAQL__c.field-meta.xml
<CustomField>
    <fullName>SAQL__c</fullName>
    <label>SAQL</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Export__c/fields/Sendable__c.field-meta.xml
<CustomField>
    <fullName>Sendable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sendable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Export__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente de aprobación</fullName>
            </value>
            <value>
                <fullName>Aprobado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>En espera de ejecución</fullName>
            </value>
            <value>
                <fullName>En ejecución</fullName>
            </value>
            <value>
                <fullName>Finalizado OK</fullName>
            </value>
            <value>
                <fullName>Finalizado con errores</fullName>
            </value>
            <value>
                <fullName>Pendiente de aprobación {Sin cantidad de registros)</fullName>
                <color>#FFFF66</color>
                <label>Pendiente de aprobación {Sin cantidad de registros)</label>
            </value>
            <value>
                <fullName>Error en SAQL</fullName>
            </value>
            <value>
                <fullName>Detener</fullName>
            </value>
            <value>
                <fullName>Detenido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Export__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ApprovalProcessEmailRequestRestTest.cls
@IsTest
private class ApprovalProcessEmailRequestRestTest {
    @IsTest 
    static void testApprove(){        
        RestRequest objRESTRequest = null; 
        RestResponse objRESTResponse = null;
        Export__c objExport = null;

        objExport = createExport();
        objRESTRequest = new RestRequest(); 
        objRESTResponse = new RestResponse();

        objRESTRequest.requestURI = String.format('https://www.salesforce.com/{0}/approve', new String [] { objExport.Id} );
        objRESTRequest.httpMethod = 'GET';
        RestContext.request = objRESTRequest;
        RestContext.response = objRESTResponse;

        ApprovalProcessEmailRequestRest.IsAlive();        
    }

    @IsTest
    static void testReject(){        
        RestRequest objRESTRequest = null; 
        RestResponse objRESTResponse = null;
        Export__c objExport = null;

        objExport = createExport();
        objRESTRequest = new RestRequest(); 
        objRESTResponse = new RestResponse();

        objRESTRequest.requestURI = String.format('https://www.salesforce.com/{0}/reject', new String [] { objExport.Id} );
        objRESTRequest.httpMethod = 'GET';
        RestContext.request = objRESTRequest;
        RestContext.response = objRESTResponse;

        ApprovalProcessEmailRequestRest.IsAlive();        
    }
    private static Export__c createExport() {
        Export__c objExport = null;

        objExport = new Export__c();
        objExport.Name = 'test';
        objExport.Type__c = 'test';
        objExport.All_Data__c = false;
        objExport.Sendable__c = false;
        objExport.SAQL__c = 'test';
        objExport.Data_Extension__c = 'test';
        objExport.Survey__c = 'test';

        objExport.Order_Date__c = Datetime.now();
        objExport.Status__c = 'Pendiente de Aprobacion';
        objExport.Callout_Message__c = 'test';
        objExport.Record_Count__c = 1;

        insert objExport;

        return objExport;
    }
}