force-app/main/default/objects/Export__c/Export__c.object-meta.xml
<CustomObject>
    <label>Export</label>
    <nameField>
        <label>Export Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Export__c/fields/All_Data__c.field-meta.xml
<CustomField>
    <fullName>All_Data__c</fullName>
    <defaultValue>false</defaultValue>
    <label>All Data</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Export__c/fields/Callout_Message__c.field-meta.xml
<CustomField>
    <fullName>Callout_Message__c</fullName>
    <label>Callout Message</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Export__c/fields/Data_Extension__c.field-meta.xml
<CustomField>
    <fullName>Data_Extension__c</fullName>
    <label>Data Extension</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Export__c/fields/Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Date__c</fullName>
    <label>Order_Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Export__c/fields/Record_Count__c.field-meta.xml
<CustomField>
    <fullName>Record_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Record Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Export__c/fields/SAQL__c.field-meta.xml
<CustomField>
    <fullName>SAQL__c</fullName>
    <label>SAQL</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Export__c/fields/Sendable__c.field-meta.xml
<CustomField>
    <fullName>Sendable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sendable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Export__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente de aprobación</fullName>
            </value>
            <value>
                <fullName>Aprobado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>En espera de ejecución</fullName>
            </value>
            <value>
                <fullName>En ejecución</fullName>
            </value>
            <value>
                <fullName>Finalizado OK</fullName>
            </value>
            <value>
                <fullName>Finalizado con errores</fullName>
            </value>
            <value>
                <fullName>Pendiente de aprobación {Sin cantidad de registros)</fullName>
                <color>#FFFF66</color>
                <label>Pendiente de aprobación {Sin cantidad de registros)</label>
            </value>
            <value>
                <fullName>Error en SAQL</fullName>
            </value>
            <value>
                <fullName>Detener</fullName>
            </value>
            <value>
                <fullName>Detenido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Export__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Permission_Type__c/Permission_Type__c.object-meta.xml
<CustomObject>
    <label>Permission Type</label>
    <nameField>
        <displayFormat>PT-{0000}</displayFormat>
        <label>Permission Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Permissions Type</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Permission_Type__c/fields/MaxRecords__c.field-meta.xml
<CustomField>
    <fullName>MaxRecords__c</fullName>
    <defaultValue>0</defaultValue>
    <label>MaxRecords</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Permission_Type__c/fields/Records__c.field-meta.xml
<CustomField>
    <fullName>Records__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Records</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Permission_Type__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <label>Time</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Diario</fullName>
            </value>
            <value>
                <fullName>Semanal</fullName>
            </value>
            <value>
                <fullName>Mensual</fullName>
            </value>
            <value>
                <fullName>Siempre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Permission_Type__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UserId</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Permissions_Type</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ExportControllerTest.cls
@IsTest
private  class ExportControllerTest {
    @IsTest
    private static void processApproveExportRequestTest() {
        ExportController.createExport('eamc', 'terst', true, true, 'esto es un saql', 'esto es una data extension', 'Pulso Survey', '', '', '', '', '');
        ExportController.createExport('pulso', 'terst', true, true, 'esto es un saql', 'esto es una data extension', 'Pulso Survey', '', '', '', '', '');
        ExportController.createExport('eacsv', 'terst', true, true, 'esto es un saql', 'esto es una data extension', 'Pulso Survey', '', '', '', '', '');
        ExportController.createExport('mccsv', 'terst', true, true, 'esto es un saql', 'esto es una data extension', 'Pulso Survey', '', '', '', '', '');
        initializeTest();

        ExportController.elmejortestlohacelusuarioenproduccion();
        Test.setMock(HttpCalloutMock.class, new RESTMock());

        List<Export__c> lstExport = ExportController.exports('');

        for(Export__c objExport : lstExport) {
            objExport.Order_Date__c = Date.today();
            objExport.Status__c = 'Aprobado';

            ExportController.processRequest(objExport.Id, true);
            ExportRESTInterface.updateExportStatus('eamc', 'En ejecución');
            ExportRESTInterface.updateExportStatus('eamc', 'Finalizado OK');            
        }

        update lstExport;
    }

    @IsTest
    private static void processUpdateExportTest() {
        Export__c objExport = null;

        objExport = new Export__c();
        objExport.Name = 'test';
        objExport.Type__c = 'test';
        objExport.All_Data__c = false;
        objExport.Sendable__c = false;
        objExport.SAQL__c = 'test';
        objExport.Data_Extension__c = 'test';
        objExport.Survey__c = 'test';

        objExport.Order_Date__c = Datetime.now();
        objExport.Status__c = 'test';
        objExport.Callout_Message__c = 'test';
        objExport.Record_Count__c = 1;

        insert objExport;
        update objExport;
    }

    @IsTest
    private static void processREjectedExportRequestTest() {
        ExportController.createExport('eamc', 'terst', true, true, 'esto es un saql', 'esto es una data extension', 'Pulso Survey', '', '', '', '', '');
        ExportController.createExport('pulso', 'terst', true, true, 'esto es un saql', 'esto es una data extension', 'Pulso Survey', '', '', '', '', '');
        ExportController.createExport('eacsv', 'terst', true, true, 'esto es un saql', 'esto es una data extension', 'Pulso Survey', '', '', '', '', '');
        ExportController.createExport('mccsv', 'terst', true, true, 'esto es un saql', 'esto es una data extension', 'Pulso Survey', '', '', '', '', '');
        

        List<Export__c> lstExport = ExportController.exports('');

        for(Export__c objExport : lstExport) {
            objExport.Order_Date__c = Date.today();
            objExport.Status__c = 'Rechazado';

            ExportController.processRequest(objExport.Id, false);
        }

        update lstExport;
    }

    private static void initializeTest() {
        Permission_Type__c objPermissionType = null;
        List<Permission_Type__c> lstPermissionType = null;
        
        lstPermissionType = new List<Permission_Type__c>();
        
        objPermissionType = new Permission_Type__c();
        objPermissionType.MaxRecords__c = 100000;
        objPermissionType.Records__c = 100000;
        objPermissionType.Profile_Id__c = UserInfo.getProfileId();
        objPermissionType.Time__c = 'Semanal';
        lstPermissionType.add(objPermissionType);

        objPermissionType = new Permission_Type__c();
        objPermissionType.MaxRecords__c = 100000;
        objPermissionType.Records__c = 100000;
        objPermissionType.UserId__c = UserInfo.getUserId();
        objPermissionType.Time__c = 'Semanal';
        lstPermissionType.add(objPermissionType);

		insert lstPermissionType;        
    }
}