force-app/main/default/objects/ActivityLog__c/ActivityLog__c.object-meta.xml
<CustomObject>
    <description>Se genera un registro nuevo por cada visualizacion de un usuario a una vista custom: citizen o territory.</description>
    <label>ActivityLog</label>
    <nameField>
        <displayFormat>LOG{0000000}</displayFormat>
        <label>ActivityLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ActivityLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ActivityLog__c/fields/Empatia__c.field-meta.xml
<CustomField>
    <fullName>Empatia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empatia</label>
    <referenceTo>Empatia__c</referenceTo>
    <relationshipLabel>ActivityLogs</relationshipLabel>
    <relationshipName>ActivityLogs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ActivityLog__c/fields/LogSource__c.field-meta.xml
<CustomField>
    <fullName>LogSource__c</fullName>
    <label>LogSource</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Document_Number__c.field-meta.xml
<CustomField>
    <fullName>Document_Number__c</fullName>
    <label>Documento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/guid__c.field-meta.xml
<CustomField>
    <fullName>guid__c</fullName>
    <externalId>true</externalId>
    <label>GUID</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Empatia__c/Empatia__c.object-meta.xml
<CustomObject>
    <label>Empatía</label>
    <nameField>
        <displayFormat>EMP-{0000000}</displayFormat>
        <label>Empatia Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Empatía</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Empatia__c/fields/Apellido__c.field-meta.xml
<CustomField>
    <fullName>Apellido__c</fullName>
    <label>Apellido</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Empatia__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <externalId>true</externalId>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Empatia__c/fields/Empatia_Activista__c.field-meta.xml
<CustomField>
    <fullName>Empatia_Activista__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empatia Activista</label>
    <referenceTo>Empatia_Activista__c</referenceTo>
    <relationshipLabel>Respuestas Encuesta</relationshipLabel>
    <relationshipName>Empatias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Empatia__c/fields/Response_Token__c.field-meta.xml
<CustomField>
    <fullName>Response_Token__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Response Token</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Empatia__c/recordTypes/Activista.recordType-meta.xml
<RecordType>
    <fullName>Activista</fullName>
    <active>true</active>
    <label>Activista</label>
</RecordType>

force-app/main/default/objects/Empatia_Activista__c/Empatia_Activista__c.object-meta.xml
<CustomObject>
    <label>Empatia Activista</label>
    <nameField>
        <label>Empatia Activista Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empatía Activistas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Empatia_Activista__c/fields/DNI__c.field-meta.xml
<CustomField>
    <fullName>DNI__c</fullName>
    <externalId>true</externalId>
    <label>DNI</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Empatia_Nota__c/Empatia_Nota__c.object-meta.xml
<CustomObject>
    <label>Empatia_Nota</label>
    <nameField>
        <displayFormat>E{000000}</displayFormat>
        <label>Empatia_Nota Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Empatia_Notas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Empatia_Nota__c/fields/Empatia_Activista__c.field-meta.xml
<CustomField>
    <fullName>Empatia_Activista__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empatia Activista</label>
    <referenceTo>Empatia_Activista__c</referenceTo>
    <relationshipLabel>Observaciones</relationshipLabel>
    <relationshipName>Empatia_Notas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Empatia_Nota__c/fields/Nota__c.field-meta.xml
<CustomField>
    <fullName>Nota__c</fullName>
    <label>Nota</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/empatiaControllerTest.cls
@isTest
public with sharing class empatiaControllerTest {
  @TestSetup
  static void makeData() {
    Contact ct = new Contact();
    ct.LastName = 'test';
    ct.guid__c = '11111';
    ct.Document_Number__c = '123456';

    insert ct;

    Empatia__c empatia = new Empatia__c(
      Apellido__c = 'testApellido',
      Nombre__c = 'testNombre',
      DNI__c = '123456',
      email__c = 'prueba@prueba.com',
      Response_Token__c = 'test2',
      Fecha_Respuesta__c = Date.newInstance(2222, 2, 17)
    );

    insert empatia;
  }

  @isTest
  public static void testRapido_OkCases() {
    Empatia_Activista__c activista = [
      SELECT id
      FROM Empatia_Activista__c
      WHERE dni__C = '123456'
    ];

    Empatia_Nota__c nota = new Empatia_Nota__c(
      Nota__c = 'test cuerpo nota',
      Empatia_Activista__c = activista.Id
    );

    insert nota;

    Empatia__c empRecord = [
      SELECT id, Empatia_Activista__c
      FROM Empatia__c
      WHERE DNI__c = '123456'
    ];

    Test.startTest();
    empatiaController.retrieveActivistaFromId(empRecord.id);
    empatiaController.retrieveNotasFromActivistaFromId(empRecord.id);
    empatiaController.insertNota(
      empRecord.Empatia_Activista__c,
      'test, nueva nota'
    );
    Test.stopTest();
  }

  @isTest
  public static void testRapido_NullRecords() {
    Boolean exepcion = false;
    Test.startTest();
    empatiaController.retrieveActivistaFromId(null);
    empatiaController.retrieveNotasFromActivistaFromId(null);
    Test.stopTest();
  }

  @isTest
  static void createLogTest() {
    Empatia__c empatia = [
      SELECT id, Empatia_Activista__c
      FROM Empatia__c
      WHERE DNI__c = '123456'
    ];

    Test.startTest();
    empatiaController.createLog(empatia.id);
    Test.stopTest();

    List<ActivityLog__c> logs = [ SELECT empatia__c, logSource__c FROM ActivityLog__c];

    System.assertEquals(1, logs.size(), 'Se debe haber creado 1 log.');
    System.assertEquals(empatia.id, logs[0].empatia__c, 'El log debe estar completo con el registro de empatia que se visitó');
    System.assertEquals('CRM', logs[0].logSource__c, 'El log debe estar identificado como generado desde el CRM');
  }
}