force-app/main/default/objects/ActivityLog__c/ActivityLog__c.object-meta.xml
<CustomObject>
    <description>Se genera un registro nuevo por cada visualizacion de un usuario a una vista custom: citizen o territory.</description>
    <label>ActivityLog</label>
    <nameField>
        <displayFormat>LOG{0000000}</displayFormat>
        <label>ActivityLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ActivityLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ActivityLog__c/fields/LogSource__c.field-meta.xml
<CustomField>
    <fullName>LogSource__c</fullName>
    <label>LogSource</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ActivityLog__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>Territorio_Administrativo__c</referenceTo>
    <relationshipLabel>ActivityLogs</relationshipLabel>
    <relationshipName>ActivityLogs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/Territorio_Administrativo__c.object-meta.xml
<CustomObject>
    <description>Objeto Custom para carga de Territorios de multiples paises, estructurado en 5 niveles</description>
    <label>Territorio</label>
    <nameField>
        <label>Territorio Administrativo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territorios</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/TerritoryFullPageController_ltTest.cls
@isTest
public class TerritoryFullPageController_ltTest {
    @isTest
    public static void simpleQueryTest () {
        Territorio_administrativo__c terr = CommonTestFunctions.createTerritorioAdministrativo('Territorio 0', null, 0);
        Test.startTest();
        List<Territorio_administrativo__c> terrList= TerritoryFullPageController_lt.getTerritoryById(terr.id);
        Test.stopTest();
        System.assertEquals(terrList[0].name, 'Territorio 0', 'El controller debe devolver el territorio correctamente');
    }

    @isTest  
    static void createLogTest() {      
        Territorio_administrativo__c terr = CommonTestFunctions.createTerritorioAdministrativo('Territorio 0', null, 0);
        Test.startTest();        
        TerritoryFullPageController_lt.createLog(terr.id);
        Test.stopTest();

        List<ActivityLog__c> logs = [SELECT Territory__c, logSource__c FROM ActivityLog__c];

        System.assertEquals(1, logs.size(), 'Se debe haber creado 1 log.');
        System.assertEquals(terr.id, logs[0].Territory__c, 'El log debe estar completo con el territorio que se visitó');
        System.assertEquals('CRM', logs[0].logSource__c, 'El log debe estar identificado como generado desde el CRM');
        
    }
}