force-app/main/default/objects/ActivityLog__c/ActivityLog__c.object-meta.xml
<CustomObject>
    <description>Se genera un registro nuevo por cada visualizacion de un usuario a una vista custom: citizen o territory.</description>
    <label>ActivityLog</label>
    <nameField>
        <displayFormat>LOG{0000000}</displayFormat>
        <label>ActivityLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ActivityLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ActivityLog__c/fields/Citizen__c.field-meta.xml
<CustomField>
    <fullName>Citizen__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Citizen</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>ActivityLogs</relationshipLabel>
    <relationshipName>ActivityLogs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ActivityLog__c/fields/LogSource__c.field-meta.xml
<CustomField>
    <fullName>LogSource__c</fullName>
    <label>LogSource</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Community__c.field-meta.xml
<CustomField>
    <fullName>Community__c</fullName>
    <label>Comunidad</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Futbolista</fullName>
            </value>
            <value>
                <fullName>Mascoteros</fullName>
                <default>true</default>
                <label>Mascoteros</label>
            </value>
            <value>
                <fullName>Futboleros</fullName>
            </value>
            <value>
                <fullName>Lector</fullName>
            </value>
            <value>
                <fullName>Pintor</fullName>
            </value>
            <value>
                <fullName>Tenista</fullName>
            </value>
            <value>
                <fullName>Fanático de futebol</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/guid__c.field-meta.xml
<CustomField>
    <fullName>guid__c</fullName>
    <externalId>true</externalId>
    <label>GUID</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CommunitiesControllerTest.cls
/**
* Class Name: CommunitiesControllerTest
* Description: Test Class for the CommunitiesController
* Developer: José Gerstner - Date: 17/05/2021
*/

@isTest
public class CommunitiesControllerTest {
    @testSetup
    private static void setupTest() {
        CommonTestFunctions.commonSetup();                       
    }
    
    @isTest 
    private static void testCommunitiesController() {
        Contact objContact = null;
		ApexPages.StandardController objStandardController = null;
        ContactDetailController objContactDetailController = null;
        CitizenWrapper objContactWrapper = null;
        
        objContact = CommonTestFunctions.retrieveContact();
        System.assertEquals(TRUE, ContactDetailController.saveMultipicklistOptions(objContact.Id, 'Contact', 'Community__c', new String[] {'hola', 'mundo'})); 

        objStandardController = new ApexPages.StandardController(objContact);
        objContactDetailController = new ContactDetailController (objStandardController);
        objContactDetailController.saveContact();
        
        System.assertEquals(objContact.Id, objContactDetailController.contact.Id);
        System.assertEquals(objContact.Id, objContactDetailController.conId);
        System.assertEquals(objContact.Id, objContactDetailController.contWrap.contact.Id);     
        System.assertNotEquals(NULL, objContactDetailController.contWrap.personAddressSearch); 
        //System.assertNotEquals(NULL, objContactDetailController.contWrap.tags);     
     
        objContactWrapper = CommunitiesController.retrieveInfoFromCitizenId(objContact.Id);
        System.assertEquals(objContact.Id, objContactWrapper.citizen.Id);          
    }
    
    @IsTest
    private static void retrieveSiteTest() {
        CommunitiesController.retrieveSite();
    }
    
    @isTest  
    static void retriveTerritory() {              
        CommunitiesController.getRootTerritory();
    }

    @isTest  
    static void createLogTest() {      
        Contact ct = new Contact ();
        ct.FirstName = 'testName';
        ct.LastName = 'testLstName';
        ct.guid__c = 'asd123123';
        insert ct;

        Test.startTest();        
        CommunitiesController.createLog(ct.id);
        Test.stopTest();

        List<ActivityLog__c> logs = [SELECT Citizen__c, logSource__c FROM ActivityLog__c];

        System.assertEquals(1, logs.size(), 'Se debe haber creado 1 log.');
        System.assertEquals(ct.id, logs[0].Citizen__c, 'El log debe estar completo con el ciudadano que se visitó');
        System.assertEquals('CRM', logs[0].logSource__c, 'El log debe estar identificado como generado desde el CRM');
        
    }
}