force-app/main/default/objects/ActivityLog__c/ActivityLog__c.object-meta.xml
<CustomObject>
    <description>Se genera un registro nuevo por cada visualizacion de un usuario a una vista custom: citizen o territory.</description>
    <label>ActivityLog</label>
    <nameField>
        <displayFormat>LOG{0000000}</displayFormat>
        <label>ActivityLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ActivityLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ActivityLog__c/fields/Citizen__c.field-meta.xml
<CustomField>
    <fullName>Citizen__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Citizen</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>ActivityLogs</relationshipLabel>
    <relationshipName>ActivityLogs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ActivityLog__c/fields/Empatia__c.field-meta.xml
<CustomField>
    <fullName>Empatia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empatia</label>
    <referenceTo>Empatia__c</referenceTo>
    <relationshipLabel>ActivityLogs</relationshipLabel>
    <relationshipName>ActivityLogs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Age_f_x__c.field-meta.xml
<CustomField>
    <fullName>Age_f_x__c</fullName>
    <description>Formula que calcula la edad en funcion de la fecha de nacimiento del ciudadano</description>
    <formula>IF(ISNULL(Birthdate) , NULL, FLOOR((TODAY()-Birthdate +1)/365.2425))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Edad</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Cuil_Number__c.field-meta.xml
<CustomField>
    <fullName>Cuil_Number__c</fullName>
    <externalId>true</externalId>
    <label>CUIL/CUIT</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Document_Number__c.field-meta.xml
<CustomField>
    <fullName>Document_Number__c</fullName>
    <label>Documento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Sexo</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/guid__c.field-meta.xml
<CustomField>
    <fullName>guid__c</fullName>
    <externalId>true</externalId>
    <label>GUID</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Level1Name__c.field-meta.xml
<CustomField>
    <fullName>Level1Name__c</fullName>
    <formula>IF(Territorio_Administrativo__r.Nivel_Administrativo__c == 1, Territorio_Administrativo__r.Name,  (
	IF(Territorio_Administrativo__r.Nivel_Administrativo__c ==  2 ,Territorio_Administrativo__r.ParentId__r.Name,
		IF(Territorio_Administrativo__r.Nivel_Administrativo__c == 3, Territorio_Administrativo__r.ParentId__r.ParentId__r.Name,
			IF(Territorio_Administrativo__r.Nivel_Administrativo__c == 4, Territorio_Administrativo__r.ParentId__r.ParentId__r.ParentId__r.Name, NULL)		
		) 
	)
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Level1Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Level2Name__c.field-meta.xml
<CustomField>
    <fullName>Level2Name__c</fullName>
    <formula>IF(Territorio_Administrativo__r.Nivel_Administrativo__c == 2, Territorio_Administrativo__r.Name,  (
	IF(Territorio_Administrativo__r.Nivel_Administrativo__c ==  3 ,Territorio_Administrativo__r.ParentId__r.Name,
		IF(Territorio_Administrativo__r.Nivel_Administrativo__c == 4, Territorio_Administrativo__r.ParentId__r.ParentId__r.Name, NULL)		
		) 
	)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Level2Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Level3Name__c.field-meta.xml
<CustomField>
    <fullName>Level3Name__c</fullName>
    <formula>IF(Territorio_Administrativo__r.Nivel_Administrativo__c == 3, Territorio_Administrativo__r.Name,  (
	IF(Territorio_Administrativo__r.Nivel_Administrativo__c ==  4 ,Territorio_Administrativo__r.ParentId__r.Name, NULL
		
	)
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Level3Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Level4Name__c.field-meta.xml
<CustomField>
    <fullName>Level4Name__c</fullName>
    <formula>IF(Territorio_Administrativo__r.Nivel_Administrativo__c ==  4 ,Territorio_Administrativo__r.Name, NULL
		
	)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Level4Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MailingAppartment__c.field-meta.xml
<CustomField>
    <fullName>MailingAppartment__c</fullName>
    <description>Este es el que va 13/6</description>
    <label>MailingAppartment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MailingNumber__c.field-meta.xml
<CustomField>
    <fullName>MailingNumber__c</fullName>
    <description>Este es el numero de Calle que vá</description>
    <label>MailingNumber</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Nacionalidad__c.field-meta.xml
<CustomField>
    <fullName>Nacionalidad__c</fullName>
    <label>Nacionalidad</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PhotoUrl_legacy__c.field-meta.xml
<CustomField>
    <fullName>PhotoUrl_legacy__c</fullName>
    <label>PhotoURL</label>
    <length>2048</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Whatsapp__c.field-meta.xml
<CustomField>
    <fullName>Whatsapp__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Whatsapp</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Empatia__c/Empatia__c.object-meta.xml
<CustomObject>
    <label>Empatía</label>
    <nameField>
        <displayFormat>EMP-{0000000}</displayFormat>
        <label>Empatia Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Empatía</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Empatia__c/fields/Apellido__c.field-meta.xml
<CustomField>
    <fullName>Apellido__c</fullName>
    <label>Apellido</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Empatia__c/fields/Celular__c.field-meta.xml
<CustomField>
    <fullName>Celular__c</fullName>
    <label>Celular</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Empatia__c/fields/Ciudad__c.field-meta.xml
<CustomField>
    <fullName>Ciudad__c</fullName>
    <formula>TEXT(Ciudad_Catamarca__c)+
TEXT(Ciudad_Chaco__c)+
TEXT(Ciudad_Chubut__c)+
TEXT(Ciudad_Cordoba__c)+
TEXT(Ciudad_Corrientes__c)+
TEXT(Ciudad_Entre_Rios__c)+
TEXT(Ciudad_Formosa__c)+
TEXT(Ciudad_Jujuy__c)+
TEXT(Ciudad_La_Pampa__c)+
TEXT(Ciudad_La_Rioja__c)+
TEXT(CIudad_Mendoza__c)+
TEXT(Ciudad_Misiones__c)+
TEXT(Ciudad_Neuquen__c)+
TEXT(Ciudad_Rio_Negro__c)+
TEXT(Ciudad_Salta__c)+
TEXT(Ciudad_San_Juan__c)+
TEXT(Ciudad_San_Luis__c)+
TEXT(Ciudad_Santa_Cruz__c)+
TEXT(Ciudad_Santa_Fe__c)+
TEXT(Ciudad_Santiago_del_Estero__c)+
TEXT(Ciudad_Tierra_del_Fuego__c)+
TEXT(Ciudad_Tucuman__c)+
TEXT(Municipio_Buenos_Aires__c)</formula>
    <label>Ciudad</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Empatia__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <externalId>true</externalId>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Empatia__c/fields/Empatia_Activista__c.field-meta.xml
<CustomField>
    <fullName>Empatia_Activista__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empatia Activista</label>
    <referenceTo>Empatia_Activista__c</referenceTo>
    <relationshipLabel>Respuestas Encuesta</relationshipLabel>
    <relationshipName>Empatias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Empatia__c/fields/Evento__c.field-meta.xml
<CustomField>
    <fullName>Evento__c</fullName>
    <label>Evento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Empatia__c/fields/Fecha_de_Nacimiento__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Nacimiento__c</fullName>
    <label>Fecha de Nacimiento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Empatia__c/fields/Participacion__c.field-meta.xml
<CustomField>
    <fullName>Participacion__c</fullName>
    <label>Participacion</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Difundir en Redes Sociales y WhatsApp</fullName>
            </value>
            <value>
                <fullName>Ir a la presentación de Facundo Manes en mi ciudad</fullName>
            </value>
            <value>
                <fullName>Subirte a la caravana de la Empatía</fullName>
            </value>
            <value>
                <fullName>Poner un cartel de Empatía en mi casa</fullName>
            </value>
            <value>
                <fullName>Ver y/o presentar un proyecto para mi ciudad</fullName>
            </value>
            <value>
                <fullName>Ver y/o realizar un micro aporte en causas sociales de mi ciudad</fullName>
            </value>
            <value>
                <fullName>Dedicar 10hs semanales a tareas de activismo en mi ciudad</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Empatia__c/fields/Provincia__c.field-meta.xml
<CustomField>
    <fullName>Provincia__c</fullName>
    <label>Provincia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buenos Aires</fullName>
            </value>
            <value>
                <fullName>CABA</fullName>
            </value>
            <value>
                <fullName>Catamarca</fullName>
            </value>
            <value>
                <fullName>Chaco</fullName>
            </value>
            <value>
                <fullName>Chubut</fullName>
            </value>
            <value>
                <fullName>Córdoba</fullName>
            </value>
            <value>
                <fullName>Corrientes</fullName>
            </value>
            <value>
                <fullName>Entre Ríos</fullName>
            </value>
            <value>
                <fullName>Formosa</fullName>
            </value>
            <value>
                <fullName>Jujuy</fullName>
            </value>
            <value>
                <fullName>La Pampa</fullName>
            </value>
            <value>
                <fullName>La Rioja</fullName>
            </value>
            <value>
                <fullName>Mendoza</fullName>
            </value>
            <value>
                <fullName>Misiones</fullName>
            </value>
            <value>
                <fullName>Neuquén</fullName>
            </value>
            <value>
                <fullName>Río Negro</fullName>
            </value>
            <value>
                <fullName>Salta</fullName>
            </value>
            <value>
                <fullName>San Juan</fullName>
            </value>
            <value>
                <fullName>San Luis</fullName>
            </value>
            <value>
                <fullName>Santa Cruz</fullName>
            </value>
            <value>
                <fullName>Santa Fe</fullName>
            </value>
            <value>
                <fullName>Santiago del Estero</fullName>
            </value>
            <value>
                <fullName>Tierra del Fuego</fullName>
            </value>
            <value>
                <fullName>Tucumán</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Empatia_Activista__c/Empatia_Activista__c.object-meta.xml
<CustomObject>
    <label>Empatia Activista</label>
    <nameField>
        <label>Empatia Activista Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empatía Activistas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Empatia_Activista__c/fields/Citizen__c.field-meta.xml
<CustomField>
    <fullName>Citizen__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Citizen</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Empatía Activistas</relationshipLabel>
    <relationshipName>Empatia_Activistas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Empatia_Activista__c/fields/DNI__c.field-meta.xml
<CustomField>
    <fullName>DNI__c</fullName>
    <externalId>true</externalId>
    <label>DNI</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Empatia_Activista__c/fields/Fecha_de_nacimiento__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_nacimiento__c</fullName>
    <description>Se usa junto con el DNI para identificar al ciudadano. Un trigger la concatena en el campo &quot;identificador_unico__c&quot;</description>
    <label>Fecha de nacimiento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Empatia_Activista__c/fields/Provincia__c.field-meta.xml
<CustomField>
    <fullName>Provincia__c</fullName>
    <label>Provincia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Empatia_Nota__c/Empatia_Nota__c.object-meta.xml
<CustomObject>
    <label>Empatia_Nota</label>
    <nameField>
        <displayFormat>E{000000}</displayFormat>
        <label>Empatia_Nota Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Empatia_Notas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Empatia_Nota__c/fields/Empatia_Activista__c.field-meta.xml
<CustomField>
    <fullName>Empatia_Activista__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empatia Activista</label>
    <referenceTo>Empatia_Activista__c</referenceTo>
    <relationshipLabel>Observaciones</relationshipLabel>
    <relationshipName>Empatia_Notas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/empatiaController.cls
public without sharing class empatiaController {
  @AuraEnabled(cacheable=true)
  public static Empatia__c retrieveActivistaFromId(Id empatiaId) {

    List<Empatia__c> queryResults = [
      SELECT
        name,
        ciudad__c,
        Celular__c,
        Nombre__c,
        Apellido__c,
        DNI__c,
        Email__c,
        Evento__c,
        Fecha_de_Nacimiento__c,
        Participacion__c,
        Provincia__c,
        Empatia_Activista__r.Citizen__r.MailingPostalCode,
        Empatia_Activista__r.Citizen__r.MailingStreet,
        Empatia_Activista__r.Citizen__r.MailingNumber__c,
        Empatia_Activista__r.Citizen__r.Level1Name__c,
        Empatia_Activista__r.Citizen__r.Level2Name__c,
        Empatia_Activista__r.Citizen__r.Level3Name__c,
        Empatia_Activista__r.Citizen__r.Level4Name__c,
        Empatia_Activista__r.Citizen__r.Age_f_x__c,
        Empatia_Activista__r.Citizen__r.Nacionalidad__c,
        Empatia_Activista__r.Citizen__r.guid__c,
        Empatia_Activista__r.Citizen__r.Email,
        Empatia_Activista__r.Citizen__r.HomePhone,
        Empatia_Activista__r.Citizen__r.MobilePhone,
        Empatia_Activista__r.Citizen__r.Whatsapp__c,
        Empatia_Activista__r.Citizen__r.PhotoUrl_legacy__c,
        Empatia_Activista__r.Citizen__r.FirstName,
        Empatia_Activista__r.Citizen__r.LastName,
        Empatia_Activista__r.Citizen__r.Name,
        Empatia_Activista__r.Citizen__r.Birthdate,
        Empatia_Activista__r.Citizen__r.Gender__c,
        Empatia_Activista__r.Citizen__r.Document_Number__c,
        Empatia_Activista__r.Citizen__r.Cuil_Number__c,
        Empatia_Activista__r.Citizen__r.MailingAppartment__c,
        Empatia_Activista__c,
        Empatia_Activista__r.Estado_Contacto__c,
        Empatia_Activista__r.Etapa_Contacto__c,
        Empatia_Activista__r.Fecha_de_Inscripcion__c
      FROM Empatia__c
      WHERE Id = :empatiaId
    ];

    if (queryResults.size() == 0) {
      return null;
    }

    return queryResults[0];
  }

  @AuraEnabled(cacheable=true)
  public static List<Empatia_Nota__c> retrieveNotasFromActivistaFromId(
    Id empatiaId
  ) {
    //relaciones: empatia_notas (muchos)-----(1/0) empatia_activista (1/0)------(muchos) empatias
    List<Empatia__c> empatiaResult = [
      SELECT Empatia_Activista__c
      FROM Empatia__c
      WHERE Id = :empatiaId
    ];

    if (empatiaResult.size() == 0) {
      return new List<Empatia_Nota__c>();
    }

    List<Empatia_Nota__c> queryResults = [
      SELECT Nota__c, CreatedBy.FirstName, CreatedBy.LastName, CreatedDate
      FROM Empatia_Nota__c
      WHERE Empatia_Activista__c = :empatiaResult[0].Empatia_Activista__c
      ORDER BY CreatedDate DESC
    ];

    if (queryResults.size() == 0) {
      return new List<Empatia_Nota__c>();
    }

    return queryResults;
  }

  @AuraEnabled
  public static List<Empatia_Nota__c> insertNota(
    Id empatiaActivistaId,
    String nota
  ) {
    Empatia_Nota__c newNota = new Empatia_Nota__c();
    newNota.Nota__c = nota;
    newNota.Empatia_Activista__c = empatiaActivistaId;
    insert newNota;

    return [
      SELECT Nota__c, CreatedBy.FirstName, CreatedBy.LastName, CreatedDate
      FROM Empatia_Nota__c
      WHERE Empatia_Activista__c = :empatiaActivistaId
      ORDER BY CreatedDate DESC
    ];
  }

  @AuraEnabled
  public static void createLog (Id recordId) {
      String networkId = Network.getNetworkId();
      String logSource = 'CRM';
      if (String.isNotBlank(networkId)) {
          //no se pueden crear datos de test para el objeto NETWORK, porque reprensenta comunidades. Asi que lo testeo.
          //una alternativa seria que el lwc le pase como parametro el context (nompre de la app del CRM o de la comunidad donde se este usando)
          List<Network> lstNetwork = [SELECT NAME FROM NETWORK WHERE ID =: networkId];
          logSource = lstNetwork[0].name;
      }
  
      ActivityLog__c log = new ActivityLog__c ();
      log.empatia__c = recordId;
      log.logSource__c = logSource;
      Insert log;
  }
}