force-app/main/default/objects/ActivityLog__c/ActivityLog__c.object-meta.xml
<CustomObject>
    <description>Se genera un registro nuevo por cada visualizacion de un usuario a una vista custom: citizen o territory.</description>
    <label>ActivityLog</label>
    <nameField>
        <displayFormat>LOG{0000000}</displayFormat>
        <label>ActivityLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ActivityLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ActivityLog__c/fields/LogSource__c.field-meta.xml
<CustomField>
    <fullName>LogSource__c</fullName>
    <label>LogSource</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ActivityLog__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>Territorio_Administrativo__c</referenceTo>
    <relationshipLabel>ActivityLogs</relationshipLabel>
    <relationshipName>ActivityLogs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/Territorio_Administrativo__c.object-meta.xml
<CustomObject>
    <description>Objeto Custom para carga de Territorios de multiples paises, estructurado en 5 niveles</description>
    <label>Territorio</label>
    <nameField>
        <label>Territorio Administrativo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territorios</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Nivel_Administrativo__c.field-meta.xml
<CustomField>
    <fullName>Nivel_Administrativo__c</fullName>
    <label>Nivel Administrativo</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ParentId</label>
    <referenceTo>Territorio_Administrativo__c</referenceTo>
    <relationshipLabel>Territories</relationshipLabel>
    <relationshipName>ChildTerritories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TerritoryFullPageController_lt.cls
public class TerritoryFullPageController_lt {
  @AuraEnabled(Cacheable=true)
  public static List<Territorio_Administrativo__c> getTerritoryById(Id territoryId) {
    List<Territorio_Administrativo__c> terrList = [
        SELECT
          Id, Name,
          Nivel_Administrativo__c,
          ParentId__c,
          ParentId__r.Name,
          ParentId__r.ParentId__c,
          ParentId__r.ParentId__r.Name,
          ParentId__r.ParentId__r.ParentId__c,
          ParentId__r.ParentId__r.ParentId__r.Name,
          ParentId__r.ParentId__r.ParentId__r.ParentId__c,
          ParentId__r.ParentId__r.ParentId__r.ParentId__r.Name,
          (SELECT Id, Name FROM ChildTerritories__r)
        FROM Territorio_Administrativo__c
        WHERE id = :territoryId
      ];
      
    return terrList;
  }

  @AuraEnabled
  public static void createLog (Id recordId) {
      String networkId = Network.getNetworkId();
      String logSource = 'CRM';
      if (String.isNotBlank(networkId)) {
          //no se pueden crear datos de test para el objeto NETWORK, porque reprensenta comunidades. Asi que lo testeo.
          //una alternativa seria que el lwc le pase como parametro el context (nompre de la app del CRM o de la comunidad donde se este usando)
          List<Network> lstNetwork = [SELECT NAME FROM NETWORK WHERE ID =: networkId];
          logSource = lstNetwork[0].name;
      }
  
      ActivityLog__c log = new ActivityLog__c ();
      log.Territory__c = recordId;
      log.logSource__c = logSource;
      Insert log;
  }
}