force-app/main/default/objects/Prosumer_Dominio_de_Email__c/Prosumer_Dominio_de_Email__c.object-meta.xml
<CustomObject>
    <label>Prosumer Dominio de Email</label>
    <nameField>
        <label>Prosumer Dominio de Email</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prosumer Dominios de Email</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prosumer_Dominio_de_Email__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Prosumer Dominios de Email</relationshipLabel>
    <relationshipName>Prosumer_Dominios_de_Email</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prosumer_Dominio_de_Email__c/fields/Dominio_Verificado__c.field-meta.xml
<CustomField>
    <fullName>Dominio_Verificado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Para ser tildado por el admin una vez se realiza el proceso de verificacion del dominio.</description>
    <inlineHelpText>Para ser tildado por el admin una vez se realiza el proceso de verificacion del dominio.</inlineHelpText>
    <label>Dominio Verificado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/prosumer_gestor_dominiosController.cls
public class prosumer_gestor_dominiosController {
    @AuraEnabled
    public static List<Prosumer_Dominio_de_Email__c> getDominios(){
        Id accountId = Prosumer_AudienciaPageController.getAccountFromUser();
        return [SELECT Dominio_Verificado__c, id, Name FROM Prosumer_Dominio_de_Email__c WHERE Account__c =: accountId];
    }

    @AuraEnabled
    public static Prosumer_Dominio_de_Email__c insertDominio(String dominio){
        Id accountId = Prosumer_AudienciaPageController.getAccountFromUser();
        Prosumer_Dominio_de_Email__c nuevoDominio = new Prosumer_Dominio_de_Email__c();
        nuevoDominio.Account__c = accountId;
        nuevoDominio.Name = dominio;
        insert nuevoDominio;
        return nuevoDominio;
    }

    @AuraEnabled
    public static boolean deleteDominio(Id idDominio){
        Prosumer_Dominio_de_Email__c nuevoDominio = new Prosumer_Dominio_de_Email__c();
        nuevoDominio.id = idDominio;
        delete nuevoDominio;
        return true;
    }
}