force-app/main/default/objects/Datos_de_territorio__c/Datos_de_territorio__c.object-meta.xml
<CustomObject>
    <label>Territory Data</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Territory Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territory Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Datos_de_territorio__c/fields/Economic_Activities__c.field-meta.xml
<CustomField>
    <fullName>Economic_Activities__c</fullName>
    <defaultValue>(&quot;{}&quot;)</defaultValue>
    <label>Economic_Activities</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Datos_de_territorio__c/fields/Education_Level_Primary__c.field-meta.xml
<CustomField>
    <fullName>Education_Level_Primary__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Education_Level_Primary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Datos_de_territorio__c/fields/Education_Level_Secondary__c.field-meta.xml
<CustomField>
    <fullName>Education_Level_Secondary__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Education_Level_Secondary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Datos_de_territorio__c/fields/Education_Level_Tertiary__c.field-meta.xml
<CustomField>
    <fullName>Education_Level_Tertiary__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Education_Level_Tertiary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Datos_de_territorio__c/fields/Education_Level_University_Degree__c.field-meta.xml
<CustomField>
    <fullName>Education_Level_University_Degree__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Education_Level_University_Degree</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Datos_de_territorio__c/fields/Income_Range_High__c.field-meta.xml
<CustomField>
    <fullName>Income_Range_High__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Income_Range_High</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Datos_de_territorio__c/fields/Income_Range_Low__c.field-meta.xml
<CustomField>
    <fullName>Income_Range_Low__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Income_Range_Low</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Datos_de_territorio__c/fields/Income_Range_Medium__c.field-meta.xml
<CustomField>
    <fullName>Income_Range_Medium__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Income_Range_Medium</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Datos_de_territorio__c/fields/Income_Range_Very_High__c.field-meta.xml
<CustomField>
    <fullName>Income_Range_Very_High__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Income_Range_Very_High</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Datos_de_territorio__c/fields/Income_Range_Very_Low__c.field-meta.xml
<CustomField>
    <fullName>Income_Range_Very_Low__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Income_Range_Very_Low</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Datos_de_territorio__c/fields/Occupation_Not_Declared__c.field-meta.xml
<CustomField>
    <fullName>Occupation_Not_Declared__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Occupation_Not_Declared</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Datos_de_territorio__c/fields/Occupation_Retired__c.field-meta.xml
<CustomField>
    <fullName>Occupation_Retired__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Occupation_Retired</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Datos_de_territorio__c/fields/Occupation_Self_Employed__c.field-meta.xml
<CustomField>
    <fullName>Occupation_Self_Employed__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Occupation_Self_Employed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Datos_de_territorio__c/fields/Occupation_Wage_Earned__c.field-meta.xml
<CustomField>
    <fullName>Occupation_Wage_Earned__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Occupation_Wage_Earned</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Datos_de_territorio__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>Territorio_Administrativo__c</referenceTo>
    <relationshipLabel>Territory Data</relationshipLabel>
    <relationshipName>Territory_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/Territorio_Administrativo__c.object-meta.xml
<CustomObject>
    <description>Objeto Custom para carga de Territorios de multiples paises, estructurado en 5 niveles</description>
    <label>Territorio</label>
    <nameField>
        <label>Territorio Administrativo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territorios</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/TerritoryDataBatch_ClearFileds.cls
global class TerritoryDataBatch_ClearFileds implements Database.Batchable<sObject>,Database.Stateful {
    public Boolean doChain;

    global TerritoryDataBatch_ClearFileds() {
        this.doChain = true;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){

        return Database.getQueryLocator([SELECT Id, (SELECT id, gender__c FROM Territory_Data__r) FROM Territorio_Administrativo__c]);

    }

    global void execute(Database.BatchableContext BC, List<Territorio_Administrativo__c> scope){
        Set<Id> territoryDataRecordsToClearIds = new Set<Id> ();

        insertMissingTerritoryData(scope);

        clearOldTerritoryData(scope);

    }

    global void finish(Database.BatchableContext BC) {
        //call batch que empieze a actualizar los territorios a los que los citizens pertenezcan. TerritoryBatch_AcumCitizens
        if(this.doChain) {
            List<id> argentinaLvl2TerritoriesIds = TerritoryDataBatch_AcumCitizens.getSetOfLevel2ZonesForArgentina();
            TerritoryDataBatch_AcumCitizens batch = new TerritoryDataBatch_AcumCitizens(argentinaLvl2TerritoriesIds);
            database.executeBatch(batch, 2000);
        }
    }

    private static void insertMissingTerritoryData (List<Territorio_Administrativo__c> scope) {
        Map<Id, List<String>> missingTerritoryDataByTerritoryId = new Map<Id, List<String>> ();
        //put(territoryId,['M','F']) en caso que falten los 2

        for(Territorio_Administrativo__c thisTerritory : scope) {
            List<String> thisTerritoryMissingData = getMissingGenders(thisTerritory);

            if(thisTerritoryMissingData.size() != 0){
                missingTerritoryDataByTerritoryId.put(thisTerritory.id,thisTerritoryMissingData);
            }

        }


        if(!missingTerritoryDataByTerritoryId.isEmpty()){
            List<Datos_de_territorio__c> territoryDataToInsert = new List<Datos_de_territorio__c> ();

            for(Id thisId : missingTerritoryDataByTerritoryId.keySet()){
                List<String> missingDataGenders = missingTerritoryDataByTerritoryId.get(thisId);
                if(missingDataGenders.contains('M')){
                    territoryDataToInsert.add(
                        new Datos_de_territorio__c(
                            Territory__c = thisId,
                            gender__c = 'M'
                        )
                    );
                }

                if(missingDataGenders.contains('F')){
                    territoryDataToInsert.add(
                        new Datos_de_territorio__c(
                            Territory__c = thisId,
                            gender__c = 'F'
                        )
                    );
                }
            }

            insert territoryDataToInsert;
        }
    }

    private static List<String> getMissingGenders (Territorio_Administrativo__c territory) {
        List<String> missingGenders = new List<String> ();
        Boolean maleMissing = true;
        Boolean femaleMissing = true;

        if(territory.Territory_Data__r.size() == 0){
            missingGenders.add('M');
            missingGenders.add('F');
            return missingGenders;
        }

        for(Datos_de_territorio__c thisData : territory.Territory_Data__r){
            if(thisData.Gender__c == 'M'){
                maleMissing = false;
            }
            if(thisData.Gender__c == 'F'){
                femaleMissing = false;
            }
        }
        if(maleMissing){
            missingGenders.add('M');
        }
        if(femaleMissing){
            missingGenders.add('F');
        }
        return missingGenders;
    }

    private static void clearOldTerritoryData (List<Territorio_Administrativo__c> scope) {
        List<Datos_de_territorio__c> territoryDataToClear = new List<Datos_de_territorio__c>();

        for(Territorio_Administrativo__c thisTerritorio : scope){
            for(Datos_de_territorio__c thisTerritoryData : thisTerritorio.Territory_Data__r){
                territoryDataToClear.add(getClearTerritoryDataRecord(thisTerritoryData));
            }
        }
        if(territoryDataToClear.size() != 0){
            Update territoryDataToClear;
        }
    }

    private static Datos_de_territorio__c getClearTerritoryDataRecord (Datos_de_territorio__c recordToClear) {
        //me aseguro de mantener el genero, lookup, id y cosas asi si modificar en memoria el objeto en scope 
        Datos_de_territorio__c clearedRecord = recordToClear.clone(true, false, false, false);
        
        clearedRecord.Economic_Activities__c = '{}';

        clearedRecord.Income_Range_High__c = 0;
        clearedRecord.Income_Range_Low__c = 0;
        clearedRecord.Income_Range_Medium__c = 0;
        clearedRecord.Income_Range_Very_High__c = 0;
        clearedRecord.Income_Range_Very_Low__c = 0;

        clearedRecord.Occupation_Not_Declared__c = 0;
        clearedRecord.Occupation_Retired__c = 0;
        clearedRecord.Occupation_Self_Employed__c = 0;
        clearedRecord.Occupation_Wage_Earned__c = 0;

        clearedRecord.Education_Level_Primary__c = 0;
        clearedRecord.Education_Level_Secondary__c = 0;
        clearedRecord.Education_Level_Tertiary__c = 0;
        clearedRecord.Education_Level_University_Degree__c = 0;

        return clearedRecord;
    }
}