force-app/main/default/objects/Account/fields/Cantidad_Creditos__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_Creditos__c</fullName>
    <label>Cantidad Creditos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campania__c/Campania__c.object-meta.xml
<CustomObject>
    <label>Campania</label>
    <nameField>
        <label>Campania Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campanias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Campania__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Campañas</relationshipLabel>
    <relationshipName>Campanias</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Creditos_Campania__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Creditos_Campania__c</fullName>
    <label>Prosumer Creditos Campaña</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Cuenta_Cliente__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Cuenta_Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prosumer Cuenta Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campanias</relationshipLabel>
    <relationshipName>Campanias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Fecha_de_Finalizacion__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Fecha_de_Finalizacion__c</fullName>
    <label>Prosumer Fecha de Finalizacion</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Fecha_de_Inicio__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Fecha_de_Inicio__c</fullName>
    <description>Fecha de creacion de la campaña. Cuando le dan aceptar al formulario.</description>
    <label>Prosumer Fecha de Inicio</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Filtros_Audiencia__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Filtros_Audiencia__c</fullName>
    <label>Prosumer Filtros Audiencia</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Hora_de_Finalizacion__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Hora_de_Finalizacion__c</fullName>
    <label>Prosumer Hora de Finalizacion</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Hora_de_Inicio__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Hora_de_Inicio__c</fullName>
    <label>Prosumer Hora de Inicio</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Mensaje_Audio__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Mensaje_Audio__c</fullName>
    <label>Prosumer Mensaje Audio</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Mensaje_SMS__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Mensaje_SMS__c</fullName>
    <label>Prosumer Mensaje SMS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Moviles_en_Audiencia__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Moviles_en_Audiencia__c</fullName>
    <label>Prosumer Moviles en Audiencia</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_SAQL_Audiencias__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_SAQL_Audiencias__c</fullName>
    <label>Prosumer SAQL Audiencias</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Tamanio_de_Audiencia__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Tamanio_de_Audiencia__c</fullName>
    <description>Cantidad de personas que hay en la audiencia.</description>
    <label>Prosumer Tamaño de Audiencia</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Proyecto</label>
    <nameField>
        <label>Proyecto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proyectos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Prosumer_audience_controller.cls
public without sharing class Prosumer_audience_controller {
    @AuraEnabled
    public static boolean consumeCredits(Decimal totalOfMobiles){
        Map<String, Decimal> values = Prosumer_AudienciaPageController.getUserCreditInformation();
        Decimal creditsToConsume = values.get('sms_cost') * totalOfMobiles;
        Boolean enoughCredits = values.get('accountCredits') >= creditsToConsume;

        if(!enoughCredits){ return false;}

        Account acc = [SELECT Cantidad_Creditos__c FROM account WHERE id = :Prosumer_AudienciaPageController.getAccountFromUser()];
        acc.Cantidad_Creditos__c = acc.Cantidad_Creditos__c - creditsToConsume;
        update acc;

        return true;
    }

    @AuraEnabled
    public static Id createCampaing(String titulo, String saql, String filtros, String msj, Integer costo, Integer moviles, Integer personas){
        try {
            Campania__c campania = new Campania__c ();
            campania.name = titulo;
            campania.Prosumer_SAQL_Audiencias__c = saql;
            campania.Prosumer_Filtros_Audiencia__c = filtros;
            campania.Prosumer_Mensaje_SMS__c = msj;
            campania.Prosumer_Creditos_Campania__c = costo;
            campania.Prosumer_Moviles_en_Audiencia__c = moviles;
            campania.Prosumer_Tamanio_de_Audiencia__c = personas;
            campania.Prosumer_Cuenta_Cliente__c = Prosumer_AudienciaPageController.getAccountFromUser();
            campania.Prosumer_Fecha_de_Inicio__c = Datetime.now();
            campania.Project__c = getProject('ProsumerSMS');
            insert campania;
            return campania.id;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static Id createCampaignIVR(String titulo, String saql, String filtros, String audiofileid, Integer costo, Integer moviles, Integer personas, Datetime fecha_inicio, Datetime fecha_finalizacion, String hora_inicio, String hora_finalizacion){
        try {
            Campania__c campania = new Campania__c ();
            campania.name = titulo;
            campania.Prosumer_SAQL_Audiencias__c = saql;
            campania.Prosumer_Filtros_Audiencia__c = filtros;
            campania.Prosumer_Mensaje_Audio__c = audiofileid;
            campania.Prosumer_Creditos_Campania__c = costo;
            campania.Prosumer_Moviles_en_Audiencia__c = moviles;
            campania.Prosumer_Tamanio_de_Audiencia__c = personas;
            campania.Prosumer_Cuenta_Cliente__c = Prosumer_AudienciaPageController.getAccountFromUser();
            // campania.Prosumer_Fecha_de_Inicio__c = Datetime.now();
            campania.Prosumer_Fecha_de_Inicio__c = fecha_inicio;
            campania.Prosumer_Fecha_de_Finalizacion__c = fecha_finalizacion;
            campania.Prosumer_Hora_de_Inicio__c = hora_inicio;
            campania.Prosumer_Hora_de_Finalizacion__c = hora_finalizacion;
            campania.Project__c = getProject('ProsumerIVR');
            insert campania;
            return campania.id;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @testVisible
    private static Id getProject (String projectName) {
        List<Project__c> proyects = [SELECT id FROM Project__c WHERE NAME =:projectName];
        if(proyects.size() != 0){
            return proyects[0].id;
        }

        Project__c pj = new Project__c ();
        pj.name = projectName;
        insert pj;
        return pj.id;
    }
}