force-app/main/default/objects/Account/fields/Cantidad_Creditos__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_Creditos__c</fullName>
    <label>Cantidad Creditos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campania__c/Campania__c.object-meta.xml
<CustomObject>
    <label>Campania</label>
    <nameField>
        <label>Campania Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campanias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Campania__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Campañas</relationshipLabel>
    <relationshipName>Campanias</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_cantidad_emails__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_cantidad_emails__c</fullName>
    <label>Prosumer cantidad emails</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Creditos_Campania__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Creditos_Campania__c</fullName>
    <label>Prosumer Creditos Campaña</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Cuenta_Cliente__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Cuenta_Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prosumer Cuenta Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campanias</relationshipLabel>
    <relationshipName>Campanias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Email__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Email__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prosumer Email</label>
    <referenceTo>Prosumer_Email__c</referenceTo>
    <relationshipLabel>Campanias</relationshipLabel>
    <relationshipName>Campanias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Email_Asunto_Campania__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Email_Asunto_Campania__c</fullName>
    <label>Prosumer Email Asunto Campaña</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Email_Remitente_Email__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Email_Remitente_Email__c</fullName>
    <label>Prosumer Email Remitente Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Email_Remitente_Nombre__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Email_Remitente_Nombre__c</fullName>
    <label>Prosumer Email Remitente Nombre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Fecha_de_Inicio__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Fecha_de_Inicio__c</fullName>
    <description>Fecha de creacion de la campaña. Cuando le dan aceptar al formulario.</description>
    <label>Prosumer Fecha de Inicio</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Filtros_Audiencia__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Filtros_Audiencia__c</fullName>
    <label>Prosumer Filtros Audiencia</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_SAQL_Audiencias__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_SAQL_Audiencias__c</fullName>
    <label>Prosumer SAQL Audiencias</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Tamanio_de_Audiencia__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Tamanio_de_Audiencia__c</fullName>
    <description>Cantidad de personas que hay en la audiencia.</description>
    <label>Prosumer Tamaño de Audiencia</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Proyecto</label>
    <nameField>
        <label>Proyecto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proyectos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prosumer_Email__c/Prosumer_Email__c.object-meta.xml
<CustomObject>
    <label>Prosumer Email</label>
    <nameField>
        <label>Prosumer Email Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prosumer Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Prosumer_audience_emailController.cls
public class Prosumer_audience_emailController {
    @AuraEnabled
    public static boolean consumeCredits(Decimal totalOfMobiles){
        Map<String, Decimal> values = Prosumer_AudienciaPageController.getUserCreditInformation();
        Decimal creditsToConsume = values.get('email_cost') * totalOfMobiles;
        Boolean enoughCredits = values.get('accountCredits') >= creditsToConsume;

        if(!enoughCredits){ return false;}

        Account acc = [SELECT Cantidad_Creditos__c FROM account WHERE id = :Prosumer_AudienciaPageController.getAccountFromUser()];
        acc.Cantidad_Creditos__c = acc.Cantidad_Creditos__c - creditsToConsume;
        update acc;

        return true;
    }

    @AuraEnabled
    public static Id createCampaing(String titulo, String saql, String filtros, 
                            Id emailId, Integer costo, Integer cantidadEmails, Integer personas, 
                            String asuntoCampania, String nombreRemitente, String emailRemitente){
            Campania__c campania = new Campania__c ();
            campania.name = titulo;
            campania.Prosumer_SAQL_Audiencias__c = saql;
            campania.Prosumer_Filtros_Audiencia__c = filtros;
            campania.Prosumer_email__c = emailId;
            campania.Prosumer_Creditos_Campania__c = costo;
            campania.Prosumer_cantidad_emails__c = cantidadEmails;
            campania.Prosumer_Tamanio_de_Audiencia__c = personas;
            campania.Prosumer_Cuenta_Cliente__c = Prosumer_AudienciaPageController.getAccountFromUser();
            campania.Prosumer_Fecha_de_Inicio__c = Datetime.now();
            campania.Project__c = getProject('ProsumerEmail');
            campania.Prosumer_Email_Asunto_Campania__c = asuntoCampania;
            campania.Prosumer_Email_Remitente_Nombre__c = nombreRemitente;
            campania.Prosumer_Email_Remitente_Email__c = emailRemitente;
            insert campania;
            return campania.id;
    }

    @testVisible
    private static Id getProject (String projectName) {
        List<Project__c> proyects = [SELECT id FROM Project__c WHERE NAME =:projectName];
        if(proyects.size() != 0){
            return proyects[0].id;
        }

        Project__c pj = new Project__c ();
        pj.name = projectName;
        insert pj;
        return pj.id;
    }
}