force-app/main/default/objects/Account/fields/Cantidad_Creditos__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_Creditos__c</fullName>
    <label>Cantidad Creditos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Creditos_Email__c.field-meta.xml
<CustomField>
    <fullName>Creditos_Email__c</fullName>
    <label>Creditos Email</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Creditos_IVR__c.field-meta.xml
<CustomField>
    <fullName>Creditos_IVR__c</fullName>
    <label>Creditos IVR</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Creditos_SMS__c.field-meta.xml
<CustomField>
    <fullName>Creditos_SMS__c</fullName>
    <label>Creditos SMS</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/SAQL_Sharing_Criteria__c.field-meta.xml
<CustomField>
    <fullName>SAQL_Sharing_Criteria__c</fullName>
    <label>SAQL Sharing Criteria</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Campania__c/Campania__c.object-meta.xml
<CustomObject>
    <label>Campania</label>
    <nameField>
        <label>Campania Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campanias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Campania__c/fields/Prosumer_Email__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Email__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prosumer Email</label>
    <referenceTo>Prosumer_Email__c</referenceTo>
    <relationshipLabel>Campanias</relationshipLabel>
    <relationshipName>Campanias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prosumer_Email__c/Prosumer_Email__c.object-meta.xml
<CustomObject>
    <label>Prosumer Email</label>
    <nameField>
        <label>Prosumer Email Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prosumer Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Prosumer_audience_emailControllerTest.cls
@isTest
public class Prosumer_audience_emailControllerTest {
    @isTest
    public static void testConsumeCredits() {
        Account acc = new Account ();
        acc.name = 'PROSUMER ADMINS DEFAULT ACCOUNT';
        acc.SAQL_Sharing_Criteria__c = '(\'CI_Asalariado\' == 1 || \'CI_Cuentapropista\' == 1)';
        acc.Cantidad_Creditos__c = 10;
        acc.Creditos_Email__c = 1;
        acc.Creditos_IVR__c = 1;
        acc.Creditos_SMS__c = 1;
        
        insert acc;

        System.assertEquals(false, Prosumer_audience_emailController.consumeCredits (11), 'NO deberia poder consumir mas creditos de los que tiene disponibles');
        System.assertEquals(true, Prosumer_audience_emailController.consumeCredits (8), 'Deberia retornar true si fue capaz de consumir los creditos');
        Account updatedAcc = [SELECT Cantidad_Creditos__c FROM account WHERE id =:  acc.id];
        System.assertEquals(2, updatedAcc.Cantidad_Creditos__c, 'Luego de consumir 8 creditos deben restarle 2');
    }

    @isTest
    public static void testCreateCampaing() {
        Prosumer_email__c emailRecord = new Prosumer_email__c();
        emailRecord.name = 'test';
        insert emailRecord;

        //String titulo, String saql, String filtros, 
        //Id emailId, Integer costo, Integer cantidadEmails, Integer personas, 
        //String asuntoCampania, String nombreRemitente, String emailRemitente

        Prosumer_audience_emailController.createCampaing('String titulo', 'String saql', 'String filtros',
                                                                emailRecord.Id, 5, 5, 5,
                                                                'asunto', 'nombre', 'email@test.com');
        
        List<Campania__c> campanias = [SELECT id FROM Campania__c WHERE name = 'String titulo'];

        System.assertEquals(1, campanias.size(), 'Debe haberse creado la campaña');
    }
}