force-app/main/default/objects/Account/fields/Cantidad_Creditos__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_Creditos__c</fullName>
    <label>Cantidad Creditos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Creditos_Email__c.field-meta.xml
<CustomField>
    <fullName>Creditos_Email__c</fullName>
    <label>Creditos Email</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Creditos_IVR__c.field-meta.xml
<CustomField>
    <fullName>Creditos_IVR__c</fullName>
    <label>Creditos IVR</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Creditos_SMS__c.field-meta.xml
<CustomField>
    <fullName>Creditos_SMS__c</fullName>
    <label>Creditos SMS</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Prosumer_Sharing_Id__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Sharing_Id__c</fullName>
    <label>Prosumer Sharing Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SAQL_Sharing_Criteria__c.field-meta.xml
<CustomField>
    <fullName>SAQL_Sharing_Criteria__c</fullName>
    <label>SAQL Sharing Criteria</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sharing_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Sharing_Criteria__c</fullName>
    <label>Sharing Criteria</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/Prosumer_AudienciaPageControllerTest.cls
@isTest
public class Prosumer_AudienciaPageControllerTest {
    @isTest
    public static void testGetProsumerAudienciaCriteria(){
        //el SAQL_Sharing_Criteria__c es el importante
        Account acc = new Account ();
        acc.name = 'PROSUMER ADMINS DEFAULT ACCOUNT';
        acc.SAQL_Sharing_Criteria__c = '(\'CI_Asalariado\' == 1 || \'CI_Cuentapropista\' == 1)';
        acc.Cantidad_Creditos__c = 10;
        acc.Creditos_Email__c = 1;
        acc.Creditos_IVR__c = 1;
        acc.Creditos_SMS__c = 1;
        acc.Prosumer_Sharing_Id__c = 'A1';
        acc.Sharing_Criteria__c = 'String, not being used really.';
        
        insert acc;

        Prosumer_AudienciaPageController.getProsumerAudienceCriterias();
    }

    @isTest
    public static void testGetProsumerAudienciaCriteria_sinCuentaPrevia(){
        //si la cuenta no existe debe crearla
        Prosumer_AudienciaPageController.getProsumerAudienceCriterias();
    }

    @isTest
    public static void testGetUserCreditInformation(){
        //el SAQL_Sharing_Criteria__c es el importante
        Account acc = new Account ();
        acc.name = 'PROSUMER ADMINS DEFAULT ACCOUNT';
        acc.SAQL_Sharing_Criteria__c = '(\'CI_Asalariado\' == 1 || \'CI_Cuentapropista\' == 1)';
        acc.Cantidad_Creditos__c = 10;
        acc.Creditos_Email__c = 1;
        acc.Creditos_IVR__c = 1;
        acc.Creditos_SMS__c = 1;
        acc.Prosumer_Sharing_Id__c = 'A1';
        acc.Sharing_Criteria__c = 'String, not being used really.';
        
        insert acc;

        Prosumer_AudienciaPageController.getUserCreditInformation();
    }
}