force-app/main/default/objects/Survey_Available_Option__c/Survey_Available_Option__c.object-meta.xml
<CustomObject>
    <label>Survey Available Option</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Survey Available Options Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Available Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Survey__c/User_Survey__c.object-meta.xml
<CustomObject>
    <label>User Survey</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>User Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Users Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Survey__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Lead.RecordTypeId</field>
            <operation>equals</operation>
            <value>PulsoCRM</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Users Surveys</relationshipLabel>
    <relationshipName>Users_Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Survey__c/fields/Number_Of_Answered_Questions__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Answered_Questions__c</fullName>
    <label>Number_Of_Answered_Questions</label>
    <summaryForeignKey>User_Survey_Answers__c.User_Survey__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/User_Survey__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>Encuesta__c</referenceTo>
    <relationshipLabel>Users Surveys</relationshipLabel>
    <relationshipName>Users_Surveys</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/User_Survey_Answers__c/User_Survey_Answers__c.object-meta.xml
<CustomObject>
    <label>User Survey Answers</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>User Survey Answers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Survey Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Survey_Answers__c/fields/Survey_Available_Option__c.field-meta.xml
<CustomField>
    <fullName>Survey_Available_Option__c</fullName>
    <label>Survey Available Option</label>
    <referenceTo>Survey_Available_Option__c</referenceTo>
    <relationshipLabel>User Survey Answers</relationshipLabel>
    <relationshipName>User_Survey_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Survey_Answers__c/fields/User_Survey__c.field-meta.xml
<CustomField>
    <fullName>User_Survey__c</fullName>
    <label>User Survey</label>
    <referenceTo>User_Survey__c</referenceTo>
    <relationshipLabel>User Survey Answers</relationshipLabel>
    <relationshipName>User_Survey_Answers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/pulso_admin_generar_audiencia_test.cls
@isTest
private class pulso_admin_generar_audiencia_test { 
    @testSetup 
    static void setup() {
		CommonTestFunctions testSet = new CommonTestFunctions();
		testSet.createNewSurveyForTest();
    }

    static testmethod void test() {        
        Test.setMock(HttpCalloutMock.class, new RESTMock());
        Test.startTest();
        
        List<User_Survey__c> usersAnswers = new List<User_Survey__c>();
        usersAnswers = [SELECT Id, Survey__c, Lead__c
                   FROM User_Survey__c
                   WHERE Number_Of_Answered_Questions__c > 0
                   LIMIT 2];
        System.debug('DAC: ' + usersAnswers);
        
        ID surveyId = usersAnswers[0].Survey__c;
        ID userId = usersAnswers[0].Lead__c;
        ID user_survey_id = usersAnswers[0].Id;
        
        List<User_Survey_Answers__c> answers = new List<User_Survey_Answers__c>();
        answers = [SELECT Survey_Available_Option__c
                   FROM User_Survey_Answers__c
                   WHERE User_Survey__c = :user_survey_id];
        
        List<String> questionsIds = new List<String>();
        for (User_Survey_Answers__c ans : answers) {
            questionsIds.add((String)ans.Survey_Available_Option__c);
        }
        
        String dataExtension = 'dataExtensionForTest';
        pulso_admin_generar_audiencia genAud = new pulso_admin_generar_audiencia(surveyId, questionsIds, dataExtension);
        Id batchId = Database.executeBatch(genAud);
        
        Test.stopTest();
        
        // after the testing stops, assert records were updated properly
        System.assertEquals(1, 1);
    }
    
}