force-app/main/default/objects/Survey_Available_Option__c/Survey_Available_Option__c.object-meta.xml
<CustomObject>
    <label>Survey Available Option</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Survey Available Options Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Available Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Survey__c/User_Survey__c.object-meta.xml
<CustomObject>
    <label>User Survey</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>User Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Users Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Survey__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Lead.RecordTypeId</field>
            <operation>equals</operation>
            <value>PulsoCRM</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Users Surveys</relationshipLabel>
    <relationshipName>Users_Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Survey__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>Encuesta__c</referenceTo>
    <relationshipLabel>Users Surveys</relationshipLabel>
    <relationshipName>Users_Surveys</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/User_Survey_Answers__c/User_Survey_Answers__c.object-meta.xml
<CustomObject>
    <label>User Survey Answers</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>User Survey Answers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Survey Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Survey_Answers__c/fields/Survey_Available_Option__c.field-meta.xml
<CustomField>
    <fullName>Survey_Available_Option__c</fullName>
    <label>Survey Available Option</label>
    <referenceTo>Survey_Available_Option__c</referenceTo>
    <relationshipLabel>User Survey Answers</relationshipLabel>
    <relationshipName>User_Survey_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Survey_Answers__c/fields/User_Survey__c.field-meta.xml
<CustomField>
    <fullName>User_Survey__c</fullName>
    <label>User Survey</label>
    <referenceTo>User_Survey__c</referenceTo>
    <relationshipLabel>User Survey Answers</relationshipLabel>
    <relationshipName>User_Survey_Answers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/pulso_admin_generar_audiencia.cls
global class pulso_admin_generar_audiencia implements 
Database.Batchable<sObject>, Database.Stateful {
    //Class Constructor 
    global String query;
    global List<String> Ids;
    global String surveyId;
    global String dataExtension;
    global List<String> fields;
    global pulso_admin_generar_audiencia (String xsurveyId, List<String> xoptionsId, String xdataExtension){
        this.Ids = xoptionsId;
        this.surveyId = xsurveyId;
        this.dataExtension = xdataExtension;
        this.fields = new List<String>{'Nombre', 'eMail'};
        
        this.query = 'SELECT Id, Lead__r.FirstName, Lead__r.LastName, ' +
                            '(SELECT ID ' +
                            'FROM User_Survey_Answers__r ' +  
                            'WHERE Survey_Available_Option__c ' + 
                            'IN :Ids)' +
                    'FROM User_Survey__c ' + 
                    'WHERE Survey__c = :surveyId';
        System.debug(this.query);
    }
    
    // instance member to retain state across transactions
    global Integer recordsProcessed = 0;
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(this.query);
    }
    
    global Set<User_Survey__c> surveyUsers = new Set<User_Survey__c>();
    global void execute(Database.BatchableContext bc, List<User_Survey__c> scope) {
        // process each batch of records
        System.debug('Im in the execute function');
        for (User_Survey__c answer : scope) {
            if (answer.User_Survey_Answers__r.size() == Ids.size()) {
                surveyUsers.add(answer);
            }
            System.debug(answer);
            recordsProcessed += 1;
        }
    }
    
    global void finish(Database.BatchableContext bc) {
        System.debug(recordsProcessed + ' records processed!');
        System.debug('Set size = ' + surveyUsers.size());
        SendNuevaAudienciaToMC audiencia = new SendNuevaAudienciaToMC(dataExtension, surveyId, surveyUsers, fields);
        ID jobID = System.enqueueJob(audiencia);
    }
    
}