force-app/main/default/objects/Community_Config__mdt/Community_Config__mdt.object-meta.xml
<CustomObject>
    <label>Community Config</label>
    <pluralLabel>Communities Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Community_Config__mdt/fields/Login_Footer_Title__c.field-meta.xml
<CustomField>
    <fullName>Login_Footer_Title__c</fullName>
    <description>Titulo del footer de la pagina de login. El texto que aparece al lado de la bandera.</description>
    <inlineHelpText>Titulo del footer de la pagina de login. El texto que aparece al lado de la bandera.</inlineHelpText>
    <label>Login Footer Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Community_Config__mdt/fields/Login_Tab_Title__c.field-meta.xml
<CustomField>
    <fullName>Login_Tab_Title__c</fullName>
    <description>Titulo que aparece arriba en la tab, de la pagina vf de login.</description>
    <inlineHelpText>Titulo que aparece arriba en la tab, de la pagina vf de login.</inlineHelpText>
    <label>Login Tab Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Community_Config__mdt/fields/Static_Resourse_Name_FavIcon__c.field-meta.xml
<CustomField>
    <fullName>Static_Resourse_Name_FavIcon__c</fullName>
    <description>Nombre del recurso estatico con el favIcon. La metadata solo se utiliza en la vf de login de la comunidad por ahora.</description>
    <inlineHelpText>Nombre del recurso estatico con el favIcon. La metadata solo se utiliza en la vf de login de la comunidad por ahora.</inlineHelpText>
    <label>Static Resourse Name - FavIcon</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Community_Config__mdt/fields/Static_Resourse_Name_ZipBundle__c.field-meta.xml
<CustomField>
    <fullName>Static_Resourse_Name_ZipBundle__c</fullName>
    <description>Nombre del recurso con la carpeta con los recursos de la comunidad. Por ahora, la pagina de login solo va a buscar la bandera que se muestra en el footer.</description>
    <inlineHelpText>Nombre del recurso con la carpeta con los recursos de la comunidad. Por ahora, la pagina de login solo va a buscar la bandera que se muestra en el footer.</inlineHelpText>
    <label>Static Resourse Name - ZipBundle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CommunityAuthController.cls
public class CommunityAuthController {
    // global CommunityAuthController() {}
    public String username {get; set;}
    public String password {get; set;}

    public String tabTitle {get; set;}
    public String favIconName {get; set;}
    public String zipBundle {get; set;}
    public String footerTitle {get; set;}

    public PageReference doLogin() {
        String startUrl = System.currentPageReference().getParameters().get('startURL');
        return Site.login(username, password, startUrl);
    }

    public CommunityAuthController() {
        Community_Config__mdt communityConfig = HelperFunctions.retrieveCommunitySettings();
        this.tabTitle = communityConfig?.Login_Tab_Title__c;
        this.favIconName = communityConfig?.Static_Resourse_Name_FavIcon__c;
        this.zipBundle = communityConfig?.Static_Resourse_Name_ZipBundle__c;
        this.footerTitle = communityConfig?.Login_Footer_Title__c;
    }
    
    /*@AuraEnabled(cacheable=true)
    public static String communityLogin(String username, String password){
        String startUrl = System.currentPageReference().getParameters().get('startURL');
        ApexPages.PageReference pageRef = Site.login(username, password, startUrl);
		return pageRef.getParameters().get('startURL');
    }*/
    
    /*@AuraEnabled(cacheable=true)
    public static String communityLogin(String username, String password, String startURL){
        ApexPages.PageReference pageRef = Site.login(username, password, startUrl);
		return startURL;
    }*/
}