force-app/main/default/objects/Message__c/Message__c.object-meta.xml
<CustomObject>
    <label>Message</label>
    <nameField>
        <label>Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Message__c/fields/TotalsSent__c.field-meta.xml
<CustomField>
    <fullName>TotalsSent__c</fullName>
    <label>TotalsSent</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Response__c/Response__c.object-meta.xml
<CustomObject>
    <label>Response</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Response__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <referenceTo>Message__c</referenceTo>
    <relationshipLabel>Responses</relationshipLabel>
    <relationshipName>Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Response__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SMS_Response__c/SMS_Response__c.object-meta.xml
<CustomObject>
    <label>SMS Response</label>
    <nameField>
        <displayFormat>SMS-{000000}</displayFormat>
        <label>SMS Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SMS_Response__c/fields/destino__c.field-meta.xml
<CustomField>
    <fullName>destino__c</fullName>
    <label>destino</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Response__c/fields/fecha__c.field-meta.xml
<CustomField>
    <fullName>fecha__c</fullName>
    <label>fecha</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Response__c/fields/mensaje__c.field-meta.xml
<CustomField>
    <fullName>mensaje__c</fullName>
    <label>mensaje</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Response__c/fields/origenRotativo__c.field-meta.xml
<CustomField>
    <fullName>origenRotativo__c</fullName>
    <label>origenRotativo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Response__c/fields/telco__c.field-meta.xml
<CustomField>
    <fullName>telco__c</fullName>
    <label>telco</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SondeosRESTMO.cls
@RestResource(urlMapping='/sondeos/mo/*')
global  class SondeosRESTMO {
    @HttpGet 
    global static String isAlive() {
        return 'isAlive!';
    }

    @HttpPost
    global static void updateResponse() {
        RemotingMessageHelper.SondeosMO objRequest = null;
        
        System.debug('updateResponse [RestContext.request.requestBody : ' + RestContext.request.requestBody + '] ->');
        
        if(RestContext.request.requestBody != NULL) {
            objRequest = (RemotingMessageHelper.SondeosMO) JSON.deserialize(RestContext.request.requestBody.toString(), RemotingMessageHelper.SondeosMO.class);
            System.debug('updateResponse [RestContext.request.requestBody.toString() : ' + RestContext.request.requestBody.toString() + ' ]');        
            System.debug('updateResponse [objRequest : ' + objRequest + ' ]');        


            if(objRequest != NULL && objRequest.parameters != NULL) {
                updateResponse(objRequest.parameters.origen, objRequest.parameters.origenRotativo, objRequest.parameters.destino, objRequest.parameters.telco, objRequest.parameters.fecha, objRequest.parameters.mensaje, objRequest.parameters.customerId);
            }
        } else {
            System.debug('updateResponse [REQUEST IS NULL]');        
        }

        System.debug('updateResponse [] <-');
    }

    global static void updateResponse(Long origen, Long origenRotativo, Long destino, String telco, String fecha, String mensaje, String customerId ) {
        RemotingMessageHelper.Sondeos objSondeos = null;
        SMS_Response__c objSMSResponse = null;
        Response__c objResponse = null;
        RestResponse objRESTResponse = null;
        RemotingMessageHelper.OperationResult objResult = null;

        System.debug('updateResponse[origen : ' + origen + ' - origenRotativo : ' + origenRotativo + ' - destino : ' + destino + ' - telco : ' + telco + ' - fecha : ' + fecha + ' - mensaje : ' + mensaje + ' - customerId : ' + customerId + ' ] ->');

        try {
            objResult = new RemotingMessageHelper.OperationResult();
            objRESTResponse = RestContext.response;

            objSMSResponse = new SMS_Response__c();
            objSMSResponse.origen__c = String.valueOf(origen);
            objSMSResponse.origenRotativo__c = String.valueOf(origenRotativo);
            objSMSResponse.destino__c = String.valueOf(destino);
            objSMSResponse.telco__c = telco;
            objSMSResponse.fecha__c = fecha;
            objSMSResponse.mensaje__c = mensaje;
            
            insert objSMSResponse;

            objResponse = new Response__c();
            objResponse.Message__c = customerId;
            objResponse.Response__c = mensaje;

            insert objResponse;

            objResult.Code = 0;
            objResult.Message = 'OK';

            objRESTResponse.statusCode = 200;
            objRESTResponse.responseBody = Blob.valueOf(JSON.serialize(objResult)); 
        } catch(Exception Ex) {
            objResult.Code = 999;
            objResult.Message = Ex.getMessage();

            objRESTResponse.statusCode = 500;
            objRESTResponse.responseBody = Blob.valueOf(JSON.serialize(objResult)); 
        }

        System.debug('updateResponse [ statusCode : ' + objRESTResponse.statusCode + ' ]');
        System.debug('updateResponse [ responseBody : ' + objRESTResponse.responseBody + ' ]');
        System.debug('updateResponse [] <- ');

    }

    @HttpPut
    global static void updateStatistics(String strStatType, String strCampaingId, Integer intSends) {
        Message__c objMessage = null;
        RestResponse objRESTResponse = null;
        RemotingMessageHelper.OperationResult objResult = null;

        System.debug('updateStatistics[strStatType : ' + strStatType + ' - strCampaingId : ' + strCampaingId + ' - intSends : ' + intSends + ' ] ->');

        try {
            objResult = new RemotingMessageHelper.OperationResult();
            objRESTResponse = RestContext.response;

            objMessage = [SELECT TotalsSent__c FROM Message__c WHERE Id =: strCampaingId];
            objMessage.TotalsSent__c = intSends;

            update objMessage;

            objResult.Code = 0;
            objResult.Message = 'OK';

            objRESTResponse.statusCode = 200;
            objRESTResponse.responseBody = Blob.valueOf(JSON.serialize(objResult)); 
        } catch (Exception Ex) {
            objResult.Code = 999;
            objResult.Message = Ex.getMessage();

            objRESTResponse.statusCode = 500;
            objRESTResponse.responseBody = Blob.valueOf(JSON.serialize(objResult)); 

        }
        System.debug('updateStatistics[] <-');
    }
}