force-app/main/default/objects/Survey_Setting__mdt/Survey_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Survey Setting</label>
    <pluralLabel>Survey_Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Survey_Setting__mdt/fields/Facebook_API_Version__c.field-meta.xml
<CustomField>
    <fullName>Facebook_API_Version__c</fullName>
    <label>Facebook API Version</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Setting__mdt/fields/Facebook_Application_Id__c.field-meta.xml
<CustomField>
    <fullName>Facebook_Application_Id__c</fullName>
    <label>Facebook_Application_Id</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Survey_Setting__mdt/fields/Facebook_Pixel_Id__c.field-meta.xml
<CustomField>
    <fullName>Facebook_Pixel_Id__c</fullName>
    <label>Facebook Pixel Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FacebookConnector.cls
public class FacebookConnector {
    public class FacebookConnectorException extends Exception {} 
    public String ApplicationId { get; set; }
    public String PixelId { get; set; }
    public String Version { get; set; }
    
    public FacebookConnector() {       
        System.debug('FacebookConnector [] ->');

        Survey_Setting__mdt objSurveySettings = NULL;
        
        objSurveySettings = HelperFunctions.retrieveSurveySettings('Pulso_CRM');
        if(objSurveySettings != NULL) {
            this.ApplicationId = objSurveySettings.Facebook_Application_Id__c.toPlainString();
            this.Version = objSurveySettings.Facebook_API_Version__c;
            this.PixelId = objSurveySettings.Facebook_Pixel_Id__c;
        } else {
            throw new FacebookConnectorException(Label.FacebookConnector_NoApplicationDefined);
        }
        
        System.debug('FacebookConnector [] <-');
    }
}