force-app/main/default/objects/BatchToTriggerFlow_Query__mdt/BatchToTriggerFlow_Query__mdt.object-meta.xml
<CustomObject>
    <description>Almacena las query string que el batch utilizara para obtener los registros sobre los luego switcheara el campo booleando.</description>
    <label>BatchToTriggerFlow_Query</label>
    <pluralLabel>BatchToTriggerFlow_Querys</pluralLabel>
</CustomObject>

force-app/main/default/objects/BatchToTriggerFlow_Query__mdt/fields/ConfigToUse__c.field-meta.xml
<CustomField>
    <fullName>ConfigToUse__c</fullName>
    <description>El campo define que configuracion va a usar el batch cuando se ejectue. Puede tener 3 valores:
 - TEST: para poder realizar los test. NO BORRAR NI MODIFICAR EL REGISTRO MARCADO COMO TEST. Solo puede existir un registro marcado como TEST.
 - ACTIVO: la configuracion con la cual se ejecutar el batch. Solo puede existir un registro marcado como ACTIVO.
 - Si valor: las configuraciones que no se esten usando se pueden dejar &quot;apagadas&quot; borrando el valor del campo.</description>
    <inlineHelpText>Valores permitidos:
 - TEST
 - ACTIVO
 - en blanco</inlineHelpText>
    <label>ConfigToUse</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Flow_by_batch_Flag__c.field-meta.xml
<CustomField>
    <fullName>Flow_by_batch_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Se utiliza el campo como flag. Un batch puede recorrer hasta 50M de registros, y cambiar el valor del flag en cualquier sentido, de true a false, o de false a true.

Luego, para automatizaciones simples, se pueden crear los flows que hagan falta, que se ejecuten cuando el valor del campo cambie.

Batchs name: BatchToTriggerFlowsTest

Flow names:</description>
    <label>Flow by batch - Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/guid__c.field-meta.xml
<CustomField>
    <fullName>guid__c</fullName>
    <externalId>true</externalId>
    <label>GUID</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchToTriggerFlowsTest.cls
@isTest
public class BatchToTriggerFlowsTest {
  @TestSetup
  static void makeData() {
    Contact c1 = new contact();
    c1.guid__c = 'guid1';
    c1.LastName = 'contact1';
    c1.Flow_by_batch_Flag__c = false;

    insert c1;

    Contact c2 = new contact();
    c2.guid__c = 'guid2';
    c2.LastName = 'contact2';
    c2.Flow_by_batch_Flag__c = true;

    insert c2;

    Contact c3 = new contact();
    c3.guid__c = 'guid3';
    c3.LastName = 'excluido';
    c3.Flow_by_batch_Flag__c = false;

    insert c3;
  }

  @isTest
  static void test_batchProcess() {
    List<BatchToTriggerFlow_Query__mdt> testMtd = [SELECT DeveloperName FROM BatchToTriggerFlow_Query__mdt WHERE ConfigToUse__c = 'TEST'];

    System.assertEquals(
      1,
      testMtd.size(),
      'En la org debe estar creada la metadata de test, obtiene todos los contactos y switchea el campo Flow_by_batch_Flag__c'
    );

    Test.startTest();
    Id batchJobId = Database.executeBatch(new BatchToTriggerFlows('TEST'), 200);
    Test.stopTest();
  }

  @isTest
  static void test_makeCalloutsAndNextBatch() {
    String configToUse = 'TEST';
    String mtdFieldToSwitch = 'Flow_by_batch_Flag__c';
    String mtdFromStatement = 'Contact';
    String mtdWhereStatement = 'LastName != \'excluido\'';
    Decimal mtdBatchSizeStatement = 100;
    Id lastRecordReferenceId = null;

    BatchToTriggerFlowsHelper.BatchState batchState = new BatchToTriggerFlowsHelper.BatchState(
      configToUse,
      mtdFieldToSwitch,
      mtdFromStatement,
      mtdWhereStatement,
      mtdBatchSizeStatement, 
      lastRecordReferenceId
    );

    batchState.bodyRows = '"guidTEst123","true"';

    String nextBatchId = BatchToTriggerFlows.makeCalloutsAndNextBatch(batchState);
    System.assert(
        nextBatchId != null,
      'Si bien no hace los callouts porque tenia problemas en el test, se debe lanzar un batch porque para este batchState no se proceso ningun registro y hay 2 creados'
    );
  }

  @isTest
  static void test_handleTimeOutLogic_withRetry() {
    String configToUse = 'TEST';
    String mtdFieldToSwitch = 'Flow_by_batch_Flag__c';
    String mtdFromStatement = 'Contact';
    String mtdWhereStatement = null;
    Decimal mtdBatchSizeStatement = 100;
    Id lastRecordReferenceId = null;

    BatchToTriggerFlowsHelper.BatchState batchState = new BatchToTriggerFlowsHelper.BatchState(
      configToUse,
      mtdFieldToSwitch,
      mtdFromStatement,
      mtdWhereStatement,
      mtdBatchSizeStatement,
      lastRecordReferenceId
    );

    CalloutException e = new CalloutException();
    e.setMessage('Read timed out');
    String scheduledJobId = BatchToTriggerFlows.handleTimeOutLogic(batchState, e);
    System.assert(
      scheduledJobId != null,
      'Como no tuve retriers previos, y la excepcion es de tipo timeout ' +
      'se debe haber scheduleado un trabajo y tener un id de referencia'
    );
  }
}