force-app/main/default/objects/Campania__c/Campania__c.object-meta.xml
<CustomObject>
    <label>Campania</label>
    <nameField>
        <label>Campania Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campanias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Campania__c/fields/Prosumer_Cantidad_Entregados__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Cantidad_Entregados__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Prosumer Cantidad Entregados</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Cantidad_No_Entregados__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Cantidad_No_Entregados__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Undelivered SMS de Marketing Cloud.</description>
    <label>Prosumer Cantidad No Entregados</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Creditos_Campania__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Creditos_Campania__c</fullName>
    <label>Prosumer Creditos Campaña</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Cuenta_Cliente__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Cuenta_Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prosumer Cuenta Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campanias</relationshipLabel>
    <relationshipName>Campanias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Estado__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Estado__c</fullName>
    <label>Prosumer Estado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Export Finalizado OK</fullName>
            </value>
            <value>
                <fullName>Export Finalizado con Errores</fullName>
            </value>
            <value>
                <fullName>Export en espera de ejecución</fullName>
            </value>
            <value>
                <fullName>Export en ejecución</fullName>
            </value>
            <value>
                <fullName>Send Automation Iniciado</fullName>
            </value>
            <value>
                <fullName>Send Automation en ejecución</fullName>
            </value>
            <value>
                <fullName>Cerrado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Fecha_de_Inicio__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Fecha_de_Inicio__c</fullName>
    <description>Fecha de creacion de la campaña. Cuando le dan aceptar al formulario.</description>
    <label>Prosumer Fecha de Inicio</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Filtros_Audiencia__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Filtros_Audiencia__c</fullName>
    <label>Prosumer Filtros Audiencia</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Mensaje_SMS__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Mensaje_SMS__c</fullName>
    <label>Prosumer Mensaje SMS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Moviles_en_Audiencia__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Moviles_en_Audiencia__c</fullName>
    <label>Prosumer Moviles en Audiencia</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Tamanio_de_Audiencia__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Tamanio_de_Audiencia__c</fullName>
    <description>Cantidad de personas que hay en la audiencia.</description>
    <label>Prosumer Tamaño de Audiencia</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Prosumer_DashboardController.cls
public without sharing class Prosumer_DashboardController {
    
    @AuraEnabled
    public static List<Campania__c> getCampanias () {
        return [SELECT Id, Name, Prosumer_Estado__c, FORMAT(Prosumer_Fecha_de_Inicio__c) Desde, Prosumer_Moviles_en_Audiencia__c
                FROM Campania__c
                WHERE Prosumer_Cuenta_Cliente__c =: Prosumer_AudienciaPageController.getAccountFromUser()
                ORDER BY Prosumer_Fecha_de_Inicio__c DESC];
    }

    @AuraEnabled
    public static Campania__c getCampania (Id id) {
        return [SELECT Id, Name, Prosumer_Estado__c, Prosumer_Creditos_Campania__c,
                        FORMAT(Prosumer_Fecha_de_Inicio__c) Desde, Prosumer_Moviles_en_Audiencia__c,
                        Prosumer_Mensaje_SMS__c, Prosumer_Tamanio_de_Audiencia__c, Prosumer_Filtros_Audiencia__c, Prosumer_Cantidad_Entregados__c, Prosumer_Cantidad_No_Entregados__c
                FROM Campania__c
                WHERE id=: id];
    }
}