force-app/main/default/objects/Campania__c/Campania__c.object-meta.xml
<CustomObject>
    <label>Campania</label>
    <nameField>
        <label>Campania Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campanias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Campania__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Campañas</relationshipLabel>
    <relationshipName>Campanias</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Cantidad_Entregados__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Cantidad_Entregados__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Prosumer Cantidad Entregados</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Cantidad_Enviados__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Cantidad_Enviados__c</fullName>
    <label>Prosumer Cantidad Enviados</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Cantidad_No_Entregados__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Cantidad_No_Entregados__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Undelivered SMS de Marketing Cloud.</description>
    <label>Prosumer Cantidad No Entregados</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Estado__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Estado__c</fullName>
    <label>Prosumer Estado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Export Finalizado OK</fullName>
            </value>
            <value>
                <fullName>Export Finalizado con Errores</fullName>
            </value>
            <value>
                <fullName>Export en espera de ejecución</fullName>
            </value>
            <value>
                <fullName>Export en ejecución</fullName>
            </value>
            <value>
                <fullName>Send Automation Iniciado</fullName>
            </value>
            <value>
                <fullName>Send Automation en ejecución</fullName>
            </value>
            <value>
                <fullName>Cerrado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Sondeos_IVR_Campaign_Id__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Sondeos_IVR_Campaign_Id__c</fullName>
    <label>Prosumer Sondeos IVR Campaign Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Proyecto</label>
    <nameField>
        <label>Proyecto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proyectos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Objetivo__c.field-meta.xml
<CustomField>
    <fullName>Objetivo__c</fullName>
    <label>Objetivo</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Prioridad__c.field-meta.xml
<CustomField>
    <fullName>Prioridad__c</fullName>
    <label>Prioridad</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ProsumerIvrRESTInterfaceTest.cls
@isTest
private class ProsumerIvrRESTInterfaceTest {

	@testSetup
    private static void setupTest() {
        Project__c objProject = new Project__c();
        objProject.Prioridad__c = 2;
        objProject.Objetivo__c = 'objetivo';
        insert objProject;
        
        Campania__c campania = new Campania__c (Project__c = objProject.Id, name='Campaña de navidad', StartDate__c=Date.newInstance(2019, 7, 7), Status__c='FINALIZADA');
        campania.Prosumer_Sondeos_IVR_Campaign_Id__c = 'Test Campaign Id';        
        insert campania;        
    }
    

    @isTest
    static void testUpdateCampanias() {
        List<ProsumerIvrRESTInterface.Stats> lstStats = new List<ProsumerIvrRESTInterface.Stats>();
        ProsumerIvrRESTInterface.Stats stats = new ProsumerIvrRESTInterface.Stats();
        stats.id = 'Test Campaign Id';
        stats.name = 'Test Campaign';
        stats.type = 'Test Type';
        stats.status = 'Finished';
        stats.from_date = '2023-07-24';
        stats.until_date = '2023-07-25';
        stats.processed_cases = 100;
        stats.contacted_cases = 80;
        stats.processed_percent = 80.0;
        stats.total_cases = 200;
        lstStats.add(stats);

        // Test the HTTP POST method
        Test.startTest();
        Integer result = ProsumerIvrRESTInterface.updateCampanias(lstStats);
        Test.stopTest();

        // Verify that the records are updated as expected
        List<Campania__c> updatedCampanias = [SELECT Prosumer_Cantidad_Enviados__c, Prosumer_Cantidad_Entregados__c,
                                              Prosumer_Cantidad_No_Entregados__c, Prosumer_Estado__c
                                              FROM Campania__c WHERE Prosumer_Sondeos_IVR_Campaign_Id__c = 'Test Campaign Id'];

        System.assertEquals(1, updatedCampanias.size());
        Campania__c updatedCampania = updatedCampanias[0];
        System.assertEquals(100, updatedCampania.Prosumer_Cantidad_Enviados__c);
        System.assertEquals(80, updatedCampania.Prosumer_Cantidad_Entregados__c);
        System.assertEquals(20, updatedCampania.Prosumer_Cantidad_No_Entregados__c);
        System.assertEquals('Cerrado', updatedCampania.Prosumer_Estado__c);
    }
    
}