force-app/main/default/objects/Campania__c/Campania__c.object-meta.xml
<CustomObject>
    <label>Campania</label>
    <nameField>
        <label>Campania Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campanias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Campania__c/fields/Message_Tracking_Last_Update__c.field-meta.xml
<CustomField>
    <fullName>Message_Tracking_Last_Update__c</fullName>
    <label>Message Tracking Last Update</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Mobile_Connect_Campaign_Id__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Connect_Campaign_Id__c</fullName>
    <label>Mobile Connect Campaign Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Campañas</relationshipLabel>
    <relationshipName>Campanias</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Cantidad_Entregados__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Cantidad_Entregados__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Prosumer Cantidad Entregados</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Cantidad_Enviados__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Cantidad_Enviados__c</fullName>
    <label>Prosumer Cantidad Enviados</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Cantidad_No_Entregados__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Cantidad_No_Entregados__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Undelivered SMS de Marketing Cloud.</description>
    <label>Prosumer Cantidad No Entregados</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Estado__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Estado__c</fullName>
    <label>Prosumer Estado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Export Finalizado OK</fullName>
            </value>
            <value>
                <fullName>Export Finalizado con Errores</fullName>
            </value>
            <value>
                <fullName>Export en espera de ejecución</fullName>
            </value>
            <value>
                <fullName>Export en ejecución</fullName>
            </value>
            <value>
                <fullName>Send Automation Iniciado</fullName>
            </value>
            <value>
                <fullName>Send Automation en ejecución</fullName>
            </value>
            <value>
                <fullName>Cerrado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Mensaje_SMS__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Mensaje_SMS__c</fullName>
    <label>Prosumer Mensaje SMS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Proyecto</label>
    <nameField>
        <label>Proyecto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proyectos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ProsumerRESTInterfaceTest.cls
@isTest
private class ProsumerRESTInterfaceTest {

    @isTest
    static void testUpdateCampanias() {
        
        
        // Create test data
        Project__c project = new Project__c();
        project.Name = 'Test Project';
        insert project;

        Campania__c testCampania = new Campania__c(
            Name = 'Test Campaign',
            Prosumer_Mensaje_SMS__c = 'Test Message',
            Project__c = project.Id
        );
        insert testCampania;

        ProsumerRESTInterface.Stats testStats = new ProsumerRESTInterface.Stats();
        testStats.intMCCampaignId = 1234;
        testStats.strMessage = 'Test Message';
        testStats.intMessagesSent = 10;
        testStats.intMessagesDelivered = 8;
        testStats.intMessagesUndelivered = 2;

        List<ProsumerRESTInterface.Stats> testStatsList = new List<ProsumerRESTInterface.Stats>();
        testStatsList.add(testStats);

        // Call the method being tested
        Test.startTest();
        ProsumerRESTInterface.updateCampanias(testStatsList);
        Test.stopTest();

        // Verify that the Campania__c record was updated correctly
        Campania__c updatedCampania = [SELECT Id, Prosumer_Cantidad_Enviados__c, Prosumer_Cantidad_Entregados__c, Prosumer_Cantidad_No_Entregados__c, Mobile_Connect_Campaign_Id__c, Message_Tracking_Last_Update__c, Prosumer_Estado__c FROM Campania__c WHERE Id = :testCampania.Id];
        System.assertEquals(10, updatedCampania.Prosumer_Cantidad_Enviados__c);
        System.assertEquals(8, updatedCampania.Prosumer_Cantidad_Entregados__c);
        System.assertEquals(2, updatedCampania.Prosumer_Cantidad_No_Entregados__c);
        System.assertEquals(1234, updatedCampania.Mobile_Connect_Campaign_Id__c);
        System.assertEquals('Send Automation en ejecución', updatedCampania.Prosumer_Estado__c);
    }
    
    @isTest
    static void testUpdateCampanias2() {
        
        // Create test data
        Project__c project = new Project__c();
        project.Name = 'Test Project 2';
        insert project;
        
        Campania__c testCampania2 = new Campania__c(
            Name = 'Test Campaign',
            Prosumer_Mensaje_SMS__c = 'Test Message 2',
            Project__c = project.Id,
            Mobile_Connect_Campaign_Id__c = 4567,
            Prosumer_Cantidad_Enviados__c = 0,
            Prosumer_Cantidad_Entregados__c = 0,
            Prosumer_Cantidad_No_Entregados__c = 0
        );
        insert testCampania2;

        ProsumerRESTInterface.Stats testStats2 = new ProsumerRESTInterface.Stats();
        testStats2.intMCCampaignId = 4567;
        testStats2.strMessage = 'Test Message 2';
        testStats2.intMessagesSent = 10;
        testStats2.intMessagesDelivered = 9;
        testStats2.intMessagesUndelivered = 1;

        List<ProsumerRESTInterface.Stats> testStatsList2 = new List<ProsumerRESTInterface.Stats>();
        testStatsList2.add(testStats2);

        // Call the method being tested
        Test.startTest();
        ProsumerRESTInterface.updateCampanias(testStatsList2);
        Test.stopTest();

        // Verify that the Campania__c record was updated correctly
        Campania__c updatedCampania2 = [SELECT Id, Prosumer_Cantidad_Enviados__c, Prosumer_Cantidad_Entregados__c, Prosumer_Cantidad_No_Entregados__c, Mobile_Connect_Campaign_Id__c, Message_Tracking_Last_Update__c, Prosumer_Estado__c FROM Campania__c WHERE Id = :testCampania2.Id];
        System.assertEquals(10, updatedCampania2.Prosumer_Cantidad_Enviados__c);
        System.assertEquals(9, updatedCampania2.Prosumer_Cantidad_Entregados__c);
        System.assertEquals(1, updatedCampania2.Prosumer_Cantidad_No_Entregados__c);
        System.assertEquals(4567, updatedCampania2.Mobile_Connect_Campaign_Id__c);
        System.assertEquals('Cerrado', updatedCampania2.Prosumer_Estado__c);
        
    }
    
}