force-app/main/default/objects/Campania__c/Campania__c.object-meta.xml
<CustomObject>
    <label>Campania</label>
    <nameField>
        <label>Campania Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campanias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Campania__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Campañas</relationshipLabel>
    <relationshipName>Campanias</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Creditos_Campania__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Creditos_Campania__c</fullName>
    <label>Prosumer Creditos Campaña</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Cuenta_Cliente__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Cuenta_Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prosumer Cuenta Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campanias</relationshipLabel>
    <relationshipName>Campanias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Fecha_de_Inicio__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Fecha_de_Inicio__c</fullName>
    <description>Fecha de creacion de la campaña. Cuando le dan aceptar al formulario.</description>
    <label>Prosumer Fecha de Inicio</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Filtros_Audiencia__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Filtros_Audiencia__c</fullName>
    <label>Prosumer Filtros Audiencia</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Mensaje_SMS__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Mensaje_SMS__c</fullName>
    <label>Prosumer Mensaje SMS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Moviles_en_Audiencia__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Moviles_en_Audiencia__c</fullName>
    <label>Prosumer Moviles en Audiencia</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_SAQL_Audiencias__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_SAQL_Audiencias__c</fullName>
    <label>Prosumer SAQL Audiencias</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Campania__c/fields/Prosumer_Tamanio_de_Audiencia__c.field-meta.xml
<CustomField>
    <fullName>Prosumer_Tamanio_de_Audiencia__c</fullName>
    <description>Cantidad de personas que hay en la audiencia.</description>
    <label>Prosumer Tamaño de Audiencia</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Proyecto</label>
    <nameField>
        <label>Proyecto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proyectos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Prosumer_DashboardControllerTest.cls
@isTest
public class Prosumer_DashboardControllerTest {

    @isTest
    public static void testQuerys () {
        //just querys, this could be done directly with the Lightning Data Service but I haven't time to check
        Account acc = new Account();
        acc.name = 'PROSUMER ADMINS DEFAULT ACCOUNT';
        insert acc;

        Project__c pj = new Project__c ();
        pj.name = 'TEST';
        insert pj;

        Campania__c campania = new Campania__c ();
        campania.name = 'TEST TITULO';
        campania.Prosumer_SAQL_Audiencias__c = 'TEST SAQL, deberia ser una correcta, pero no hace diferencia';
        campania.Prosumer_Filtros_Audiencia__c = 'TEST JSON de FILTROS VA A ACA';
        campania.Prosumer_Mensaje_SMS__c = 'ACA VA UN MSJ DE TEXTO';
        campania.Prosumer_Creditos_Campania__c = 123;
        campania.Prosumer_Moviles_en_Audiencia__c = 5;
        campania.Prosumer_Tamanio_de_Audiencia__c = 5;
        campania.Prosumer_Fecha_de_Inicio__c = Datetime.now();
        campania.Project__c = pj.id;
        campania.Prosumer_Cuenta_Cliente__c = acc.id;
        insert campania;

        System.assertEquals(1, Prosumer_DashboardController.getCampanias().size(), 'Debe recuperar la lista de campañas, de tamaño 1.');
        System.assertEquals(campania.id, Prosumer_DashboardController.getCampania(campania.id).id, 'Debe recuperar la campaña');
    }
}