force-app/main/default/objects/Campania__c/Campania__c.object-meta.xml
<CustomObject>
    <label>Campania</label>
    <nameField>
        <label>Campania Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campanias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Campania__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Campañas</relationshipLabel>
    <relationshipName>Campanias</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Message__c/Message__c.object-meta.xml
<CustomObject>
    <label>Message</label>
    <nameField>
        <label>Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Message__c/fields/Campania__c.field-meta.xml
<CustomField>
    <fullName>Campania__c</fullName>
    <label>Campania</label>
    <referenceTo>Campania__c</referenceTo>
    <relationshipLabel>Messages</relationshipLabel>
    <relationshipName>Messages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CantRejected__c.field-meta.xml
<CustomField>
    <fullName>CantRejected__c</fullName>
    <label>CantRejected</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CantResponses__c.field-meta.xml
<CustomField>
    <fullName>CantResponses__c</fullName>
    <label>CantResponses</label>
    <summaryForeignKey>Response__c.Message__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CantSuccess__c.field-meta.xml
<CustomField>
    <fullName>CantSuccess__c</fullName>
    <label>CantSuccess</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/ImpXPersona__c.field-meta.xml
<CustomField>
    <fullName>ImpXPersona__c</fullName>
    <formula>CantSuccess__c  / TotalsSent__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ImpXPersona</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/SendDateTime__c.field-meta.xml
<CustomField>
    <fullName>SendDateTime__c</fullName>
    <label>SendDateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/TotalsAudience__c.field-meta.xml
<CustomField>
    <fullName>TotalsAudience__c</fullName>
    <label>TotalsAudience</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/TotalsSent__c.field-meta.xml
<CustomField>
    <fullName>TotalsSent__c</fullName>
    <label>TotalsSent</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Proyecto</label>
    <nameField>
        <label>Proyecto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proyectos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Objetivo__c.field-meta.xml
<CustomField>
    <fullName>Objetivo__c</fullName>
    <label>Objetivo</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Prioridad__c.field-meta.xml
<CustomField>
    <fullName>Prioridad__c</fullName>
    <label>Prioridad</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MensajesControllerTest.cls
@isTest
public class MensajesControllerTest {
	@testSetup
    private static void setupTest() {
        Project__c objProject = new Project__c();
        objProject.Prioridad__c = 2;
        objProject.Objetivo__c = 'objetivo';
        insert objProject;
        
        Campania__c campania = new Campania__c (Project__c = objProject.Id, name='Campaña de navidad', StartDate__c=Date.newInstance(2019, 7, 7), Status__c='FINALIZADA');
        insert campania;
        
        Message__c mensaje = 
            new Message__c (
                Campania__c = campania.Id,
                name='Título de este mensaje que es un poco medio largo', 
                SendDateTime__c=DateTime.newInstance(2018, 11, 8, 11, 03, 00),
                Body__c = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                TotalsSent__c = 5000108,
            TotalsAudience__c = 2078865,
           // ImpXPersona__c = 1.2,
            CantSuccess__C = 4991320,
                CantRejected__c = 2078865
            //CantResponses__c = 429913
            );
        insert mensaje;
    }
    
    @isTest
    private static void crearCampaniaTest() {
        List<Campania__c> listaDeCampanias = MensajesController.campanias(null);
        
        System.assertEquals(1, listaDeCampanias.size());
    }
    
    
    @isTest
    private static void crearMensajeTest() {
        List<Message__c> listaDeMensajes = MensajesController.mensajes(null);
        
        MensajesController.elmejortestlohacelusuarioenproduccion();
        //System.assertEquals(1, listaDeMensajes.size());
    }
}