force-app/main/default/objects/Campania__c/Campania__c.object-meta.xml
<CustomObject>
    <label>Campania</label>
    <nameField>
        <label>Campania Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campanias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Campania__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Campañas</relationshipLabel>
    <relationshipName>Campanias</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Message__c/Message__c.object-meta.xml
<CustomObject>
    <label>Message</label>
    <nameField>
        <label>Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Message__c/fields/Campania__c.field-meta.xml
<CustomField>
    <fullName>Campania__c</fullName>
    <label>Campania</label>
    <referenceTo>Campania__c</referenceTo>
    <relationshipLabel>Messages</relationshipLabel>
    <relationshipName>Messages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CantRejected__c.field-meta.xml
<CustomField>
    <fullName>CantRejected__c</fullName>
    <label>CantRejected</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/CantSuccess__c.field-meta.xml
<CustomField>
    <fullName>CantSuccess__c</fullName>
    <label>CantSuccess</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/Receiver__c.field-meta.xml
<CustomField>
    <fullName>Receiver__c</fullName>
    <defaultValue>&quot;undefined data extension&quot;</defaultValue>
    <label>Receiver</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/Receiver_id__c.field-meta.xml
<CustomField>
    <fullName>Receiver_id__c</fullName>
    <defaultValue>&quot;0&quot;</defaultValue>
    <label>Receiver_id</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/SendDateTime__c.field-meta.xml
<CustomField>
    <fullName>SendDateTime__c</fullName>
    <label>SendDateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/Sender__c.field-meta.xml
<CustomField>
    <fullName>Sender__c</fullName>
    <label>Sender</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/TotalsAudience__c.field-meta.xml
<CustomField>
    <fullName>TotalsAudience__c</fullName>
    <label>TotalsAudience</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/TotalsSent__c.field-meta.xml
<CustomField>
    <fullName>TotalsSent__c</fullName>
    <label>TotalsSent</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Proyecto</label>
    <nameField>
        <label>Proyecto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proyectos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Objetivo__c.field-meta.xml
<CustomField>
    <fullName>Objetivo__c</fullName>
    <label>Objetivo</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Prioridad__c.field-meta.xml
<CustomField>
    <fullName>Prioridad__c</fullName>
    <label>Prioridad</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SondeosRESTTest.cls
@IsTest
private class SondeosRESTTest {
    @TestSetup
    private static void setupTest() {
        Campania__c objCampania = null;
        Message__c objMessage = null;

        objCampania = createCampania();
        objMessage = createMesssage(objCampania);
    }

    @IsTest
    private static void isAliveTest() {
        setupRESTContext();
        
        System.assertEquals('isAlive!', SondeosREST.isAlive());
    }

    @IsTest
    private static void updateStatsTest() {
        String strStatType = null;
        String strMessageId = null;
        Integer intSends = null;
        Campania__c objCampania = null;
        Message__c objMessage = null;

        setupRESTContext();

        strMessageId = [SELECT Id FROM Message__c LIMIT 1].Id;

        SondeosREST.updateStats(strStatType, strMessageId, 123);

        objCampania = [SELECT Status__c FROM Campania__c];

        System.assertEquals('FINALIZADA', objCampania.Status__c);
        objMessage = [SELECT TotalsSent__c, TotalsAudience__c FROM Message__c];

        System.assertEquals(123, objMessage.TotalsSent__c);
        System.assertEquals(123, objMessage.TotalsAudience__c);
    }

    private static Campania__c  createCampania() {
        Project__c objProject = new Project__c();
        objProject.Prioridad__c = 2;
        objProject.Objetivo__c = 'objetivo';
        insert objProject;

        Campania__c objCampania = null;

        objCampania = new Campania__c();
        objCampania.Name = 'Test';
        objCampania.StartDate__c = Date.today();
        objCampania.EndDate__c = Date.today();
        objCampania.Status__c = 'In Progress';
        objCampania.Project__c = objProject.Id;

        insert objCampania;

        return objCampania;
    }

    private static Message__c createMesssage(Campania__c objCampania) { 
        Message__c objMessage = null;

        objMessage = new Message__c();
        objMessage.Campania__c = objCampania.Id;
        objMessage.Body__c = 'Mensaje de prueba';
        objMessage.CantRejected__c = 0;
        objMessage.CantSuccess__c  = 0;
        objMessage.Receiver__c = '123';
        objMessage.Receiver_id__c = '123';
        objMessage.SendDateTime__c = DateTime.now();
        objMessage.Sender__c = '0';
        objMessage.TotalsAudience__c = 0;
        objMessage.TotalsSent__c = 0;

        insert objMessage;

        return objMessage;
    }

    private static void setupRESTContext() {
        RestRequest objRESTRequest = null; 
        RestResponse objRESTResponse = null;
        
        objRESTRequest = new RestRequest(); 
        objRESTResponse = new RestResponse();
        
        objRESTRequest.requestURI = 'https://www.salesforce.com';
        objRESTRequest.httpMethod = 'POST';
        
        RestContext.request = objRESTRequest;
        RestContext.response = objRESTResponse;
        
    }
}