force-app/main/default/objects/Cuidarnos__mdt/Cuidarnos__mdt.object-meta.xml
<CustomObject>
    <label>Cuidarnos</label>
    <pluralLabel>Cuidarnos</pluralLabel>
</CustomObject>

force-app/main/default/objects/Cuidarnos__mdt/fields/Dashboard_Sintomas__c.field-meta.xml
<CustomField>
    <fullName>Dashboard_Sintomas__c</fullName>
    <label>Dashboard Sintomas</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cuidarnos__mdt/fields/Dashboard_Territorial__c.field-meta.xml
<CustomField>
    <fullName>Dashboard_Territorial__c</fullName>
    <label>Dashboard Territorial</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cuidarnos__mdt/fields/DashboardId__c.field-meta.xml
<CustomField>
    <fullName>DashboardId__c</fullName>
    <label>DashboardId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cuidarnos__mdt/fields/Iframe_Url__c.field-meta.xml
<CustomField>
    <fullName>Iframe_Url__c</fullName>
    <label>Iframe Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/PRM_Cuidarnos_Analitycs.cls
public with sharing class PRM_Cuidarnos_Analitycs {
    @AuraEnabled
    public static Id retrieveDashboardId(String strDashboardType) {
        Id strDashboardId = null;
        Map<String, Cuidarnos__mdt> mapCuidarnos = null;
        List<GroupMember> lstUserGroup = null;
        Cuidarnos__mdt objSettings = null;

        System.debug('retrieveDashboardId [] ->');
        
        mapCuidarnos = retrieveCuidarnosSetting();
        lstUserGroup = retrieveGroups();
        
        if(! lstUserGroup.IsEmpty()) {
            for(GroupMember objGroupMember : lstUserGroup) {
                if(objGroupMember.Group != NULL && mapCuidarnos.containsKey(objGroupMember.Group.DeveloperName)) {
                    objSettings = mapCuidarnos.get(objGroupMember.Group.DeveloperName);
                    
                    switch on strDashboardType {
                        when 'Territorial' {
                            strDashboardId = objSettings.Dashboard_Territorial__c;                            
                        }
                        when 'Sintomas' {
                            strDashboardId = objSettings.Dashboard_Sintomas__c;                            
                        }
                        when 'Sanitario' {
                            strDashboardId = objSettings.DashboardId__c;                            
                        }
                    }

                    break;
                }
            }
        }

        System.debug('retrieveDashboardId [' + strDashboardId + '] <-');
        return strDashboardId;
    }

    private static List<GroupMember> retrieveGroups(){ 
        List<GroupMember> lstUserGroup = null;

        System.debug('retrieveGroups [] ->');

        lstUserGroup = [SELECT Id, Group.DeveloperName, UserOrGroupId, SystemModstamp 
                        FROM GroupMember 
                        WHERE  UserOrGroupId = :UserInfo.getUserId()];


        System.debug('retrieveGroups [' + lstUserGroup + '] <-');
        return lstUserGroup;
    }

    private static Map<String, Cuidarnos__mdt> retrieveCuidarnosSetting(){
        Map<String, Cuidarnos__mdt> mapCuidarnos = null;
        List<Cuidarnos__mdt> lstCuidarnos = null;

        System.debug('retrieveCuidarnosSetting [] ->');

        mapCuidarnos = new Map<String, Cuidarnos__mdt>(); 
        lstCuidarnos = [SELECT DashboardId__c,Iframe_Url__c,DeveloperName, Dashboard_Territorial__c , Dashboard_Sintomas__c
                        FROM Cuidarnos__mdt 
                        LIMIT 100];
 
        if(!lstCuidarnos.isEmpty()) {
            for(Cuidarnos__mdt objCuidarnos : lstCuidarnos) {
                mapCuidarnos.put(objCuidarnos.DeveloperName, objCuidarnos);
            }
        }

        System.debug('retrieveCuidarnosSetting [' + mapCuidarnos + '] <-');

        return mapCuidarnos;
    }
}