force-app/main/default/objects/Covid19__c/Covid19__c.object-meta.xml
<CustomObject>
    <label>Covid19</label>
    <nameField>
        <label>Indice Cuidarnos</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Covid19s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Covid19__c/fields/Archive_Date__c.field-meta.xml
<CustomField>
    <fullName>Archive_Date__c</fullName>
    <label>Fecha Archivado</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Covid19__c/fields/Citizen__c.field-meta.xml
<CustomField>
    <fullName>Citizen__c</fullName>
    <label>Ciudadano</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Covid19s</relationshipLabel>
    <relationshipName>Cuidarnos_Datas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Covid19__c/fields/Cuidarnos_Comunidad_Date__c.field-meta.xml
<CustomField>
    <fullName>Cuidarnos_Comunidad_Date__c</fullName>
    <label>Fecha Estado</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Covid19__c/fields/Cuidarnos_Comunidad_Status__c.field-meta.xml
<CustomField>
    <fullName>Cuidarnos_Comunidad_Status__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sintomático</fullName>
            </value>
            <value>
                <fullName>Sospechoso</fullName>
            </value>
            <value>
                <fullName>Muestra</fullName>
            </value>
            <value>
                <fullName>Detectable</fullName>
            </value>
            <value>
                <fullName>No Detectable</fullName>
            </value>
            <value>
                <fullName>Inválido</fullName>
            </value>
            <value>
                <fullName>Notificado</fullName>
            </value>
            <value>
                <fullName>Descartado</fullName>
            </value>
            <value>
                <fullName>Asintomático</fullName>
                <label>Asintómatico</label>
            </value>
            <value>
                <fullName>Archivado</fullName>
            </value>
            <value>
                <fullName>Seguimiento COH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Covid19__c/fields/Cuidarnos_Muestra_Result__c.field-meta.xml
<CustomField>
    <fullName>Cuidarnos_Muestra_Result__c</fullName>
    <label>Muestra</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Detectable</fullName>
            </value>
            <value>
                <fullName>No Detectable</fullName>
            </value>
            <value>
                <fullName>Inválido</fullName>
            </value>
            <value>
                <fullName>Invalido</fullName>
                <isActive>false</isActive>
                <label>Invalido</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Covid19__c/fields/Cuidarnos_Muestra_Result_Date__c.field-meta.xml
<CustomField>
    <fullName>Cuidarnos_Muestra_Result_Date__c</fullName>
    <label>Fecha Muestra</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Covid19__c/fields/Estado_Epidemiologico__c.field-meta.xml
<CustomField>
    <fullName>Estado_Epidemiologico__c</fullName>
    <label>Estado Epidemiologico</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/updateCuidarnosStatusDetectable_Batch.cls
global  without sharing class updateCuidarnosStatusDetectable_Batch  implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator([
            SELECT Id , Citizen__c, Cuidarnos_Comunidad_Status__c , LastModifiedDate, Cuidarnos_Comunidad_Date__c, Estado_Epidemiologico__c
            FROM Covid19__c
            WHERE Cuidarnos_Muestra_Result__c = 'Detectable' AND Cuidarnos_Muestra_Result_Date__c < LAST_N_DAYS:7 
                AND Cuidarnos_Comunidad_Status__c = 'Notificado' // AND Estado_Epidemiologico__c != 'Alta'
            ORDER BY Cuidarnos_Muestra_Result_Date__c ASC
        ]);
    }

    global void execute(Database.BatchableContext BC, List<Covid19__c> lstCuidarnosCovid){
        for (Covid19__c objCovid19: lstCuidarnosCovid) {
            try {
                objCovid19.Cuidarnos_Comunidad_Status__c = 'Archivado';            
                objCovid19.Cuidarnos_Comunidad_Date__c = DateTime.now();
                objCovid19.Archive_Date__c = DateTime.now();
                objCovid19.Estado_Epidemiologico__c = 'Alta';

                PRM_Cuidarnos.saveUserObservationsInSalesforce(objCovid19.Citizen__c, 'Archivado/Alta automática transcurrido 7 días de Detectado.');
            } catch (Exception e) {
                System.debug('An exception occurred: ' + e.getMessage());
            }
        }
        update lstCuidarnosCovid;
    }

    global void finish(Database.BatchableContext BC) {
    }
}