force-app/main/default/objects/Covid19__c/Covid19__c.object-meta.xml
<CustomObject>
    <label>Covid19</label>
    <nameField>
        <label>Indice Cuidarnos</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Covid19s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Covid19__c/fields/Citizen__c.field-meta.xml
<CustomField>
    <fullName>Citizen__c</fullName>
    <label>Ciudadano</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Covid19s</relationshipLabel>
    <relationshipName>Cuidarnos_Datas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/IVR_Calls_Numeral8__c/IVR_Calls_Numeral8__c.object-meta.xml
<CustomObject>
    <label>IVR Calls Numeral8</label>
    <nameField>
        <label>IVR Calls Numeral8 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IVR Calls Numeral8</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/IVR_Calls_Numeral8__c/fields/Covid19__c.field-meta.xml
<CustomField>
    <fullName>Covid19__c</fullName>
    <label>Covid19</label>
    <referenceTo>Covid19__c</referenceTo>
    <relationshipLabel>IVR Calls Numeral8</relationshipLabel>
    <relationshipName>IVR_Calls_Numeral8</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/IVR_Calls_Numeral8__c/fields/Paciente_Phone__c.field-meta.xml
<CustomField>
    <fullName>Paciente_Phone__c</fullName>
    <label>Paciente Phone</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IVR_Calls_Numeral8__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inicial</fullName>
            </value>
            <value>
                <fullName>Enviando</fullName>
            </value>
            <value>
                <fullName>OK</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>POST_ENVIADO</fullName>
            </value>
            <value>
                <fullName>POST_OK</fullName>
            </value>
            <value>
                <fullName>POST_FAILED</fullName>
            </value>
            <value>
                <fullName>GET_ENVIADO</fullName>
            </value>
            <value>
                <fullName>GET_OK</fullName>
            </value>
            <value>
                <fullName>GET_FAILED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PRM_Cuidarnos_GET_IVRNumeral8_Batch.cls
global without sharing class PRM_Cuidarnos_GET_IVRNumeral8_Batch  implements Database.Batchable<sObject>, Database.AllowsCallouts {

    global Database.QueryLocator start(Database.BatchableContext BC) {
        System.debug('PRM_Cuidarnos_GET_IVRNumeral8_Batch [start] ->');
        return Database.getQueryLocator(
                [SELECT Id , Covid19__c, Covid19__R.Citizen__c, Paciente_Phone__c
                 FROM IVR_Calls_Numeral8__c
                 WHERE Status__c = 'POST_OK']
        );
    }

    global void execute(Database.BatchableContext BC, List<IVR_Calls_Numeral8__c> lstLogs){
        System.debug('PRM_Cuidarnos_GET_IVRNumeral8_Batch [execute] ->');
        if (!lstLogs.isEmpty()) {
            System.debug('PRM_Cuidarnos_GET_IVRNumeral8_Batch [calls getRequestIVR] ->');
            List<String> lstLogIds = new List<String>();
            for(IVR_Calls_Numeral8__c objLog: lstLogs) {
                lstLogIds.add(objLog.Id);
            }
            PRM_Cuidarnos.getRequestIVRNumeral8(lstLogIds);
        }
    }

    global void finish(Database.BatchableContext BC) {

    }
}