force-app/main/default/objects/Covid19__c/Covid19__c.object-meta.xml
<CustomObject>
    <label>Covid19</label>
    <nameField>
        <label>Indice Cuidarnos</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Covid19s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Covid19__c/fields/Citizen__c.field-meta.xml
<CustomField>
    <fullName>Citizen__c</fullName>
    <label>Ciudadano</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Covid19s</relationshipLabel>
    <relationshipName>Cuidarnos_Datas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Covid19__c/fields/Cuidarnos_Comunidad_Date__c.field-meta.xml
<CustomField>
    <fullName>Cuidarnos_Comunidad_Date__c</fullName>
    <label>Fecha Estado</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Covid19__c/fields/Cuidarnos_Comunidad_Status__c.field-meta.xml
<CustomField>
    <fullName>Cuidarnos_Comunidad_Status__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sintomático</fullName>
            </value>
            <value>
                <fullName>Sospechoso</fullName>
            </value>
            <value>
                <fullName>Muestra</fullName>
            </value>
            <value>
                <fullName>Detectable</fullName>
            </value>
            <value>
                <fullName>No Detectable</fullName>
            </value>
            <value>
                <fullName>Inválido</fullName>
            </value>
            <value>
                <fullName>Notificado</fullName>
            </value>
            <value>
                <fullName>Descartado</fullName>
            </value>
            <value>
                <fullName>Asintomático</fullName>
                <label>Asintómatico</label>
            </value>
            <value>
                <fullName>Archivado</fullName>
            </value>
            <value>
                <fullName>Seguimiento COH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/updateCuidarnosStatusSalud_Schedulable.cls
global class updateCuidarnosStatusSalud_Schedulable implements Schedulable{

    public static String CRON_EXP = '0 0 4 * * ?';

    global void execute(SchedulableContext objSchedulableContext) { 

        List<Covid19__c> lstCuidarnosCovid = [
            SELECT Id , Citizen__c, Cuidarnos_Comunidad_Status__c , LastModifiedDate,Cuidarnos_Comunidad_Date__c
            FROM Covid19__c
            WHERE Cuidarnos_Comunidad_Status__c = 'Sintomático'
            AND Cuidarnos_Comunidad_Date__c < LAST_N_DAYS:5
            LIMIT 15
        ];

        if(!lstCuidarnosCovid.IsEmpty()) {
            for (Covid19__c objCovid19: lstCuidarnosCovid) {
                PRM_Cuidarnos.updateStatusInSalesforce(objCovid19.Citizen__c, 'Descartado');
            }
        }

    }

}