force-app/main/default/objects/Covid19__c/Covid19__c.object-meta.xml
<CustomObject>
    <label>Covid19</label>
    <nameField>
        <label>Indice Cuidarnos</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Covid19s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Covid19__c/fields/Citizen__c.field-meta.xml
<CustomField>
    <fullName>Citizen__c</fullName>
    <label>Ciudadano</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Covid19s</relationshipLabel>
    <relationshipName>Cuidarnos_Datas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Covid19__c/fields/Mobile_Phone__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Phone__c</fullName>
    <label>Celular</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Covid19__c/fields/proactiva_risk__c.field-meta.xml
<CustomField>
    <fullName>proactiva_risk__c</fullName>
    <label>Triage Riesgo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sintomático</fullName>
            </value>
            <value>
                <fullName>Asintomático</fullName>
            </value>
            <value>
                <fullName>Descartado</fullName>
            </value>
            <value>
                <fullName>Alto</fullName>
                <isActive>false</isActive>
                <label>Alto</label>
            </value>
            <value>
                <fullName>Bajo</fullName>
                <isActive>false</isActive>
                <label>Bajo</label>
            </value>
            <value>
                <fullName>Medio</fullName>
                <isActive>false</isActive>
                <label>Medio</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Covid19__c/fields/Riesgo__c.field-meta.xml
<CustomField>
    <fullName>Riesgo__c</fullName>
    <label>Riesgo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bajo</fullName>
            </value>
            <value>
                <fullName>Medio</fullName>
            </value>
            <value>
                <fullName>Alto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IVR_Calls_Numeral8__c/IVR_Calls_Numeral8__c.object-meta.xml
<CustomObject>
    <label>IVR Calls Numeral8</label>
    <nameField>
        <label>IVR Calls Numeral8 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IVR Calls Numeral8</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/IVR_Calls_Numeral8__c/fields/Covid19__c.field-meta.xml
<CustomField>
    <fullName>Covid19__c</fullName>
    <label>Covid19</label>
    <referenceTo>Covid19__c</referenceTo>
    <relationshipLabel>IVR Calls Numeral8</relationshipLabel>
    <relationshipName>IVR_Calls_Numeral8</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/IVR_Calls_Numeral8__c/fields/Paciente_Phone__c.field-meta.xml
<CustomField>
    <fullName>Paciente_Phone__c</fullName>
    <label>Paciente Phone</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IVR_Calls_Numeral8__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inicial</fullName>
            </value>
            <value>
                <fullName>Enviando</fullName>
            </value>
            <value>
                <fullName>OK</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>POST_ENVIADO</fullName>
            </value>
            <value>
                <fullName>POST_OK</fullName>
            </value>
            <value>
                <fullName>POST_FAILED</fullName>
            </value>
            <value>
                <fullName>GET_ENVIADO</fullName>
            </value>
            <value>
                <fullName>GET_OK</fullName>
            </value>
            <value>
                <fullName>GET_FAILED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PRM_Cuidarnos_GET_IVRNumeral8_Sch_Test.cls
@istest
public with sharing class PRM_Cuidarnos_GET_IVRNumeral8_Sch_Test {

    @testSetup 
    private static void setupTest() {
        CommonTestFunctions.commonSetup();
    }

    @IsTest
    private static void PRM_Cuidarnos_GET_IVRNumeral8_Sch_Test() {
        
        PRM_Cuidarnos_GET_IVRNumeral8_Sched objSchedulable = null;

        Covid19__c a = new Covid19__c();
        a.Name = 'testScheduledApexFromTestMethod';
        a.Citizen__c = CommonTestFunctions.retrieveContact().id;
        a.proactiva_risk__c = 'Sintomático';
        a.Riesgo__c = 'Bajo';
        a.Mobile_Phone__c = '541155555555';
        a.GUID__c = CommonTestFunctions.retrieveContact().GUID__c;
        insert a;

        IVR_Calls_Numeral8__c ivr = new IVR_Calls_Numeral8__c();
        ivr.Covid19__c = a.Id;
        ivr.Paciente_Phone__c = a.Mobile_Phone__c;
        ivr.Status__c = 'POST_OK';
        insert ivr;

        Test.startTest();
            objSchedulable = new PRM_Cuidarnos_GET_IVRNumeral8_Sched();
            objSchedulable.execute(null);
        Test.stopTest();
    }
}