force-app/main/default/objects/Covid19__c/Covid19__c.object-meta.xml
<CustomObject>
    <label>Covid19</label>
    <nameField>
        <label>Indice Cuidarnos</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Covid19s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Covid19__c/fields/Citizen__c.field-meta.xml
<CustomField>
    <fullName>Citizen__c</fullName>
    <label>Ciudadano</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Covid19s</relationshipLabel>
    <relationshipName>Cuidarnos_Datas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Covid19__c/fields/Cuidarnos_Comunidad_Date__c.field-meta.xml
<CustomField>
    <fullName>Cuidarnos_Comunidad_Date__c</fullName>
    <label>Fecha Estado</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Covid19__c/fields/Cuidarnos_Comunidad_Status__c.field-meta.xml
<CustomField>
    <fullName>Cuidarnos_Comunidad_Status__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sintomático</fullName>
            </value>
            <value>
                <fullName>Sospechoso</fullName>
            </value>
            <value>
                <fullName>Muestra</fullName>
            </value>
            <value>
                <fullName>Detectable</fullName>
            </value>
            <value>
                <fullName>No Detectable</fullName>
            </value>
            <value>
                <fullName>Inválido</fullName>
            </value>
            <value>
                <fullName>Notificado</fullName>
            </value>
            <value>
                <fullName>Descartado</fullName>
            </value>
            <value>
                <fullName>Asintomático</fullName>
                <label>Asintómatico</label>
            </value>
            <value>
                <fullName>Archivado</fullName>
            </value>
            <value>
                <fullName>Seguimiento COH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Covid19__c/fields/Cuidarnos_Muestra_Result__c.field-meta.xml
<CustomField>
    <fullName>Cuidarnos_Muestra_Result__c</fullName>
    <label>Muestra</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Detectable</fullName>
            </value>
            <value>
                <fullName>No Detectable</fullName>
            </value>
            <value>
                <fullName>Inválido</fullName>
            </value>
            <value>
                <fullName>Invalido</fullName>
                <isActive>false</isActive>
                <label>Invalido</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Covid19__c/fields/Cuidarnos_Muestra_Result_Date__c.field-meta.xml
<CustomField>
    <fullName>Cuidarnos_Muestra_Result_Date__c</fullName>
    <label>Fecha Muestra</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/updateCuidarnosStatusDetectable_Sch_Test.cls
@istest
public with sharing class updateCuidarnosStatusDetectable_Sch_Test {

    @testSetup 
    private static void setupTest() {
        CommonTestFunctions.commonSetup();
    }

    @IsTest
    private static void updateCuidarnosStatusDetectable_Sch_Test() {
        
        updateCuidarnosStatusDetectable_Sched objSchedulable = null;

        Covid19__c b = new Covid19__c();

        b.Name = 'testScheduledApexFromTestMethod_a';
        b.Citizen__c = CommonTestFunctions.retrieveContact().id;
        b.guid__c = '10';
        b.Cuidarnos_Comunidad_Status__c = 'Notificado';
        b.Cuidarnos_Muestra_Result__c = 'Detectable';
        b.Cuidarnos_Muestra_Result_Date__c = datetime.now().addDays(-15); 
        b.Cuidarnos_Comunidad_Date__c = datetime.now().addDays(-15);
        insert b;

        Test.startTest();
            objSchedulable = new updateCuidarnosStatusDetectable_Sched();
            objSchedulable.execute(null);
        Test.stopTest();
    }
}