force-app/main/default/objects/Covid19__c/Covid19__c.object-meta.xml
<CustomObject>
    <label>Covid19</label>
    <nameField>
        <label>Indice Cuidarnos</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Covid19s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Covid19__c/fields/Citizen__c.field-meta.xml
<CustomField>
    <fullName>Citizen__c</fullName>
    <label>Ciudadano</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Covid19s</relationshipLabel>
    <relationshipName>Cuidarnos_Datas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Covid19__c/fields/Cuidarnos_Comunidad_Date__c.field-meta.xml
<CustomField>
    <fullName>Cuidarnos_Comunidad_Date__c</fullName>
    <label>Fecha Estado</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Covid19__c/fields/Cuidarnos_Comunidad_Status__c.field-meta.xml
<CustomField>
    <fullName>Cuidarnos_Comunidad_Status__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sintomático</fullName>
            </value>
            <value>
                <fullName>Sospechoso</fullName>
            </value>
            <value>
                <fullName>Muestra</fullName>
            </value>
            <value>
                <fullName>Detectable</fullName>
            </value>
            <value>
                <fullName>No Detectable</fullName>
            </value>
            <value>
                <fullName>Inválido</fullName>
            </value>
            <value>
                <fullName>Notificado</fullName>
            </value>
            <value>
                <fullName>Descartado</fullName>
            </value>
            <value>
                <fullName>Asintomático</fullName>
                <label>Asintómatico</label>
            </value>
            <value>
                <fullName>Archivado</fullName>
            </value>
            <value>
                <fullName>Seguimiento COH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Covid19__c/fields/Mobile_Phone__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Phone__c</fullName>
    <label>Celular</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Covid19__c/fields/proactiva_risk__c.field-meta.xml
<CustomField>
    <fullName>proactiva_risk__c</fullName>
    <label>Triage Riesgo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sintomático</fullName>
            </value>
            <value>
                <fullName>Asintomático</fullName>
            </value>
            <value>
                <fullName>Descartado</fullName>
            </value>
            <value>
                <fullName>Alto</fullName>
                <isActive>false</isActive>
                <label>Alto</label>
            </value>
            <value>
                <fullName>Bajo</fullName>
                <isActive>false</isActive>
                <label>Bajo</label>
            </value>
            <value>
                <fullName>Medio</fullName>
                <isActive>false</isActive>
                <label>Medio</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Covid19__c/fields/Riesgo__c.field-meta.xml
<CustomField>
    <fullName>Riesgo__c</fullName>
    <label>Riesgo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bajo</fullName>
            </value>
            <value>
                <fullName>Medio</fullName>
            </value>
            <value>
                <fullName>Alto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PRM_Cuidarnos_POST_IVRNumeral8_Batch.cls
global  without sharing class PRM_Cuidarnos_POST_IVRNumeral8_Batch  implements Database.Batchable<sObject>, Database.AllowsCallouts {

    global Database.QueryLocator start(Database.BatchableContext BC) {
        System.debug('PRM_Cuidarnos_POST_IVRNumeral8_Batch [start] ->');
        return Database.getQueryLocator(
                [SELECT Id , Citizen__c, Cuidarnos_Comunidad_Status__c , LastModifiedDate, Cuidarnos_Comunidad_Date__c, Riesgo__c, proactiva_risk__c, Mobile_Phone__c
                 FROM Covid19__c
                 WHERE Cuidarnos_Comunidad_Status__c IN ('Seguimiento COH', 'Seguimiento')
                 AND Riesgo__c = 'Bajo'
                 AND Mobile_Phone__c != NULL]
        );
    }


    global void execute(Database.BatchableContext BC, List<Covid19__c> lstCuidarnosCovid){
        System.debug('PRM_Cuidarnos_POST_IVRNumeral8_Batch [execute] ->');
        if (!lstCuidarnosCovid.isEmpty()) {
            System.debug('PRM_Cuidarnos_POST_IVRNumeral8_Batch [calls postRequestIVR] ->');
            PRM_Cuidarnos.postRequestIVRNumeral8(lstCuidarnosCovid);
        }
    }


    global void finish(Database.BatchableContext BC) {

    }
}