force-app/main/default/objects/Covid19__c/Covid19__c.object-meta.xml
<CustomObject>
    <label>Covid19</label>
    <nameField>
        <label>Indice Cuidarnos</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Covid19s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Covid19__c/fields/Notificacion_Date__c.field-meta.xml
<CustomField>
    <fullName>Notificacion_Date__c</fullName>
    <label>Fecha Notificado</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Covid19__c/fields/Notifier_User__c.field-meta.xml
<CustomField>
    <fullName>Notifier_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Usuario actualizador de fecha de notificación</description>
    <label>Notifier User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Covid19s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BatchCovid19UpdateNotifierUser.cls
global inherited sharing class BatchCovid19UpdateNotifierUser implements Database.Batchable<sObject> {

    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator([SELECT Id, Name FROM Covid19__c WHERE Notifier_User__c = null AND Notificacion_Date__c != null]);
    }
   
    global void execute(Database.BatchableContext BC, List<Covid19__c> scope){
    	
        Set<Id> covid19Ids = new Set<Id>();

        for(Covid19__c covid19 : scope){
            covid19Ids.add(covid19.Id);
        }

        Map<String, Covid19__History> mapHistory = new Map<String, Covid19__History>();

        for(Covid19__History history : [SELECT ParentId, NewValue, CreatedById FROM Covid19__History WHERE ParentId IN :covid19Ids AND Field = 'Notificacion_Date__c' ORDER BY CreatedDate DESC]){
            mapHistory.put(history.ParentId, history);
        }

        List<Covid19__c> covid19ToUpdate = new List<Covid19__c>();

        for(Covid19__c covid19 : scope){
            if(mapHistory.containsKey(covid19.Id)){
                covid19.Notifier_User__c = (Id)mapHistory.get(covid19.Id).CreatedById;
                covid19ToUpdate.add(covid19);
            }
        }

        if(!covid19ToUpdate.isEmpty()){
            update covid19ToUpdate;
        }

    }

    global void finish(Database.BatchableContext BC) {
    }
}