force-app/main/default/objects/Covid19__c/Covid19__c.object-meta.xml
<CustomObject>
    <label>Covid19</label>
    <nameField>
        <label>Indice Cuidarnos</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Covid19s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Covid19__c/fields/Citizen__c.field-meta.xml
<CustomField>
    <fullName>Citizen__c</fullName>
    <label>Ciudadano</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Covid19s</relationshipLabel>
    <relationshipName>Cuidarnos_Datas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Covid19__c/fields/Cuidarnos_Comunidad_Date__c.field-meta.xml
<CustomField>
    <fullName>Cuidarnos_Comunidad_Date__c</fullName>
    <label>Fecha Estado</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Covid19__c/fields/Cuidarnos_Comunidad_Status__c.field-meta.xml
<CustomField>
    <fullName>Cuidarnos_Comunidad_Status__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sintomático</fullName>
            </value>
            <value>
                <fullName>Sospechoso</fullName>
            </value>
            <value>
                <fullName>Muestra</fullName>
            </value>
            <value>
                <fullName>Detectable</fullName>
            </value>
            <value>
                <fullName>No Detectable</fullName>
            </value>
            <value>
                <fullName>Inválido</fullName>
            </value>
            <value>
                <fullName>Notificado</fullName>
            </value>
            <value>
                <fullName>Descartado</fullName>
            </value>
            <value>
                <fullName>Asintomático</fullName>
                <label>Asintómatico</label>
            </value>
            <value>
                <fullName>Archivado</fullName>
            </value>
            <value>
                <fullName>Seguimiento COH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Covid19__c/fields/Mobile_Phone__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Phone__c</fullName>
    <label>Celular</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Covid19__c/fields/Riesgo__c.field-meta.xml
<CustomField>
    <fullName>Riesgo__c</fullName>
    <label>Riesgo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bajo</fullName>
            </value>
            <value>
                <fullName>Medio</fullName>
            </value>
            <value>
                <fullName>Alto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PRM_Cuidarnos_POST_IVRNumeral8_Sch_Test.cls
@istest
public with sharing class PRM_Cuidarnos_POST_IVRNumeral8_Sch_Test {

    @testSetup 
    private static void setupTest() {
        CommonTestFunctions.commonSetup();
    }

    @IsTest
    private static void PRM_Cuidarnos_POST_IVRNumeral8_Sched_Test() {
        
        PRM_Cuidarnos_POST_IVRNumeral8_Sched objSchedulable = null;

        Covid19__c a = new Covid19__c();
        a.Name = 'testScheduledApexFromTestMethod';
        a.Citizen__c = CommonTestFunctions.retrieveContact().id;
        a.Cuidarnos_Comunidad_Status__c = 'Seguimiento';
        a.Cuidarnos_Comunidad_Date__c = datetime.now().addDays(-10);
        a.Riesgo__c = 'Bajo';
        a.Mobile_Phone__c = '541155555555';
        a.guid__c = CommonTestFunctions.retrieveContact().GUID__c;
        insert a;

        Test.startTest();
            objSchedulable = new PRM_Cuidarnos_POST_IVRNumeral8_Sched();
            objSchedulable.execute(null);
        Test.stopTest();
    }
}