force-app/main/default/objects/Contact/fields/Administrative_Level_1__c.field-meta.xml
<CustomField>
    <fullName>Administrative_Level_1__c</fullName>
    <label>AdminLevel 1 CitizenObj</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Administrative_Level_2__c.field-meta.xml
<CustomField>
    <fullName>Administrative_Level_2__c</fullName>
    <label>AdminLevel 2 CitizenObj</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Administrative_Level_3__c.field-meta.xml
<CustomField>
    <fullName>Administrative_Level_3__c</fullName>
    <label>AdminLevel 3 CitizenObj</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Administrative_Level_4__c.field-meta.xml
<CustomField>
    <fullName>Administrative_Level_4__c</fullName>
    <label>AdminLevel 4 CitizenObj</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/covid19_predictiva_score__c.field-meta.xml
<CustomField>
    <fullName>covid19_predictiva_score__c</fullName>
    <label>Covid19 Predictiva Score</label>
    <precision>17</precision>
    <scale>16</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Document_Number__c.field-meta.xml
<CustomField>
    <fullName>Document_Number__c</fullName>
    <label>Documento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Sexo</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/guid__c.field-meta.xml
<CustomField>
    <fullName>guid__c</fullName>
    <externalId>true</externalId>
    <label>GUID</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MailingAppartment__c.field-meta.xml
<CustomField>
    <fullName>MailingAppartment__c</fullName>
    <description>Este es el que va 13/6</description>
    <label>MailingAppartment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MailingNumber__c.field-meta.xml
<CustomField>
    <fullName>MailingNumber__c</fullName>
    <description>Este es el numero de Calle que vá</description>
    <label>MailingNumber</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pilar360__c/Pilar360__c.object-meta.xml
<CustomObject>
    <label>Pilar360</label>
    <nameField>
        <displayFormat>P360-{00000000}</displayFormat>
        <label>Pilar360</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pilar360s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pilar360__c/fields/Administrative_Level_1__c.field-meta.xml
<CustomField>
    <fullName>Administrative_Level_1__c</fullName>
    <label>Administrative_Level_1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pilar360__c/fields/Administrative_Level_2__c.field-meta.xml
<CustomField>
    <fullName>Administrative_Level_2__c</fullName>
    <label>Administrative_Level_2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pilar360__c/fields/Administrative_Level_3__c.field-meta.xml
<CustomField>
    <fullName>Administrative_Level_3__c</fullName>
    <label>Administrative_Level_3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pilar360__c/fields/Administrative_Level_4__c.field-meta.xml
<CustomField>
    <fullName>Administrative_Level_4__c</fullName>
    <label>Administrative_Level_4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pilar360__c/fields/Citizen__c.field-meta.xml
<CustomField>
    <fullName>Citizen__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup con CONTACTS</description>
    <label>Citizen</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Pilar360s</relationshipLabel>
    <relationshipName>Pilar360s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pilar360__c/fields/guid__c.field-meta.xml
<CustomField>
    <fullName>guid__c</fullName>
    <externalId>true</externalId>
    <label>guid</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Pilar_REST.cls
@RestResource(urlMapping='/pilar/rest/*')
global with sharing class Pilar_REST {

    public class PilarCuitificacion extends RemotingMessageHelper.CuidarnosCuitificacion{
        public String guid { get; set; }
        public String pilar360Id { get; set; }

        public PilarCuitificacion(Contact objContact, String pilar360Id) {
            super(objContact);
            this.guid = objContact.guid__c;
            this.pilar360Id = pilar360Id;
        }
    }

    @HttpGet 
    global static void cuitificar() {
        PilarCuitificacion objResponse = null;
        RemotingMessageHelper.CountRecordsRespose objResponseError = null;
        RestRequest objRESTRequest = null;
        RestResponse objRESTResponse = null;
        List<Contact> lstContacts = null;
        List<String> lstString = null;
        String strUrl = null;
        String strDocumentNumber = null;
        String strSexo = null;
        
        System.debug('cuitificar [ request : ' + RestContext.request + ' ] -> ');
        
        try  {
            objRESTRequest = RestContext.request;
            objRESTResponse = RestContext.response;   
            objRESTResponse.addHeader('Content-Type', 'application/json');
            strUrl = objRESTRequest.requestURI;
            strSexo = objRESTRequest.params.get('sexo');
            
            System.debug('cuitificar [ strSexo : ' + strSexo + ' ]');

            if(String.isNotBlank(strSexo) && strSexo.toLowerCase() != 'm' && strSexo.toLowerCase() != 'f') {
                strSexo = '';
                System.debug('cuitificar [sexo was emptied]');
            }

            if(strUrl.endsWith('/')) {
                strUrl = strUrl.removeEnd('/');
            } 
            lstString = strUrl.split('/');
            strDocumentNumber = lstString[lstString.size() - 1];

            if(String.isNotBlank(strDocumentNumber)) {
                if(String.isBlank(strSexo)) {
                    System.debug('cuitificar [ querying with null sex]');

                    lstContacts = [ SELECT Id, Gender__c, covid19_predictiva_score__c, BirthDate, FirstName, MiddleName, LastName,
                                           MailingStreet, MailingNumber__c, MailingAppartment__c, Administrative_Level_1__c, 
                                           Administrative_Level_2__c, Administrative_Level_3__c, Administrative_Level_4__c,
                                           guid__c 
                                    FROM Contact 
                                    WHERE Document_Number__c =: strDocumentNumber];                                     
                } else {
                    System.debug('cuitificar [ querying with sex]');

                    lstContacts = [ SELECT Id, Gender__c, covid19_predictiva_score__c, BirthDate, FirstName, MiddleName, 
                                           LastName, MailingStreet, MailingNumber__c, MailingAppartment__c, Administrative_Level_1__c, 
                                           Administrative_Level_2__c, Administrative_Level_3__c, Administrative_Level_4__c,
                                           guid__c
                                    FROM Contact 
                                    WHERE Document_Number__c =: strDocumentNumber
                                    AND Gender__c =: strSexo];
                }

                if(!lstContacts.isEmpty()) {
                    Contact contact = lstContacts[0];
                    String pilar360Id;

                    List <Pilar360__c> lstPilar360 = [SELECT Id, Name FROM Pilar360__c WHERE Citizen__c = :contact.Id ORDER BY CreatedDate DESC LIMIT 1];
                    if (lstPilar360.isEmpty()) {
                        try {
                            Pilar360__c Pilar360 = new Pilar360__c();
                            Pilar360.Citizen__c = contact.Id;
                            Pilar360.guid__c = contact.guid__c;
    
                            System.debug('upserting Pilar360 record for ' + Pilar360.Citizen__c);
                            System.debug('guid = ' + contact.guid__c);
    
                            upsert Pilar360;
                            pilar360Id = Pilar360.Id;
                        } catch (Exception e) {}
                    } else {
                        pilar360Id = lstPilar360[0].Id;
                    }
                    System.debug(pilar360Id);

                    objResponse = new PilarCuitificacion(contact, pilar360Id);

                    objRESTResponse.statusCode = 200;
                    objRESTResponse.responseBody = Blob.valueOf(JSON.serialize(objResponse));    
                } else {
                    objResponseError = new RemotingMessageHelper.CountRecordsRespose();
                    objResponseError.code = 100;
                    objResponseError.message = 'No se han encontrado resultados';

                    objRESTResponse.statusCode = 400; 
                    objRESTResponse.responseBody = Blob.valueOf(JSON.serialize(objResponseError));   
                }
            } else {                
                objResponseError = new RemotingMessageHelper.CountRecordsRespose();
                objResponseError.code = 110;
                objResponseError.message = Label.API_Invalid_Request;

                objRESTResponse.statusCode = 400; 
                objRESTResponse.responseBody = Blob.valueOf(JSON.serialize(objResponseError));   
        
            }
        } catch(Exception Ex) {
            objResponseError = new RemotingMessageHelper.CountRecordsRespose();
            objResponseError.code = 999;
            objResponseError.message = Label.API_Invalid_Request;

            objRESTResponse.statusCode = 500; 
            objRESTResponse.responseBody = Blob.valueOf(JSON.serialize(objResponseError));
        }
        
        System.debug('retrieveCUIT [ statusCode : ' + objRESTResponse.statusCode + ' ]');
        System.debug('retrieveCUIT [ responseBody : ' + objRESTResponse.responseBody + ' ]');
        System.debug('retrieveCUIT [] <- ');
    }
}