force-app/main/default/objects/Contact/fields/Administrative_Level_2__c.field-meta.xml
<CustomField>
    <fullName>Administrative_Level_2__c</fullName>
    <label>AdminLevel 2 CitizenObj</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Age_f_x__c.field-meta.xml
<CustomField>
    <fullName>Age_f_x__c</fullName>
    <description>Formula que calcula la edad en funcion de la fecha de nacimiento del ciudadano</description>
    <formula>IF(ISNULL(Birthdate) , NULL, FLOOR((TODAY()-Birthdate +1)/365.2425))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Edad</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/covid19_salud_status__c.field-meta.xml
<CustomField>
    <fullName>covid19_salud_status__c</fullName>
    <label>Covid19 Reactiva Estado</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Document_Number__c.field-meta.xml
<CustomField>
    <fullName>Document_Number__c</fullName>
    <label>Documento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PRM_Cuidarnos_Search_Controller.cls
public with sharing class PRM_Cuidarnos_Search_Controller {
    @AuraEnabled
    public static Integer retrieveCitizens() {
        Integer intCount = null;

        System.debug('retrieveCitizens [] ->');
        intCount = Database.countQuery('SELECT count() FROM Contact');

        System.debug('retrieveCitizens [' + intCount + '] <-');

        return intCount;
    }

    @AuraEnabled
    public static String searchCitizen(String strSearch, Integer intResults) {
        List<List<sObject>> lstResults = null;
        RemotingMessageHelper.SearchResults objSearchResults = null;
        String strJSON = null;
        
        System.debug('searchCitizen [ strSearch : ' + strSearch + ' - intResults : ' + intResults +  '] ->');
        
        lstResults = [FIND :strSearch IN ALL FIELDS  
                      RETURNING Contact(Id, Name,Document_Number__c, Age_f_x__c, Administrative_Level_2__c,  covid19_salud_status__c )
                      LIMIT :intResults];

        System.debug('searchForNames [ lstResults : ' + lstResults + ']');
        
        if(!lstResults.IsEmpty()) {
            objSearchResults = new RemotingMessageHelper.SearchResults(lstResults);
            strJSON = JSON.serializePretty(objSearchResults, true);            
        }
        
        System.debug('searchCitizen [ ' + strJSON + '] <-');

        return strJSON;
    }    
}