force-app/main/default/objects/Contact/fields/Administrative_Level_0__c.field-meta.xml
<CustomField>
    <fullName>Administrative_Level_0__c</fullName>
    <label>AdminLevel 0 CitizenObj</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Administrative_Level_1__c.field-meta.xml
<CustomField>
    <fullName>Administrative_Level_1__c</fullName>
    <label>AdminLevel 1 CitizenObj</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Administrative_Level_2__c.field-meta.xml
<CustomField>
    <fullName>Administrative_Level_2__c</fullName>
    <label>AdminLevel 2 CitizenObj</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Administrative_Level_3__c.field-meta.xml
<CustomField>
    <fullName>Administrative_Level_3__c</fullName>
    <label>AdminLevel 3 CitizenObj</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Administrative_Level_4__c.field-meta.xml
<CustomField>
    <fullName>Administrative_Level_4__c</fullName>
    <label>AdminLevel 4 CitizenObj</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Age_f_x__c.field-meta.xml
<CustomField>
    <fullName>Age_f_x__c</fullName>
    <description>Formula que calcula la edad en funcion de la fecha de nacimiento del ciudadano</description>
    <formula>IF(ISNULL(Birthdate) , NULL, FLOOR((TODAY()-Birthdate +1)/365.2425))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Edad</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Beneficios_Sociales__c.field-meta.xml
<CustomField>
    <fullName>Beneficios_Sociales__c</fullName>
    <label>Beneficios Sociales</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AUH</fullName>
            </value>
            <value>
                <fullName>IFE</fullName>
            </value>
            <value>
                <fullName>Tarjeta AlimentAR</fullName>
            </value>
            <value>
                <fullName>PBF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Community__c.field-meta.xml
<CustomField>
    <fullName>Community__c</fullName>
    <label>Comunidad</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Futbolista</fullName>
            </value>
            <value>
                <fullName>Mascoteros</fullName>
                <default>true</default>
                <label>Mascoteros</label>
            </value>
            <value>
                <fullName>Futboleros</fullName>
            </value>
            <value>
                <fullName>Lector</fullName>
            </value>
            <value>
                <fullName>Pintor</fullName>
            </value>
            <value>
                <fullName>Tenista</fullName>
            </value>
            <value>
                <fullName>Fanático de futebol</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/condicion_de_ingreso__c.field-meta.xml
<CustomField>
    <fullName>condicion_de_ingreso__c</fullName>
    <label>Condición de Ingreso</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Asalariado</fullName>
            </value>
            <value>
                <fullName>Cooperativas y precaria</fullName>
            </value>
            <value>
                <fullName>Jubilados y pensionados</fullName>
            </value>
            <value>
                <fullName>Cuenta propia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Cuil_Number__c.field-meta.xml
<CustomField>
    <fullName>Cuil_Number__c</fullName>
    <externalId>true</externalId>
    <label>CUIL/CUIT</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CUIT_Empleador_1__c.field-meta.xml
<CustomField>
    <fullName>CUIT_Empleador_1__c</fullName>
    <label>CUIT</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CUIT_Empleador_2__c.field-meta.xml
<CustomField>
    <fullName>CUIT_Empleador_2__c</fullName>
    <label>CUIT #2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CUIT_Empleador_3__c.field-meta.xml
<CustomField>
    <fullName>CUIT_Empleador_3__c</fullName>
    <label>CUIT #3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Document_Number__c.field-meta.xml
<CustomField>
    <fullName>Document_Number__c</fullName>
    <label>Documento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Education_Level__c.field-meta.xml
<CustomField>
    <fullName>Education_Level__c</fullName>
    <label>Nivel de Educación</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Employer_1__c.field-meta.xml
<CustomField>
    <fullName>Employer_1__c</fullName>
    <label>Empleadores #1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Employer_2__c.field-meta.xml
<CustomField>
    <fullName>Employer_2__c</fullName>
    <label>Empleadores #2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Employer_3__c.field-meta.xml
<CustomField>
    <fullName>Employer_3__c</fullName>
    <label>Empleadores #3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Facebook_Link__c.field-meta.xml
<CustomField>
    <fullName>Facebook_Link__c</fullName>
    <label>Facebook Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Sexo</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Income_Total__c.field-meta.xml
<CustomField>
    <fullName>Income_Total__c</fullName>
    <label>Ingreso Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Ingreso__c.field-meta.xml
<CustomField>
    <fullName>Ingreso__c</fullName>
    <label>Ingreso</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Muy Alto</fullName>
            </value>
            <value>
                <fullName>Alto</fullName>
            </value>
            <value>
                <fullName>Medio</fullName>
            </value>
            <value>
                <fullName>Bajo</fullName>
            </value>
            <value>
                <fullName>Muy Bajo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Instagram_Link__c.field-meta.xml
<CustomField>
    <fullName>Instagram_Link__c</fullName>
    <label>Instagram Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Linkedin_Link__c.field-meta.xml
<CustomField>
    <fullName>Linkedin_Link__c</fullName>
    <label>Linkedin Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Movilidad__c.field-meta.xml
<CustomField>
    <fullName>Movilidad__c</fullName>
    <description>Tipos de transporte que el Ciudadano utiliza</description>
    <inlineHelpText>Tipos de transporte que el Ciudadano utiliza</inlineHelpText>
    <label>Movilidad</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Auto</fullName>
            </value>
            <value>
                <fullName>Moto</fullName>
            </value>
            <value>
                <fullName>Transporte Público</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Nacionalidad__c.field-meta.xml
<CustomField>
    <fullName>Nacionalidad__c</fullName>
    <label>Nacionalidad</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PhotoUrl_legacy__c.field-meta.xml
<CustomField>
    <fullName>PhotoUrl_legacy__c</fullName>
    <label>PhotoURL</label>
    <length>2048</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Profession__c.field-meta.xml
<CustomField>
    <fullName>Profession__c</fullName>
    <label>Profesión</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sueldo_1__c.field-meta.xml
<CustomField>
    <fullName>Sueldo_1__c</fullName>
    <label>Sueldo #1</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sueldo_2__c.field-meta.xml
<CustomField>
    <fullName>Sueldo_2__c</fullName>
    <label>Sueldo #2</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sueldo_3__c.field-meta.xml
<CustomField>
    <fullName>Sueldo_3__c</fullName>
    <label>Sueldo #3</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Telegram__c.field-meta.xml
<CustomField>
    <fullName>Telegram__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Telegram</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Tiene_Email__c.field-meta.xml
<CustomField>
    <fullName>Tiene_Email__c</fullName>
    <formula>if( Email  =&apos;&apos;, false , true)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tiene Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Tiene_Facebook__c.field-meta.xml
<CustomField>
    <fullName>Tiene_Facebook__c</fullName>
    <formula>IF( (Facebook_Link__c !=&quot;&quot;  ||   Usuario_Facebook__c != &quot;&quot;),True,False)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tiene Facebook ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Tiene_Instagram__c.field-meta.xml
<CustomField>
    <fullName>Tiene_Instagram__c</fullName>
    <formula>IF( ( Instagram_Link__c  !=&quot;&quot; ||  Usuario_Instagram__c  != &quot;&quot;),True,False)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tiene Instagram ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Tiene_Linkedin__c.field-meta.xml
<CustomField>
    <fullName>Tiene_Linkedin__c</fullName>
    <formula>IF( ( Linkedin_Link__c !=&quot;&quot; || Usuario_Linkedin__c  != &quot;&quot;),True,False)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tiene Linkedin ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Tiene_Moviles__c.field-meta.xml
<CustomField>
    <fullName>Tiene_Moviles__c</fullName>
    <formula>if(MobilePhone =&apos;&apos;, false , true)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tiene Moviles</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Tiene_Telefonos_Fijos__c.field-meta.xml
<CustomField>
    <fullName>Tiene_Telefonos_Fijos__c</fullName>
    <formula>if(  HomePhone =&apos;&apos;, false , true)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tiene Telefonos Fijos</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Tiene_Twitter__c.field-meta.xml
<CustomField>
    <fullName>Tiene_Twitter__c</fullName>
    <formula>IF( ( Twitter_Link__c !=&quot;&quot; || Usuario_Twitter__c  != &quot;&quot;),True,False)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tiene Twitter ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Twitter_Link__c.field-meta.xml
<CustomField>
    <fullName>Twitter_Link__c</fullName>
    <label>Twitter Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Usuario_Facebook__c.field-meta.xml
<CustomField>
    <fullName>Usuario_Facebook__c</fullName>
    <description>Nombre de Usuario de Facebook</description>
    <label>Usuario Facebook</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Usuario_Instagram__c.field-meta.xml
<CustomField>
    <fullName>Usuario_Instagram__c</fullName>
    <label>Usuario Instagram</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Usuario_Linkedin__c.field-meta.xml
<CustomField>
    <fullName>Usuario_Linkedin__c</fullName>
    <label>Usuario Linkedin</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Usuario_Twitter__c.field-meta.xml
<CustomField>
    <fullName>Usuario_Twitter__c</fullName>
    <label>Usuario Twitter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <label>UUID</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Whatsapp__c.field-meta.xml
<CustomField>
    <fullName>Whatsapp__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Whatsapp</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/UserPermissionsConsoleController.cls
public class UserPermissionsConsoleController {
    
    public Id userId {get;set;}
    public Contact contact {get;set;}
    public User currentUser {get;set;}
    public List<GroupPermissionWrapper> permissions {get;set;}
    public List<SystemPermissionWrapper> systemPermissions {get;set;}
    public List<PermissionSet> permissionSets {get;set;}
    public List<CustomPermission> customPermissions {get;set;}
    public List<FieldPermissions> fieldPermissions;
    public String groupName {get;set;}
    public List<FieldPermissionDetailWrapper> selectedGroupDetail {get;set;}
    List<String> identificationFields = new List<String> {'Id', 'UUID__c', 'Name', 'Birthdate', 'Document_Number__c', 
            'Cuil_Number__c', 'Gender__c', 'Nacionalidad__c', 'Age_f_x__c', 'PhotoUrl_legacy__c', 'Administrative_Level_0__c', 
            'Administrative_Level_1__c', 'Administrative_Level_2__c', 'Administrative_Level_3__c', 'Administrative_Level_4__c'};
    List<String> attributeFields = new List<String> {'Movilidad__c', 'Profession__c', 'Education_Level__c', 'Ingreso__c', 
        'Beneficios_Sociales__c', 'condicion_de_ingreso__c'};
    List<String> incomeFields = new List<String> {'Employer_1__c', 'Employer_2__c', 'Employer_3__c', 'CUIT_Empleador_1__c', 'CUIT_Empleador_2__c', 
        'CUIT_Empleador_3__c', 'Sueldo_1__c', 'Sueldo_2__c', 'Sueldo_3__c',  'Income_Total__c'};
    List<String> electoralFields = new List<String> {};
    List<String> contactFields = new List<String> {'MailingAddress', 'HomePhone', 'Phone', 'Email', 'Whatsapp__c', 'Telegram__c', 'Facebook_Link__c',
        'Usuario_Facebook__c', 'Twitter_Link__c', 'Usuario_Twitter__c', 'Instagram_Link__c', 'Usuario_Instagram__c', 'Linkedin_Link__c', 'Usuario_Linkedin__c'};
    List<String> hasContactFields = new List<String> {'Tiene_Telefonos_Fijos__c', 'Tiene_Moviles__c', 'Tiene_Email__c', 'Tiene_Facebook__c',
        'Tiene_Instagram__c', 'Tiene_Linkedin__c', 'Tiene_Twitter__c', 'Whatsapp__c', 'Telegram__c', 'Socio_CARP__c'};
    List<String> tagsFields = new List<String> {'Community__c', 'Audiencia_Politica__c', 'Audiencia_Electoral__c', 'Audiencia_Generaciones__c'};
    List<String> tagsProjectFields = new List<String> {'Alerta_Buenos_Aires__c', 'Alerta_Buenos_Aires_ID__c', 
        'Alerta_Buenos_Aires_SirenaID__c', 'ADFi_Profile_ID__c'};
    List<String> systemPermissionsFieldsProfile = new List<String> {'PermissionsApiUserOnly', 'PermissionsApiEnabled', 'PermissionsApexRestServices',
        'PermissionsBulkApiHardDelete', 'PermissionsExportReport', 'PermissionsRunReports', 'PermissionsViewSetup', 'PermissionsEmailMass', 
        'PermissionsEmailSingle', 'PermissionsManageNetworks', 'PermissionsGovernNetworks', 'PermissionsManageUsers', 'PermissionsManageInternalUsers', 
        'PermissionsAssignPermissionSets', 'PermissionsViewAllData', 'PermissionsModifyMetadata', 'PermissionsModifyAllData', 'PermissionsManageIpAddresses'};
    List<String> systemPermissionsFieldsPermissionSet = new List<String> {'PermissionsAddAnalyticsRemoteConnections', 'PermissionsWaveTabularDownload',
        'PermissionsInsightsAppEltEditor', 'PermissionsInsightsAppUser', 'PermissionsCreateUpdateSDDStory', 'PermissionsCreateUpdateSDDDataset', 'PermissionsInsightsAppAdmin'};
    //Lists where field permissions are saved in groups
    public List<FieldPermissionDetailWrapper> identificationList;
    public List<FieldPermissionDetailWrapper> attributesList;
    public List<FieldPermissionDetailWrapper> incomeList;
    public List<FieldPermissionDetailWrapper> electoralList;
    public List<FieldPermissionDetailWrapper> contactList;
    public List<FieldPermissionDetailWrapper> hasContactList;
    public List<FieldPermissionDetailWrapper> tagList;
    public List<FieldPermissionDetailWrapper> tagProjectList;
            
    public UserPermissionsConsoleController () {
        contact = new Contact();
        userId = ApexPages.CurrentPage().getParameters().get('id');
        if(userId != NULL){
            contact.OwnerId = userId;
            currentUser = [SELECT Id, Name, Profile.Name, Profile.Id FROM User WHERE Id =: userId];
            permissions = getGroupPermissions(userId);
            systemPermissions = getSystemPermissions(currentUser);
            permissionSets = getPermissionSets(userId);
            customPermissions = getCustomPermissions(permissionSets);   
        }
    }
    
    public PageReference updateUserView () {
        userId = contact.OwnerId;
        if(userId != NULL){
            currentUser = [SELECT Id, Name, Profile.Name, Profile.Id FROM User WHERE Id =: userId];
            permissions = getGroupPermissions(userId);
            systemPermissions = getSystemPermissions(currentUser);
            permissionSets = getPermissionSets(userId);
            customPermissions = getCustomPermissions(permissionSets);
        }
        return null;
    }
    
    public PageReference getGroupDetail () {
        userId = ApexPages.CurrentPage().getParameters().get('id');
        groupName = ApexPages.CurrentPage().getParameters().get('group');
        selectedGroupDetail = new List<FieldPermissionDetailWrapper>();
        if(groupName == 'Identificacion'){
            selectedGroupDetail = identificationList;
            addMissingFieldsToGroup(selectedGroupDetail, identificationFields);
        }else if(groupName == 'Atributos'){
            selectedGroupDetail = attributesList;
            addMissingFieldsToGroup(selectedGroupDetail, attributeFields);
        }else if(groupName == 'Ingresos'){
            selectedGroupDetail = incomeList;
            addMissingFieldsToGroup(selectedGroupDetail, incomeFields);
        }else if(groupName == 'Electoral'){
            selectedGroupDetail = electoralList;
            addMissingFieldsToGroup(selectedGroupDetail, electoralFields);
        }else if(groupName == 'Contacto'){
            selectedGroupDetail = contactList;
            addMissingFieldsToGroup(selectedGroupDetail, contactFields);
        }else if(groupName == 'Contacto(tiene)'){
            selectedGroupDetail = hasContactList;
            addMissingFieldsToGroup(selectedGroupDetail, hasContactFields);
        }else if(groupName == 'Tags Standard'){
            selectedGroupDetail = tagList;
            addMissingFieldsToGroup(selectedGroupDetail, tagsFields);
        }else if(groupName == 'Tags x proyecto'){
            selectedGroupDetail = tagProjectList;
            addMissingFieldsToGroup(selectedGroupDetail, tagsProjectFields);
        }
        return null;
    }    
    
    public PageReference goBack() {
        
        return Page.UserPermissionsConsole;
    }
    
    public List<GroupPermissionWrapper> getGroupPermissions(Id userId) {
        
        List<GroupPermissionWrapper> permissionsList = new List<GroupPermissionWrapper>();
        fieldPermissions = [SELECT Id, PermissionsEdit, PermissionsRead, Field FROM FieldPermissions WHERE 
                            ParentId IN (SELECT PermissionSetId FROM PermissionSetAssignment WHERE Assignee.Id =: userId) AND SobjectType = 'Contact' AND (NOT Parent.Name LIKE 'X00e%')];
        //Lists where field permissions are saved in groups
        identificationList = new List<FieldPermissionDetailWrapper>();
        attributesList = new List<FieldPermissionDetailWrapper>();
        incomeList = new List<FieldPermissionDetailWrapper>();
        electoralList = new List<FieldPermissionDetailWrapper>();
        contactList = new List<FieldPermissionDetailWrapper>();
        hasContactList = new List<FieldPermissionDetailWrapper>();
        tagList = new List<FieldPermissionDetailWrapper>();
        tagProjectList = new List<FieldPermissionDetailWrapper>();
        
        //iteration over all field permissions
        for(FieldPermissions field : fieldPermissions) {
            
            if(identificationFields.contains(field.Field.split('\\.')[1])){
                createPermissionDetail(field, identificationFields, identificationList);
            }else if(attributeFields.contains(field.Field.split('\\.')[1])){
                createPermissionDetail(field, attributeFields, attributesList);
            }else if(incomeFields.contains(field.Field.split('\\.')[1])){
                createPermissionDetail(field, incomeFields, incomeList);
            }else if(electoralFields.contains(field.Field.split('\\.')[1])){
                createPermissionDetail(field, electoralFields, electoralList);
            }else if(contactFields.contains(field.Field.split('\\.')[1])){
                createPermissionDetail(field, contactFields, contactList);
            }else if(hasContactFields.contains(field.Field.split('\\.')[1])){
                createPermissionDetail(field, hasContactFields, hasContactList);
            }else if(tagsFields.contains(field.Field.split('\\.')[1])){
                createPermissionDetail(field, tagsFields, tagList);
            }else if(tagsProjectFields.contains(field.Field.split('\\.')[1])){
                createPermissionDetail(field, tagsProjectFields, tagProjectList);
            }
        }
        permissionsList.add(createGroupPermission('Identificacion', identificationList, identificationFields));
        permissionsList.add(createGroupPermission('Atributos', attributesList, attributeFields));
        permissionsList.add(createGroupPermission('Ingresos', incomeList, incomeFields));
        permissionsList.add(createGroupPermission('Electoral', electoralList, electoralFields));
        permissionsList.add(createGroupPermission('Contacto', contactList, contactFields));
        permissionsList.add(createGroupPermission('Contacto(tiene)', hasContactList, hasContactFields));
        permissionsList.add(createGroupPermission('Tags Standard', tagList, tagsFields));
        permissionsList.add(createGroupPermission('Tags x proyecto', tagProjectList, tagsProjectFields));
        return permissionsList;
    }
    
    public List<SystemPermissionWrapper> getSystemPermissions(User user) {
        Schema.DescribeSObjectResult objectDescribe  = Profile.SObjectType.getDescribe();
        List<SystemPermissionWrapper> sysPerList = new List<SystemPermissionWrapper>();
        Profile profile = [SELECT Id, PermissionsApiUserOnly, PermissionsApiEnabled, PermissionsApexRestServices, PermissionsBulkApiHardDelete,
                           PermissionsExportReport, PermissionsRunReports, PermissionsViewSetup, PermissionsEmailMass,
                           PermissionsEmailSingle, PermissionsManageNetworks, PermissionsGovernNetworks, PermissionsManageUsers,
                           PermissionsManageInternalUsers, PermissionsAssignPermissionSets, PermissionsViewAllData, PermissionsModifyMetadata,
                           PermissionsModifyAllData, PermissionsManageIpAddresses, PermissionsAddAnalyticsRemoteConnections FROM Profile WHERE Id =: user.Profile.Id];
        List<PermissionSet> permissionSets = [SELECT Id, PermissionsAddAnalyticsRemoteConnections, PermissionsWaveTabularDownload, PermissionsInsightsAppEltEditor,
                                        PermissionsInsightsAppUser, PermissionsCreateUpdateSDDStory, PermissionsCreateUpdateSDDDataset,
                                        PermissionsInsightsAppAdmin FROM PermissionSet
                                              WHERE Id IN (SELECT PermissionSetId FROM PermissionSetAssignment WHERE Assignee.Id =: user.Id ) 
                                              AND (Name = 'EinsteinAnalyticsPlusAdmin' OR Name = 'EinsteinAnalyticsPlusUser') LIMIT 1];
        PermissionSet permissionSet = null;
        if(permissionSets.size() > 0){
            permissionSet = permissionSets[0];
        }
        Map<String, Schema.SObjectField> fieldMap = objectDescribe.fields.getMap();
        for( String fieldName : systemPermissionsFieldsProfile ) {
            Schema.SObjectField field = fieldMap.get( fieldName );
            Schema.DescribeFieldResult fieldDescribe = field.getDescribe();
            SystemPermissionWrapper sysPer = new SystemPermissionWrapper();
            sysPer.name = fieldDescribe.getLabel();
            sysPer.active = (Boolean)profile.get(fieldName);
            sysPerList.add(sysPer);
        }
        if(permissionSet != NULL){
            for( String fieldName : systemPermissionsFieldsPermissionSet ) {
                Schema.SObjectField field = fieldMap.get( fieldName );
                Schema.DescribeFieldResult fieldDescribe = field.getDescribe();
                SystemPermissionWrapper sysPer = new SystemPermissionWrapper();
                sysPer.name = fieldDescribe.getLabel();
                sysPer.active = (Boolean)permissionSet.get(fieldName);
                sysPerList.add(sysPer);
            }
        }
        return sysPerList;    
    }
    
    public List<PermissionSet> getPermissionSets (Id recordId) {
        List<PermissionSet> permissionList = new List<PermissionSet>();
        for (PermissionSet permission : [SELECT Id, Name, Label FROM PermissionSet WHERE Id IN (SELECT PermissionSetId FROM PermissionSetAssignment WHERE Assignee.Id =: recordId )]) {
            if(!permission.name.contains('X00e')){
                permissionList.add(permission);
            }
        }
        return permissionList;
    }
    
    public List<CustomPermission> getCustomPermissions (List<PermissionSet> permissionSets) {
        List<CustomPermission> customPermissionList = [SELECT Id, DeveloperName, MasterLabel FROM CustomPermission WHERE Id IN (SELECT SetupEntityId FROM SetupEntityAccess 
                                                       WHERE ParentId IN: (permissionSets) AND SetupEntityType = 'CustomPermission')];
        return customPermissionList;
    }
    
    /* Checks if a field exist in the permissionList and add it if not */
    private void createPermissionDetail (FieldPermissions field, List<String> fieldGroup, List<FieldPermissionDetailWrapper> permissionsList) {
        Boolean existInGroup = false;
        String nameField = field.Field.split('\\.')[1];
        
        //check if the field iterarion already exist on the group
        for (FieldPermissionDetailWrapper item : permissionsList) {
            if(item.fieldName == nameField){
                //if it exist update the permissions ONLY if the previous value was false
                if(!item.readPermission){
                    item.readPermission = field.permissionsRead;
                }
                if(!item.editPermission){
                    item.editPermission = field.permissionsEdit;
                }
                existInGroup = true;
                break;
            }
        }
        //if it doesn't exist in the group then add it
        if(!existInGroup){
            FieldPermissionDetailWrapper fpdw = new FieldPermissionDetailWrapper();
            fpdw.fieldName = nameField;
            fpdw.readPermission = field.permissionsRead;
            if(fpdw.editPermission == NULL || (!fpdw.editPermission && field.PermissionsEdit)){
                fpdw.editPermission = field.PermissionsEdit;
            }
            permissionsList.add(fpdw);   
        }
    }
    
    private GroupPermissionWrapper createGroupPermission (String name, List<FieldPermissionDetailWrapper> permissionsList, List<String> fieldList) {
        GroupPermissionWrapper permission = new GroupPermissionWrapper();
        permission.name = name;
        Integer readCount = 0;
        Integer editCount = 0;
        for (FieldPermissionDetailWrapper item : permissionsList){
            if(item.readPermission){
                readCount ++;
            }
            if(item.editPermission){
                editCount ++;
            }
        }
        if(readCount == fieldList.size() && editCount == fieldList.size()){
            permission.permissionType = 'Read/Write';
        }else if(readCount > 0 && editCount > 0){
            permission.permissionType = 'Read/Write (parcial)';
        }else if(readCount == fieldList.size()){
            permission.permissionType = 'Read Only';
        }else if(readCount > 0){
            permission.permissionType = 'Read Only (parcial)';
        }else {
            permission.permissionType = 'No Access';
        }
        return permission;
    }
    
    private void addMissingFieldsToGroup(List<FieldPermissionDetailWrapper> permissionsList, List<String> fieldNames){
        Boolean existInList;
        //Check if the group does not have all the corresponding fields
        if(permissionsList.size() != fieldNames.size()){
            //iterate over all the fields of the group to see which is missing 
            for(String fieldName : fieldNames){
                existInList = false;
                for(FieldPermissionDetailWrapper item : permissionsList){
                    if(fieldName == item.fieldName){
                        existInList = true;
                        break;
                    }
                }
                //When a missing field is found is created with its permissions set as false
                if(!existInList){
                    FieldPermissionDetailWrapper fpdw = new FieldPermissionDetailWrapper();
                    fpdw.fieldName = fieldName;
                    fpdw.readPermission = false;
                    fpdw.editPermission = false;
                    permissionsList.add(fpdw);
                }
            }
        }
    }
    
    public class GroupPermissionWrapper {
        
        public String name {get;set;}
        public String permissionType {get;set;}
    }
    
    public class SystemPermissionWrapper {
        
        public String name {get;set;}
        public Boolean active {get;set;} 
    }
    
    public class FieldPermissionDetailWrapper {
        public String fieldName {get;set;}
        public Boolean readPermission {get;set;}
        public Boolean editPermission {get;set;}
    }
}