force-app/main/default/objects/Contact/fields/Document_Number__c.field-meta.xml
<CustomField>
    <fullName>Document_Number__c</fullName>
    <label>Documento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Empatia_Activista__c/Empatia_Activista__c.object-meta.xml
<CustomObject>
    <label>Empatia Activista</label>
    <nameField>
        <label>Empatia Activista Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empatía Activistas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Empatia_Activista__c/fields/Citizen__c.field-meta.xml
<CustomField>
    <fullName>Citizen__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Citizen</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Empatía Activistas</relationshipLabel>
    <relationshipName>Empatia_Activistas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Empatia_Activista__c/fields/DNI__c.field-meta.xml
<CustomField>
    <fullName>DNI__c</fullName>
    <externalId>true</externalId>
    <label>DNI</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Empatia_Activista__c/fields/Fecha_de_nacimiento__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_nacimiento__c</fullName>
    <description>Se usa junto con el DNI para identificar al ciudadano. Un trigger la concatena en el campo &quot;identificador_unico__c&quot;</description>
    <label>Fecha de nacimiento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Empatia_Activista__c/fields/Identificador_unico__c.field-meta.xml
<CustomField>
    <fullName>Identificador_unico__c</fullName>
    <description>El trigger de activista concatena dni + fecha de nacimiento en la creacion / update. El campo evita que se creen activistas duplicados.</description>
    <externalId>true</externalId>
    <label>Identificador unico</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Empatia_ActivistaTriggerHandler.cls
public with sharing class Empatia_ActivistaTriggerHandler {
  public static void handleBeforeInsert(List<Empatia_Activista__c> newRecords) {
    completeIdentificadorUnico(newRecords);
    completeActivistaWithCitizen(newRecords);
  }

  public static void handleBeforeUpdate(Map<id, Empatia_Activista__c> newRecordsById, Map<id, Empatia_Activista__c> oldRecordsById) {
    List<Empatia_Activista__c> recordsToCheckNewIdentificador = new List<Empatia_Activista__c>();

    for (Empatia_Activista__c thisActivista : newRecordsById.values()) {
      Boolean dniCambio = thisActivista.dni__c != oldRecordsById.get(thisActivista.id).dni__c;
      Boolean fechaCambio = thisActivista.fecha_de_nacimiento__c != oldRecordsById.get(thisActivista.id).fecha_de_nacimiento__c;
      if (dniCambio || fechaCambio) {
        recordsToCheckNewIdentificador.add(thisActivista);
      }
    }
    completeIdentificadorUnico(recordsToCheckNewIdentificador);
    completeActivistaWithCitizen(recordsToCheckNewIdentificador);
  }

  public static void completeIdentificadorUnico (List<Empatia_Activista__c> newRecords){
    for(Empatia_Activista__c thisActivista : newRecords){
      //uso el metodo del otro handler para asegurar que la key esa sea consistente.
      //La otra seria crear una tercer clase helper, pero por 1 metodo parece mucho...
      thisActivista.identificador_unico__c = EmpatiaTriggerHandler.getIdentificadorUnico(thisActivista.dni__c, thisActivista.fecha_de_nacimiento__c);
    }
  }

  public static void completeActivistaWithCitizen(List<Empatia_Activista__c> newRecords) {
    Set<String> dnilst = new Set<String>();
    for (Empatia_Activista__c newrec : newRecords) {
      dnilst.add(newrec.DNI__c);
    }

    List<Contact> citizens = new List<Contact>();
    citizens = [SELECT Id, Document_Number__c,Birthdate FROM Contact WHERE Document_Number__c IN :dnilst];

    Map<string, Contact> citizensMap = new Map<string, Contact>();
    for (Contact citi : citizens) {
      String identificadorFromCitizen = EmpatiaTriggerHandler.getIdentificadorUnico(citi.Document_Number__c, citi.Birthdate);
      citizensMap.put(identificadorFromCitizen, citi);
    }

    for (Empatia_Activista__c newrec : newRecords) {
      if (citizensMap.containsKey(newrec.identificador_unico__c)) {
        newrec.Citizen__c = citizensMap.Get(newrec.identificador_unico__c).Id;
      }
    }
  }
}