force-app/main/default/objects/Contact/fields/Document_Number__c.field-meta.xml
<CustomField>
    <fullName>Document_Number__c</fullName>
    <label>Documento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/guid__c.field-meta.xml
<CustomField>
    <fullName>guid__c</fullName>
    <externalId>true</externalId>
    <label>GUID</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Empatia_Activista__c/Empatia_Activista__c.object-meta.xml
<CustomObject>
    <label>Empatia Activista</label>
    <nameField>
        <label>Empatia Activista Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empatía Activistas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Empatia_Activista__c/fields/Citizen__c.field-meta.xml
<CustomField>
    <fullName>Citizen__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Citizen</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Empatía Activistas</relationshipLabel>
    <relationshipName>Empatia_Activistas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Empatia_Activista__c/fields/DNI__c.field-meta.xml
<CustomField>
    <fullName>DNI__c</fullName>
    <externalId>true</externalId>
    <label>DNI</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Empatia_Activista__c/fields/Fecha_de_nacimiento__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_nacimiento__c</fullName>
    <description>Se usa junto con el DNI para identificar al ciudadano. Un trigger la concatena en el campo &quot;identificador_unico__c&quot;</description>
    <label>Fecha de nacimiento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Empatia_ActivistaTriggerTEST.cls
@isTest
public class Empatia_ActivistaTriggerTEST {
  @TestSetup
  public static void makeData() {
    Contact ct = new Contact();
    ct.LastName = 'test';
    ct.guid__c = '11111';
    ct.Document_Number__c = '123456789';
    ct.Birthdate = Date.newInstance(1985, 5, 12);

    insert ct;
  }

  @isTest
  public static void testInsert() {
    Empatia_Activista__c act = new Empatia_Activista__c();
    act.dni__c = '123456789';
    act.fecha_de_nacimiento__c = Date.newInstance(1985, 5, 12);

    Test.startTest();
    insert act;
    Test.stopTest();

    Empatia_Activista__c actInserted = [SELECT id, citizen__c FROM Empatia_Activista__c WHERE id = :act.id];

    Contact expectedContact = [SELECT id FROM contact WHERE Document_Number__c = :act.dni__c AND Birthdate = :act.fecha_de_nacimiento__c];

    System.assertEquals(
      expectedContact.id,
      actInserted.citizen__c,
      'El activista debe tener el lookup completo con el citizen matcheado por DNI y fecha de nacimiento'
    );
  }

  @isTest
  public static void testUpdate() {
    Empatia_Activista__c act = new Empatia_Activista__c();
    act.dni__c = '111111111';
    act.fecha_de_nacimiento__c = Date.newInstance(1985, 5, 12);
    insert act;

    Empatia_Activista__c actInserted = [SELECT id, citizen__c FROM Empatia_Activista__c WHERE id = :act.id];

    System.assertEquals(
      null,
      actInserted.citizen__c,
      'El activista debe tener el lookup en blanco, ya que no hay ninguna combinacion de DNI y fecha coincidente'
    );

    Test.startTest();
    act.dni__c = '123456789';
    update act;
    Test.stopTest();

    Empatia_Activista__c actUpdated = [SELECT id, citizen__c FROM Empatia_Activista__c WHERE id = :act.id];

    Contact expectedContact = [SELECT id FROM contact WHERE Document_Number__c = :act.dni__c AND Birthdate = :act.fecha_de_nacimiento__c];

    System.assertEquals(
      expectedContact.id,
      actUpdated.citizen__c,
      'En el update con un DNI existente (la fecha ya coincidia), se debe haber completado el lookup del activista al citizen.'
    );
  }
}