force-app/main/default/objects/Contact/fields/Document_Number__c.field-meta.xml
<CustomField>
    <fullName>Document_Number__c</fullName>
    <label>Documento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Level1Name__c.field-meta.xml
<CustomField>
    <fullName>Level1Name__c</fullName>
    <formula>IF(Territorio_Administrativo__r.Nivel_Administrativo__c == 1, Territorio_Administrativo__r.Name,  (
	IF(Territorio_Administrativo__r.Nivel_Administrativo__c ==  2 ,Territorio_Administrativo__r.ParentId__r.Name,
		IF(Territorio_Administrativo__r.Nivel_Administrativo__c == 3, Territorio_Administrativo__r.ParentId__r.ParentId__r.Name,
			IF(Territorio_Administrativo__r.Nivel_Administrativo__c == 4, Territorio_Administrativo__r.ParentId__r.ParentId__r.ParentId__r.Name, NULL)		
		) 
	)
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Level1Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Level2Name__c.field-meta.xml
<CustomField>
    <fullName>Level2Name__c</fullName>
    <formula>IF(Territorio_Administrativo__r.Nivel_Administrativo__c == 2, Territorio_Administrativo__r.Name,  (
	IF(Territorio_Administrativo__r.Nivel_Administrativo__c ==  3 ,Territorio_Administrativo__r.ParentId__r.Name,
		IF(Territorio_Administrativo__r.Nivel_Administrativo__c == 4, Territorio_Administrativo__r.ParentId__r.ParentId__r.Name, NULL)		
		) 
	)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Level2Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PhotoUrl_legacy__c.field-meta.xml
<CustomField>
    <fullName>PhotoUrl_legacy__c</fullName>
    <label>PhotoURL</label>
    <length>2048</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Empatia__c/Empatia__c.object-meta.xml
<CustomObject>
    <label>Empatía</label>
    <nameField>
        <displayFormat>EMP-{0000000}</displayFormat>
        <label>Empatia Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Empatía</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Empatia__c/fields/Empatia_Activista__c.field-meta.xml
<CustomField>
    <fullName>Empatia_Activista__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empatia Activista</label>
    <referenceTo>Empatia_Activista__c</referenceTo>
    <relationshipLabel>Respuestas Encuesta</relationshipLabel>
    <relationshipName>Empatias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Empatia__c/fields/Fecha_de_Nacimiento__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Nacimiento__c</fullName>
    <label>Fecha de Nacimiento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Empatia__c/recordTypes/Activista.recordType-meta.xml
<RecordType>
    <fullName>Activista</fullName>
    <active>true</active>
    <label>Activista</label>
</RecordType>

force-app/main/default/objects/Empatia_Activista__c/Empatia_Activista__c.object-meta.xml
<CustomObject>
    <label>Empatia Activista</label>
    <nameField>
        <label>Empatia Activista Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empatía Activistas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Empatia_Activista__c/fields/DNI__c.field-meta.xml
<CustomField>
    <fullName>DNI__c</fullName>
    <externalId>true</externalId>
    <label>DNI</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Empatia_Activista__c/fields/Fecha_de_nacimiento__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_nacimiento__c</fullName>
    <description>Se usa junto con el DNI para identificar al ciudadano. Un trigger la concatena en el campo &quot;identificador_unico__c&quot;</description>
    <label>Fecha de nacimiento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Empatia_Nota__c/Empatia_Nota__c.object-meta.xml
<CustomObject>
    <label>Empatia_Nota</label>
    <nameField>
        <displayFormat>E{000000}</displayFormat>
        <label>Empatia_Nota Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Empatia_Notas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Empatia_Nota__c/fields/Empatia_Activista__c.field-meta.xml
<CustomField>
    <fullName>Empatia_Activista__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empatia Activista</label>
    <referenceTo>Empatia_Activista__c</referenceTo>
    <relationshipLabel>Observaciones</relationshipLabel>
    <relationshipName>Empatia_Notas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/empatia_activistaMergeController.cls
public without sharing class empatia_activistaMergeController implements empatia_activistaMergeInterface {
  //quedo muy complicado... La idea era poder testar las cosas de a 1. Por un lado el metodo que decide sobre si mergear o editar
  //y por otro la logica en si, del merge/edit
  //quise usar la intefase para desacoplar las cosas y funciono, pero me parece que es complicado al pedo
  //ademas el metodo "mergeRecord", tampoco quedo del todo bien en cuanto a los tests.

  @AuraEnabled
  public static String changeActivistaInfo(String recordId, String dni, Date fecha , String injectedStrategy) {
    String strategyNameToUse = String.isBlank(injectedStrategy) ? 'empatia_activistaMergeController' : injectedStrategy;

    Type t = Type.forName(strategyNameToUse);

    empatia_activistaMergeInterface controlStrategy = (empatia_activistaMergeInterface) t.newInstance();

    List<Empatia_Activista__c> activistasExistentes = [SELECT id FROM Empatia_Activista__c WHERE dni__c = :dni AND Fecha_de_nacimiento__c =: fecha];

    if (activistasExistentes.size() == 0) {
      return controlStrategy.updateExistingRecord(recordId, dni, fecha);
    }

    String oldActivistaId = recordId;
    String newRecordId = activistasExistentes[0].id;

    return controlStrategy.mergeRecord(oldActivistaId, newRecordId);
  }

  public static string updateExistingRecord(String recordId, String dni, Date fecha) {
    Empatia_Activista__c activista = new Empatia_Activista__c();
    activista.id = recordId;
    activista.dni__c = dni;
    activista.Fecha_de_nacimiento__c = fecha;

    Database.SaveResult result = Database.update(activista, false);

    if (!result.isSuccess()) {
      throw new AuraHandledException('Ocurrio un error al actualizar el DNI del activista: ' + result.getErrors()[0].getMessage());
    }
    return '{"operationType":"update"}';
  }

  public static string mergeRecord(String oldActivistaId, String newActivistaId) {
    transferNotesToNewActivista(oldActivistaId, newActivistaId);
    transferEmpatiasToNewActivista(oldActivistaId, newActivistaId);

    Empatia_Activista__c oldActivista = new Empatia_Activista__c();
    oldActivista.id = oldActivistaId;
    delete oldActivista;

    return '{"operationType":"merge", "activistaId":"' + newActivistaId + '"}';
  }

  public static void transferNotesToNewActivista(String oldActivistaId, String newActivistaId) {
    List<Empatia_Nota__c> notasToTransfer = [SELECT id FROM Empatia_Nota__c WHERE Empatia_Activista__c = :oldActivistaId];
    for (Empatia_Nota__c thisNota : notasToTransfer) {
      thisNota.Empatia_Activista__c = newActivistaId;
    }

    update notasToTransfer;
  }

  public static void transferEmpatiasToNewActivista(String oldActivistaId, String newActivistaId) {
    List<Empatia__c> empatiasToTransfer = [SELECT id FROM Empatia__c WHERE Empatia_Activista__c = :oldActivistaId];
    for (Empatia__c thisNota : empatiasToTransfer) {
      thisNota.Empatia_Activista__c = newActivistaId;
    }

    update empatiasToTransfer;
  }

  @AuraEnabled
  public static contact searchCitizen(String dni, Date fecha ) {
    List<Contact> contactList = [
      SELECT id, Name, FirstName, LastName, Level1Name__c, Level2Name__c, PhotoUrl_legacy__c
      FROM Contact
      WHERE Document_Number__c = :dni AND BirthDate =: fecha
    ];

    if (contactList.size() == 0) {
      return null;
    }

    return contactList[0];
  }
}