force-app/main/default/objects/Contact/fields/Education_Level__c.field-meta.xml
<CustomField>
    <fullName>Education_Level__c</fullName>
    <label>Nivel de Educación</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Sexo</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/guid__c.field-meta.xml
<CustomField>
    <fullName>guid__c</fullName>
    <externalId>true</externalId>
    <label>GUID</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Ingreso__c.field-meta.xml
<CustomField>
    <fullName>Ingreso__c</fullName>
    <label>Ingreso</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Muy Alto</fullName>
            </value>
            <value>
                <fullName>Alto</fullName>
            </value>
            <value>
                <fullName>Medio</fullName>
            </value>
            <value>
                <fullName>Bajo</fullName>
            </value>
            <value>
                <fullName>Muy Bajo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Is_RiverId_Citizen__c.field-meta.xml
<CustomField>
    <fullName>Is_RiverId_Citizen__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is_RiverId_Citizen</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Location_UUID__c.field-meta.xml
<CustomField>
    <fullName>Location_UUID__c</fullName>
    <description>Codigo Unico de Territorio de Metapod</description>
    <label>Location UUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/RiverId_cat_socio__c.field-meta.xml
<CustomField>
    <fullName>RiverId_cat_socio__c</fullName>
    <label>Categoría de socio</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/RiverId_fecha_socio__c.field-meta.xml
<CustomField>
    <fullName>RiverId_fecha_socio__c</fullName>
    <label>Fecha de alta de socio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/RiverId_Nro_socio__c.field-meta.xml
<CustomField>
    <fullName>RiverId_Nro_socio__c</fullName>
    <label>Numero de socio</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SearchCriteria__c.field-meta.xml
<CustomField>
    <fullName>SearchCriteria__c</fullName>
    <label>Search Criteria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Territorio_Administrativo__c.field-meta.xml
<CustomField>
    <fullName>Territorio_Administrativo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Vinculo con Nuevo Objeto Custom &quot;Territorio Administrativo &quot;</description>
    <inlineHelpText>Vinculo con Nuevo Objeto Custom &quot;Territorio Administrativo &quot;</inlineHelpText>
    <label>Territorio Administrativo</label>
    <referenceTo>Territorio_Administrativo__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Argentino.recordType-meta.xml
<RecordType>
    <fullName>Argentino</fullName>
    <active>true</active>
    <description>Tipo de Registro default para Contactos de Prosumia.</description>
    <label>Argentino</label>
</RecordType>

force-app/main/default/objects/RiverId__c/RiverId__c.object-meta.xml
<CustomObject>
    <label>RiverId</label>
    <nameField>
        <label>RiverId Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RiverIds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RiverId__c/fields/cat_socio__c.field-meta.xml
<CustomField>
    <fullName>cat_socio__c</fullName>
    <label>Categoría de Socio</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RiverId__c/fields/fecha_socio__c.field-meta.xml
<CustomField>
    <fullName>fecha_socio__c</fullName>
    <label>Fecha de Alta de Socio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RiverId__c/fields/guid__c.field-meta.xml
<CustomField>
    <fullName>guid__c</fullName>
    <externalId>true</externalId>
    <label>Guid</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RiverId__c/fields/nro_socio__c.field-meta.xml
<CustomField>
    <fullName>nro_socio__c</fullName>
    <label>Numero de Socio</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/RiverId__c/fields/riverid_citizen__c.field-meta.xml
<CustomField>
    <fullName>riverid_citizen__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RiverIdCitizen</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>RiverIds</relationshipLabel>
    <relationshipName>RiverIds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/Territorio_Administrativo__c.object-meta.xml
<CustomObject>
    <description>Objeto Custom para carga de Territorios de multiples paises, estructurado en 5 niveles</description>
    <label>Territorio</label>
    <nameField>
        <label>Territorio Administrativo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territorios</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Location_UUID__c.field-meta.xml
<CustomField>
    <fullName>Location_UUID__c</fullName>
    <description>Código único de Territorio Metapod</description>
    <externalId>true</externalId>
    <inlineHelpText>Código único de Territorio Metapod</inlineHelpText>
    <label>Location UUID</label>
    <length>24</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Nivel_Administrativo__c.field-meta.xml
<CustomField>
    <fullName>Nivel_Administrativo__c</fullName>
    <label>Nivel Administrativo</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/RiverIdBatchTest.cls
@isTEst
public class RiverIdBatchTest {
    
    @TestSetup
    static void makeData(){
        Territorio_Administrativo__c terr0 = new Territorio_Administrativo__c();
        terr0.Location_UUID__c = 'TEST 0';
        terr0.Nivel_Administrativo__c = 0;
        terr0.Name = 'TEST 0';
        insert terr0;

        Contact con1 = new Contact();
        con1.SearchCriteria__c = '22/01/2001F609';
        con1.LastName = 'Test1';
        con1.guid__c = '1231';
        con1.Territorio_Administrativo__c = terr0.Id;
        con1.Birthdate = Date.today();
        con1.Gender__c = 'M';
        con1.Ingreso__c = 'Muy Bajo';
        con1.Education_Level__c = 'Primaro';
        con1.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Argentino').getRecordTypeId();
        con1.Is_RiverId_Citizen__c = true;
        insert con1;

        Contact con2 = new Contact();
        con2.SearchCriteria__c = '22/01/2001F609';
        con2.LastName = 'Test2';
        con2.guid__c = '1232';
        con2.Territorio_Administrativo__c = terr0.Id;
        con2.Birthdate = Date.today();
        con2.Gender__c = 'F';
        con2.Ingreso__c = 'Bajo';
        con2.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Argentino').getRecordTypeId();
        con2.Is_RiverId_Citizen__c = true;
        con2.RiverId_Nro_socio__c = '2';
        con2.RiverId_fecha_socio__c = Date.today().addDays(-10);
        con2.RiverId_cat_socio__c = 'Cat2';
        insert con2;

        List<RiverId__c> riverIds = new List<RiverId__c> ();
        
        RiverId__c riverId = new RiverId__c();

        riverId.nro_socio__c = 1;
        riverId.riverid_citizen__c = con1.id;
        riverId.name = 'River 1';
        riverId.fecha_socio__c = Date.today();
        riverId.cat_socio__c = 'Cat1';

        riverIds.add(riverId);

        riverId = new RiverId__c();

        riverId.nro_socio__c = 20465779;
        riverId.riverid_citizen__c = con2.id;
        riverId.name = 'River 2';
        riverId.fecha_socio__c = Date.today().addDays(-10);
        riverId.cat_socio__c = 'Cat2';

        riverIds.add(riverId);

        insert riverIds;
    }

    @isTest
    public static void testBatch(){
        Test.startTest();
            RiverIdBatch batch = new RiverIdBatch();
            database.executeBatch(batch, 2000);
        Test.stopTest();

        
        Contact con1 = [SELECT RiverId_Nro_socio__c,RiverId_fecha_socio__c,RiverId_cat_socio__c FROM Contact WHERE LastName = 'Test1'];
        Contact con2 = [SELECT RiverId_Nro_socio__c,RiverId_fecha_socio__c,RiverId_cat_socio__c FROM Contact WHERE LastName = 'Test2'];


        System.assertEquals('1', con1.RiverId_Nro_socio__c, 'Contact1, debe tener los valores del RiverId__c relacionado en todos los campos. RiverId_Nro_socio__c == 1');
        System.assertEquals(Date.today(), con1.RiverId_fecha_socio__c, 'Contact1, debe tener los valores del RiverId__c relacionado en todos los campos. RiverId_fecha_socio__c == 1');
        System.assertEquals('Cat1', con1.RiverId_cat_socio__c, 'Contact1, debe tener los valores del RiverId__c relacionado en todos los campos. RiverId_cat_socio__c == 1');

        System.assertEquals('20465779', con2.RiverId_Nro_socio__c, 'El campo RiverId_Nro_socio__c es el unico de contact2 que debe haberse modificado, el valor esperado es: 3');
        System.assertEquals(Date.today().addDays(-10), con2.RiverId_fecha_socio__c, 'Contact2 ya tenia algunos campos completos con los mismos valores que el RiverId__c relacionado. RiverId_fecha_socio__c no debe cambiar');
        System.assertEquals('Cat2', con2.RiverId_cat_socio__c, 'Contact2 ya tenia algunos campos completos con los mismos valores que el RiverId__c relacionado. RiverId_cat_socio__c no debe cambiar');
    }
}