force-app/main/default/objects/Contact/fields/Education_Level__c.field-meta.xml
<CustomField>
    <fullName>Education_Level__c</fullName>
    <label>Nivel de Educación</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Sexo</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/guid__c.field-meta.xml
<CustomField>
    <fullName>guid__c</fullName>
    <externalId>true</externalId>
    <label>GUID</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Ingreso__c.field-meta.xml
<CustomField>
    <fullName>Ingreso__c</fullName>
    <label>Ingreso</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Muy Alto</fullName>
            </value>
            <value>
                <fullName>Alto</fullName>
            </value>
            <value>
                <fullName>Medio</fullName>
            </value>
            <value>
                <fullName>Bajo</fullName>
            </value>
            <value>
                <fullName>Muy Bajo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Location_UUID__c.field-meta.xml
<CustomField>
    <fullName>Location_UUID__c</fullName>
    <description>Codigo Unico de Territorio de Metapod</description>
    <label>Location UUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SearchCriteria__c.field-meta.xml
<CustomField>
    <fullName>SearchCriteria__c</fullName>
    <label>Search Criteria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Territorio_Administrativo__c.field-meta.xml
<CustomField>
    <fullName>Territorio_Administrativo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Vinculo con Nuevo Objeto Custom &quot;Territorio Administrativo &quot;</description>
    <inlineHelpText>Vinculo con Nuevo Objeto Custom &quot;Territorio Administrativo &quot;</inlineHelpText>
    <label>Territorio Administrativo</label>
    <referenceTo>Territorio_Administrativo__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Argentino.recordType-meta.xml
<RecordType>
    <fullName>Argentino</fullName>
    <active>true</active>
    <description>Tipo de Registro default para Contactos de Prosumia.</description>
    <label>Argentino</label>
</RecordType>

force-app/main/default/objects/Territorio_Administrativo__c/Territorio_Administrativo__c.object-meta.xml
<CustomObject>
    <description>Objeto Custom para carga de Territorios de multiples paises, estructurado en 5 niveles</description>
    <label>Territorio</label>
    <nameField>
        <label>Territorio Administrativo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territorios</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Location_UUID__c.field-meta.xml
<CustomField>
    <fullName>Location_UUID__c</fullName>
    <description>Código único de Territorio Metapod</description>
    <externalId>true</externalId>
    <inlineHelpText>Código único de Territorio Metapod</inlineHelpText>
    <label>Location UUID</label>
    <length>24</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Nivel_Administrativo__c.field-meta.xml
<CustomField>
    <fullName>Nivel_Administrativo__c</fullName>
    <label>Nivel Administrativo</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ParentId</label>
    <referenceTo>Territorio_Administrativo__c</referenceTo>
    <relationshipLabel>Territories</relationshipLabel>
    <relationshipName>ChildTerritories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_UpdateTerritories.cls
@isTest
public with sharing class Test_UpdateTerritories {

    @testSetup
    static void setup(){	

        Cache.SessionPartition sessionPart = Cache.Session.getPartition('local.Territory');
        Territorio_Administrativo__c terr = new Territorio_Administrativo__c();
        terr.Location_UUID__c = 'TEST';
        terr.Nivel_Administrativo__c = 0;
        terr.Name = 'Argentina';
        insert terr;
        /*Test Setup */
        Territorio_Administrativo__c terr2 = new Territorio_Administrativo__c();
        terr2.Location_UUID__c = 'TEST 2';
        terr2.Nivel_Administrativo__c = 1;
        terr2.Name = 'TEST 2';
		terr2.ParentId__c = terr.Id;
        insert terr2;
        Territorio_Administrativo__c terr3 = new Territorio_Administrativo__c();
        terr3.Location_UUID__c = 'TEST 3';
        terr3.Nivel_Administrativo__c = 2;
        terr3.Name = 'TEST 3';
        terr3.ParentId__c = terr2.Id;
        insert terr3;
        Territorio_Administrativo__c terr4 = new Territorio_Administrativo__c();
        terr4.Location_UUID__c = 'TEST 4';
        terr4.Nivel_Administrativo__c = 3;
        terr4.Name = 'TEST 4';
        terr4.ParentId__c = terr3.Id;
        insert terr4;
        Territorio_Administrativo__c terr5 = new Territorio_Administrativo__c();
        terr5.Location_UUID__c = 'TEST 5';
        terr5.Nivel_Administrativo__c = 4;
        terr5.Name = 'TEST 5';
        terr5.ParentId__c = terr4.Id;
        insert terr5;

        List<Contact> citizens = new List<Contact>();

        Contact con = new Contact();
        con.SearchCriteria__c = '22/01/2001F609';
        con.LastName = 'Test';
        con.guid__c = '1231';
        con.Territorio_Administrativo__c = terr5.Id;
        con.Birthdate = Date.today();
        con.Gender__c = 'M';
        con.Ingreso__c = 'Muy Bajo';
        con.Education_Level__c = 'Primaro';
        con.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Argentino').getRecordTypeId();

        citizens.add(con);

        con = new Contact();
        con.SearchCriteria__c = '22/01/2001F609';
        con.LastName = 'Test';
        con.guid__c = '1232';
        con.Territorio_Administrativo__c = terr5.Id;
        con.Birthdate = Date.today();
        con.Gender__c = 'F';
        con.Ingreso__c = 'Bajo';
        con.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Argentino').getRecordTypeId();

        citizens.add(con);

        con = new Contact();
        con.SearchCriteria__c = '22/01/2001F609';
        con.LastName = 'Test';
        con.guid__c = '1233';
        con.Territorio_Administrativo__c = terr5.Id;
        con.Birthdate = Date.today().addYears(-15);
        con.Gender__c = 'M';
        con.Ingreso__c = 'Medio';
        con.Education_Level__c = 'Secundario';
        con.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Argentino').getRecordTypeId();

        citizens.add(con);

        con = new Contact();
        con.SearchCriteria__c = '22/01/2001F609';
        con.LastName = 'Test';
        con.guid__c = '1234';
        con.Territorio_Administrativo__c = terr5.Id;
        con.Birthdate = Date.today().addYears(-15);
        con.Gender__c = 'F';
        con.Ingreso__c = 'Alto';
        con.Education_Level__c = 'Terciario';
        con.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Argentino').getRecordTypeId();

        citizens.add(con);

        con = new Contact();
        con.SearchCriteria__c = '22/01/2001F609';
        con.LastName = 'Test';
        con.guid__c = '1235';
        con.Territorio_Administrativo__c = terr5.Id;
        con.Birthdate = Date.today().addYears(-30);
        con.Gender__c = 'M';
        con.Ingreso__c = 'Muy Alto';
        con.Education_Level__c = 'Universitario';
        con.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Argentino').getRecordTypeId();

        citizens.add(con);

        con = new Contact();
        con.SearchCriteria__c = '22/01/2001F609';
        con.LastName = 'Test';
        con.guid__c = '1236';
        con.Territorio_Administrativo__c = terr5.Id;
        con.Birthdate = Date.today().addYears(-30);
        con.Gender__c = 'F';
        con.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Argentino').getRecordTypeId();

        citizens.add(con);

        con = new Contact();
        con.SearchCriteria__c = '22/01/2001F609';
        con.LastName = 'Test';
        con.guid__c = '1237';
        con.Territorio_Administrativo__c = terr5.Id;
        con.Birthdate = Date.today().addYears(-45);
        con.Gender__c = 'M';
        con.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Argentino').getRecordTypeId();

        citizens.add(con);

        con = new Contact();
        con.SearchCriteria__c = '22/01/2001F609';
        con.LastName = 'Test';
        con.guid__c = '1238';
        con.Territorio_Administrativo__c = terr5.Id;
        con.Birthdate = Date.today().addYears(-45);
        con.Gender__c = 'F';
        con.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Argentino').getRecordTypeId();

        citizens.add(con);

        con = new Contact();
        con.SearchCriteria__c = '22/01/2001F609';
        con.LastName = 'Test';
        con.guid__c = '1239';
        con.Territorio_Administrativo__c = terr5.Id;
        con.Birthdate = Date.today().addYears(-60);
        con.Gender__c = 'M';
        con.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Argentino').getRecordTypeId();

        citizens.add(con);

        con = new Contact();
        con.SearchCriteria__c = '22/01/2001F609';
        con.LastName = 'Test';
        con.guid__c = '1230';
        con.Territorio_Administrativo__c = terr5.Id;
        con.Birthdate = Date.today().addYears(-60);
        con.Gender__c = 'F';
        con.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Argentino').getRecordTypeId();

        citizens.add(con);
                            
        insert citizens;
    }
    
    @isTest 
    static void testUpdate() {
        Test.startTest();
            SchdUpdateTerritories.start('Argentina');
        Test.stopTest();

    }
}