force-app/main/default/objects/Contact/fields/Education_Level__c.field-meta.xml
<CustomField>
    <fullName>Education_Level__c</fullName>
    <label>Nivel de Educación</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Sexo</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/guid__c.field-meta.xml
<CustomField>
    <fullName>guid__c</fullName>
    <externalId>true</externalId>
    <label>GUID</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Ingreso__c.field-meta.xml
<CustomField>
    <fullName>Ingreso__c</fullName>
    <label>Ingreso</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Muy Alto</fullName>
            </value>
            <value>
                <fullName>Alto</fullName>
            </value>
            <value>
                <fullName>Medio</fullName>
            </value>
            <value>
                <fullName>Bajo</fullName>
            </value>
            <value>
                <fullName>Muy Bajo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Is_RiverId_Citizen__c.field-meta.xml
<CustomField>
    <fullName>Is_RiverId_Citizen__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is_RiverId_Citizen</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/RiverId_cat_socio__c.field-meta.xml
<CustomField>
    <fullName>RiverId_cat_socio__c</fullName>
    <label>Categoría de socio</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/RiverId_fecha_socio__c.field-meta.xml
<CustomField>
    <fullName>RiverId_fecha_socio__c</fullName>
    <label>Fecha de alta de socio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/RiverId_Nro_socio__c.field-meta.xml
<CustomField>
    <fullName>RiverId_Nro_socio__c</fullName>
    <label>Numero de socio</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SearchCriteria__c.field-meta.xml
<CustomField>
    <fullName>SearchCriteria__c</fullName>
    <label>Search Criteria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Argentino.recordType-meta.xml
<RecordType>
    <fullName>Argentino</fullName>
    <active>true</active>
    <description>Tipo de Registro default para Contactos de Prosumia.</description>
    <label>Argentino</label>
</RecordType>

force-app/main/default/objects/RiverId__c/RiverId__c.object-meta.xml
<CustomObject>
    <label>RiverId</label>
    <nameField>
        <label>RiverId Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RiverIds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RiverId__c/fields/cat_socio__c.field-meta.xml
<CustomField>
    <fullName>cat_socio__c</fullName>
    <label>Categoría de Socio</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RiverId__c/fields/fecha_socio__c.field-meta.xml
<CustomField>
    <fullName>fecha_socio__c</fullName>
    <label>Fecha de Alta de Socio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RiverId__c/fields/guid__c.field-meta.xml
<CustomField>
    <fullName>guid__c</fullName>
    <externalId>true</externalId>
    <label>Guid</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RiverId__c/fields/nro_socio__c.field-meta.xml
<CustomField>
    <fullName>nro_socio__c</fullName>
    <label>Numero de Socio</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/RiverId__c/fields/riverid_citizen__c.field-meta.xml
<CustomField>
    <fullName>riverid_citizen__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RiverIdCitizen</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>RiverIds</relationshipLabel>
    <relationshipName>RiverIds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RiverId_Polls__c/RiverId_Polls__c.object-meta.xml
<CustomObject>
    <label>RiverId Poll</label>
    <nameField>
        <displayFormat>RiverIdPol-{0000000}</displayFormat>
        <label>RiverId Polls Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RiverId Polls</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RiverId_Polls__c/fields/Abonos__c.field-meta.xml
<CustomField>
    <fullName>Abonos__c</fullName>
    <label>Abonos</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RiverId_Polls__c/fields/Beneficios__c.field-meta.xml
<CustomField>
    <fullName>Beneficios__c</fullName>
    <label>Beneficios</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RiverId_Polls__c/fields/Estadio__c.field-meta.xml
<CustomField>
    <fullName>Estadio__c</fullName>
    <label>Estadio</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RiverId_Polls__c/fields/Fecha_Respuesta__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Respuesta__c</fullName>
    <label>Fecha Respuesta</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RiverId_Polls__c/fields/Futbol__c.field-meta.xml
<CustomField>
    <fullName>Futbol__c</fullName>
    <label>Futbol</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RiverId_Polls__c/fields/guid__c.field-meta.xml
<CustomField>
    <fullName>guid__c</fullName>
    <label>Guid</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RiverId_Polls__c/fields/Instalaciones__c.field-meta.xml
<CustomField>
    <fullName>Instalaciones__c</fullName>
    <label>Instalaciones</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RiverId_Polls__c/fields/RiverId_SFID__c.field-meta.xml
<CustomField>
    <fullName>RiverId_SFID__c</fullName>
    <label>RiverId_SFID</label>
    <referenceTo>RiverId__c</referenceTo>
    <relationshipLabel>RiverId Polls</relationshipLabel>
    <relationshipName>RiverId_Polls</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RiverId_Polls__c/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <externalId>true</externalId>
    <label>Token</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CommunitiesRiverControllerTest.cls
/**
 * An apex controller that retrieves polls data for RiverId Community
 */
@IsTest public with sharing class CommunitiesRiverControllerTest {

    @testSetup
    private static void setupTest() {
        createData();
    }

    @IsTest
    public static void CommunitiesRiverControllerTest() {
        Contact con1 = [SELECT RiverId_Nro_socio__c,RiverId_fecha_socio__c,RiverId_cat_socio__c, LastName FROM Contact WHERE LastName = 'Test1'];
        System.debug('name: ' + con1.LastName);
        System.assert(CommunitiesRiverController.retrieveInfoPollsFromCitizenId(con1.Id) <> null);  
        System.assert(CommunitiesRiverController.retrieveInfoPollsFromCitizenId('0031h00000dbtwgxxx') == null);
    }

    private static void createData() {
        Contact con1 = new Contact();
        con1.SearchCriteria__c = '22/01/2001F609';
        con1.LastName = 'Test1';
        con1.guid__c = '1231';
        con1.Birthdate = Date.today();
        con1.Gender__c = 'M';
        con1.Ingreso__c = 'Muy Bajo';
        con1.Education_Level__c = 'Primaro';
        con1.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Argentino').getRecordTypeId();
        con1.Is_RiverId_Citizen__c = true;
        insert con1;

        RiverId__c riverId = new RiverId__c();
        riverId.nro_socio__c = 1;
        riverId.riverid_citizen__c = con1.id;
        riverId.name = 'River 1';
        riverId.fecha_socio__c = Date.today();
        riverId.cat_socio__c = 'Cat1';
        insert riverId;

        RiverId_Polls__c poll1 = New RiverId_Polls__c();
        poll1.RiverId_SFID__c = riverId.Id;
        poll1.Abonos__c = 2;
        poll1.Beneficios__c = 4;
        poll1.Estadio__c = 4;
        poll1.Futbol__c = 3;
        poll1.Instalaciones__c = 2;
        poll1.guid__c = con1.guid__c;
        poll1.Fecha_Respuesta__c = Date.newInstance(2022, 4, 3);
        poll1.Token__c = '32132132';
        insert poll1;

        RiverId_Polls__c poll2 = New RiverId_Polls__c();
        poll2.RiverId_SFID__c = riverId.Id;
        poll2.Abonos__c = 3;
        poll2.Beneficios__c = 2;
        poll2.Estadio__c = 5;
        poll2.Futbol__c = 4;
        poll2.Instalaciones__c = 3;
        poll2.guid__c = con1.guid__c;
        poll2.Fecha_Respuesta__c = Date.newInstance(2022, 3, 3);
        poll2.Token__c = '32132132';
        insert poll2;

    }
    
}