force-app/main/default/objects/Contact/fields/Facebook_Link__c.field-meta.xml
<CustomField>
    <fullName>Facebook_Link__c</fullName>
    <label>Facebook Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Instagram_Link__c.field-meta.xml
<CustomField>
    <fullName>Instagram_Link__c</fullName>
    <label>Instagram Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Linkedin_Link__c.field-meta.xml
<CustomField>
    <fullName>Linkedin_Link__c</fullName>
    <label>Linkedin Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Twitter_Link__c.field-meta.xml
<CustomField>
    <fullName>Twitter_Link__c</fullName>
    <label>Twitter Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Usuario_Facebook__c.field-meta.xml
<CustomField>
    <fullName>Usuario_Facebook__c</fullName>
    <description>Nombre de Usuario de Facebook</description>
    <label>Usuario Facebook</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Usuario_Instagram__c.field-meta.xml
<CustomField>
    <fullName>Usuario_Instagram__c</fullName>
    <label>Usuario Instagram</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Usuario_Linkedin__c.field-meta.xml
<CustomField>
    <fullName>Usuario_Linkedin__c</fullName>
    <label>Usuario Linkedin</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Usuario_Twitter__c.field-meta.xml
<CustomField>
    <fullName>Usuario_Twitter__c</fullName>
    <label>Usuario Twitter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Social_Destination__c/Social_Destination__c.object-meta.xml
<CustomObject>
    <label>Social Destination</label>
    <nameField>
        <label>Social Media Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Social Destinations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Social_Media__c/Social_Media__c.object-meta.xml
<CustomObject>
    <label>Social Media</label>
    <nameField>
        <label>Social Media</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Social Medias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Social_Media_Sends__c/Social_Media_Sends__c.object-meta.xml
<CustomObject>
    <label>Social Media Send</label>
    <nameField>
        <displayFormat>SMS-{000000}</displayFormat>
        <label>Social Media Sends Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Social Media Sends</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Social_Media_Sends__c/fields/Social_Destination__c.field-meta.xml
<CustomField>
    <fullName>Social_Destination__c</fullName>
    <label>Social Destination</label>
    <referenceTo>Social_Destination__c</referenceTo>
    <relationshipLabel>Social Media Sends</relationshipLabel>
    <relationshipName>Social_Media_Sends</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Social_Media_Sends__c/fields/Social_Media__c.field-meta.xml
<CustomField>
    <fullName>Social_Media__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Social Media</label>
    <referenceTo>Social_Media__c</referenceTo>
    <relationshipLabel>Social Media Sends</relationshipLabel>
    <relationshipName>Social_Media_Sends</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Social_Media_Sends__c/fields/Social_Source__c.field-meta.xml
<CustomField>
    <fullName>Social_Source__c</fullName>
    <label>Social Source</label>
    <referenceTo>Social_Source__c</referenceTo>
    <relationshipLabel>Social Media Sends</relationshipLabel>
    <relationshipName>Social_Media_Sends</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Social_Source__c/Social_Source__c.object-meta.xml
<CustomObject>
    <label>Social Source</label>
    <nameField>
        <label>Hashtags</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Social Source</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SocialPostController.cls
public class SocialPostController {        
    @InvocableMethod
    public static void sendNotifications(List<SocialPost> lstSocialPosts) { 
        Map<Contact,List<SocialPost>>  mapContactPosts = null;
        List<Social_Media_Sends__c> lstSocialMediaSends = null;
        
        System.debug('sendNotifications [' + lstSocialPosts + '] ->');
        
        if(lstSocialPosts != null && !lstSocialPosts.isEmpty()) {        
            lstSocialMediaSends = retrieveSocialMediaSendsConfiguration();
             
            if(!lstSocialMediaSends.IsEmpty()) {   
                mapContactPosts = retrieveCitizens(lstSocialPosts);
                
                if(mapContactPosts != null && !mapContactPosts.isEmpty()) {
                    sendNotifications(mapContactPosts, lstSocialMediaSends);
                } else {
                    System.debug('sendNotifications [ mapContactPosts are blank]');                    
                }
            } else {
                System.debug('sendNotifications [ lstSocialMediaSends are blank]');
            }
        } else {
            System.debug('sendNotifications [ lstSocialPosts are blank]');
        }
        
        System.debug('sendNotifications [] <-');    
    }
    
    //TODO: ESTO SE PUEDE OBVIAR PORQUE CUANDO SE  MODIFIQUE EL APEX SCS
    private static Map<Contact,List<SocialPost>> retrieveCitizens(List<SocialPost> lstSocialPosts) {
        Set<String> setHandles = null;
        List<Contact> lstCitizens = null;
        List<List<Contact>> lstSOSLResult = null;
        Map<Contact,List<SocialPost>>  mapContactPosts = null;
        String strSearchTerm = null;
        System.debug('retrieveCitizens [lstSocialPosts : ' + lstSocialPosts + '] ->');
        
        try {
            mapContactPosts = new Map<Contact,List<SocialPost>>();
            setHandles = new Set<String>();
            for(SocialPost objSocialPost : lstSocialPosts) {
                if(String.isNotBlank(objSocialPost.Handle)) {
                    setHandles.add(objSocialPost.Handle);
                }
            }
            
            strSearchTerm = String.join(new List<String>(setHandles), ' OR ');
            lstSOSLResult = [FIND :strSearchTerm RETURNING CONTACT(FirstName, LastName, Usuario_Twitter__c, Usuario_Facebook__c, Email, MobilePhone)];
            /*
            lstCitizens = [SELECT Id, FirstName, Email, MobilePhone, Usuario_Twitter__c, Twitter_Link__c, Usuario_LinkedIn__c, LinkedIn_Link__c, Usuario_Instagram__c, Instagram_Link__c, Usuario_Facebook__c, Facebook_Link__c
                           FROM Contact 
                           WHERE Usuario_Twitter__c IN :setHandles 
                           OR Twitter_Link__c IN :setHandles 
                           OR Usuario_LinkedIn__c IN :setHandles 
                           OR LinkedIn_Link__c IN :setHandles 
                           OR Usuario_Instagram__c IN :setHandles 
                           OR Instagram_Link__c IN :setHandles 
                           OR Usuario_Facebook__c IN :setHandles 
                           OR Facebook_Link__c IN :setHandles 
                           LIMIT 1000];   */
            
            System.debug('retrieveCitizens [' + lstSOSLResult +'] <-'); 
            mapContactPosts = new Map<Contact,List<SocialPost>>();
            
            if(!lstSOSLResult.isEmpty()) {
                for(List<Contact> lstResults : lstSOSLResult) {
                    for(Contact objContact : lstResults) {                         
                        mapContactPosts.put(objContact, new List<SocialPost>());
                        
                        for(SocialPost objSocialPost : lstSocialPosts) {
                            if(objSocialPost.Handle == objContact.Usuario_Twitter__c || objSocialPost.Handle == objContact.Usuario_Facebook__c) {
                                mapContactPosts.get(objContact).add(objSocialPost);
                                System.debug('retrieveCitizens [Found : ' + objContact +'] <-'); 
                            }                        
                        }
                    }
                }
            }
        } catch(Exception Ex) {
            System.debug('retrieveCitizens [' + Ex.getMessage() + ']');
            System.debug('retrieveCitizens [' + Ex.getStackTraceString() + ']');
        }
        
        System.debug('retrieveCitizens [' + mapContactPosts +'] <-');  
        
        return mapContactPosts;                
    }
    
    private static void sendNotifications(Map<Contact,List<SocialPost>> mapContactSocialPost, List<Social_Media_Sends__c> lstSocialMediaSends) {
        MarketingCloudAPIHandler objMC = null;
        RemotingMessageHelper.MarketingCloudAccessToken objAccessToken = null;
        List<RemotingMessageHelper.Subscriber> lstSubscribersSMS = null;
        List<RemotingMessageHelper.Subscriber> lstSubscribersEmail = null;
        List<RemotingMessageHelper.Subscriber> lstSubscribersWhatsApp = null;
        RemotingMessageHelper.Subscriber objSubscriber = null;
        Set<String> setPhoneNumbers = null;
        Set<String> setEmails = null;
        String strMobilePhone = null;
        
        System.debug('sendNotifications [ mapContactSocialPost : ' + mapContactSocialPost + ' : lstSocialMediaSends : ' + lstSocialMediaSends + '] ->'); 
        if(mapContactSocialPost != null && !mapContactSocialPost.isEmpty() && lstSocialMediaSends != null && !lstSocialMediaSends.isEmpty()) {
            setPhoneNumbers = new  Set<String>();
            setEmails = new  Set<String>();
            lstSubscribersSMS = new List<RemotingMessageHelper.Subscriber>();
            lstSubscribersEmail = new List<RemotingMessageHelper.Subscriber>();
            lstSubscribersWhatsApp = new List<RemotingMessageHelper.Subscriber>();
            
            for(Contact objCitizen : mapContactSocialPost.keySet()) {
                System.debug('sendNotifications [ processing citizen : ' + objCitizen + ' ]'); 

                for(SocialPost objSocialPost : mapContactSocialPost.get(objCitizen)) {
                    System.debug('sendNotifications [ processing post : ' + objSocialPost + ' ]'); 

                    for(Social_Media_Sends__c objSocialMediaSend : lstSocialMediaSends) {
                        //chequeo el hashtag yo el source son handleados
                        strMobilePhone = objCitizen.MobilePhone;
                                     
                        System.debug('sendNotifications [Hashtag : ' + objSocialMediaSend.Social_Source__r.Name + ' : ' + objSocialPost.TopicProfileName + ' ]');
                        System.debug('sendNotifications [Hashtag : ' + objSocialMediaSend.Social_Media__r.Name + ' : ' + objSocialPost.MediaProvider + ' ]');
                        if(objSocialMediaSend.Social_Source__r.Name == objSocialPost.TopicProfileName && objSocialMediaSend.Social_Media__r.Name == objSocialPost.MediaProvider) {
                            objSubscriber = new RemotingMessageHelper.Subscriber();
                            objSubscriber.MobileNumber = strMobilePhone;
                            objSubscriber.SubscriberKey = strMobilePhone;
                            objSubscriber.Attributes.put('Nombre', objCitizen.FirstName);
                            objSubscriber.Attributes.put('Tema', objSocialPost.Content );
                            objSubscriber.Attributes.put('twitterHandle', objSocialPost.Handle );
                            
                            if(objSocialMediaSend.Social_Destination__r.Name == 'Whats App') {
                                System.debug('sendNotifications [Adding WhatsApp]');
                                if(!strMobilePhone.startsWith('549')) {
                                    strMobilePhone = strMobilePhone.substring(0,2) + '9' + strMobilePhone.substring(2, strMobilePhone.length());
                                }
                                objSubscriber.MobileNumber = strMobilePhone;
                                lstSubscribersWhatsApp.add(objSubscriber);
                            } else if(objSocialMediaSend.Social_Destination__r.Name == 'SMS') {
                                System.debug('sendNotifications [SMS]');
                                if(strMobilePhone.startsWith('549')) {
                                    strMobilePhone = strMobilePhone.substring(0,2) + strMobilePhone.substring(3, strMobilePhone.length());
                                }
                                objSubscriber.MobileNumber = strMobilePhone;
                                if(!setPhoneNumbers.contains(strMobilePhone) ) {
                                    lstSubscribersSMS.add(objSubscriber);
                                    setPhoneNumbers.add(strMobilePhone); 
                                }
                            } else if(objSocialMediaSend.Social_Destination__r.Name == 'Email') {
                                System.debug('sendNotifications [Email]');
                                lstSubscribersEmail.add(objSubscriber);
                                setEmails.add(objCitizen.Email); 
                            }                          
                        }
                    }
                }             
            } 
            
            objMC = new MarketingCloudAPIHandler();
            //objAccessToken = objMC.retrieveAccessToken();  
            
            System.debug('sendNotifications [ objAccessToken : ' + objAccessToken + ']');
            System.debug('sendNotifications [ lstSubscribersSMS : ' + lstSubscribersSMS + ']');
            System.debug('sendNotifications [ lstSubscribersWhatsApp : ' + lstSubscribersWhatsApp + ']');
            System.debug('sendNotifications [ lstSubscribersEmail : ' + lstSubscribersEmail + ']');
            
            System.debug('sendNotifications [ setEmails : ' + setEmails + ']');
            
            if(!lstSubscribersSMS.IsEmpty()) {
                //objMC.sendSMS(objAccessToken, lstSubscribersSMS );                    
            }
            
            if(!setEmails.IsEmpty()) {
                //objMC.sendEmail(objAccessToken, setEmails );                
            } 
            
            if(!lstSubscribersWhatsApp.isEmpty()) {
                System.debug('sending whats app messages');
                WhatsAppAPI.sendMessages(lstSubscribersWhatsApp);                              
            }
        } else {
            System.debug('sendNotifications [ Citizens are NULL ]');
        }
    }
    
    private static List<Social_Media_Sends__c>  retrieveSocialMediaSendsConfiguration() {
        List<Social_Media_Sends__c> lstSocialMediaSends = null;
        
        lstSocialMediaSends = [SELECT ID, Social_Destination__r.Name, Social_Media__r.Name, Social_Source__r.Name
                               FROM Social_Media_Sends__c
                               WHERE Active__c = TRUE];
        
        return lstSocialMediaSends;
    }
    
        /*
    @future(callout=true)
    private static void updateAccessToken() { 
        MarketingCloudAPIHandler objMC = null;
        
        objMC = new MarketingCloudAPIHandler();
        objMC.updateAccessToken();
    }
    
    @future(callout=true)
    private static void sendNotifications(String strJSONCitizens, String strJSONConfiguration) {
        Map<Contact,List<SocialPost>> mapContactSocialPost = null;
        List<Social_Media_Sends__c> lstSocialMediaSends = null;
        
        System.debug('sendNotifications [ strJSONCitizens : ' + strJSONCitizens + ' - strJSONConfiguration : ' + strJSONConfiguration + '] ->');
        if(String.isNotBlank(strJSONCitizens) && String.isNotBlank(strJSONConfiguration) ) {
            mapContactSocialPost = (Map<Contact,List<SocialPost>>)JSON.deserialize(strJSONCitizens, Map<Contact,List<SocialPost>>.class);
            lstSocialMediaSends = (List<Social_Media_Sends__c>)JSON.deserialize(strJSONConfiguration, List<Social_Media_Sends__c>.class);
        
            sendNotifications(mapContactSocialPost, lstSocialMediaSends);
        }
        
        System.debug('sendNotifications [] <-');
    }
*/
}