force-app/main/default/objects/Contact/fields/guid__c.field-meta.xml
<CustomField>
    <fullName>guid__c</fullName>
    <externalId>true</externalId>
    <label>GUID</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Usuario_Twitter__c.field-meta.xml
<CustomField>
    <fullName>Usuario_Twitter__c</fullName>
    <label>Usuario Twitter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Cloud_Settings__c/Marketing_Cloud_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Marketing Cloud Settings</label>
</CustomObject>

force-app/main/default/objects/Marketing_Cloud_Settings__c/fields/ClientId__c.field-meta.xml
<CustomField>
    <fullName>ClientId__c</fullName>
    <description>Client Id of the created application in Marketing Cloud</description>
    <inlineHelpText>Client Id of the created application in Marketing Cloud</inlineHelpText>
    <label>ClientId</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Cloud_Settings__c/fields/ClientSecret__c.field-meta.xml
<CustomField>
    <fullName>ClientSecret__c</fullName>
    <description>Client secret of the created application in Marketing Cloud</description>
    <inlineHelpText>Client secret of the created application in Marketing Cloud</inlineHelpText>
    <label>ClientSecret</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Cloud_Settings__c/fields/Email_Sender_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Address__c</fullName>
    <description>Email Sender address</description>
    <inlineHelpText>Email Sender address</inlineHelpText>
    <label>Email Sender Address</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Marketing_Cloud_Settings__c/fields/Email_Sender_Name__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Name__c</fullName>
    <description>Email Sender Name</description>
    <inlineHelpText>Email Sender Name</inlineHelpText>
    <label>Email Sender Name</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Cloud_Settings__c/fields/EmailMessageId__c.field-meta.xml
<CustomField>
    <fullName>EmailMessageId__c</fullName>
    <description>External Id of the triggered Marketing Cloud Email</description>
    <inlineHelpText>External Id of the triggered Marketing Cloud Email</inlineHelpText>
    <label>EmailMessageId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Cloud_Settings__c/fields/ShortCode__c.field-meta.xml
<CustomField>
    <fullName>ShortCode__c</fullName>
    <description>Marketing Cloud SMS Short Code</description>
    <inlineHelpText>Marketing Cloud SMS Short Code</inlineHelpText>
    <label>ShortCode</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Cloud_Settings__c/fields/SMSKeyword__c.field-meta.xml
<CustomField>
    <fullName>SMSKeyword__c</fullName>
    <description>SMS Message keyword in Marketing Cloud (Looks like FREETEXT / BAJA / ETC )</description>
    <inlineHelpText>SMS Message keyword in Marketing Cloud (Looks like FREETEXT / BAJA / ETC )</inlineHelpText>
    <label>SMSKeyword</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Cloud_Settings__c/fields/SMSMessageId__c.field-meta.xml
<CustomField>
    <fullName>SMSMessageId__c</fullName>
    <description>SMS Message Id in Marketing Cloud (Looks like MTIzOjc4OjA )</description>
    <inlineHelpText>SMS Message Id in Marketing Cloud (Looks like MTIzOjc4OjA )</inlineHelpText>
    <label>SMSMessageId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Social_Destination__c/Social_Destination__c.object-meta.xml
<CustomObject>
    <label>Social Destination</label>
    <nameField>
        <label>Social Media Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Social Destinations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Social_Media__c/Social_Media__c.object-meta.xml
<CustomObject>
    <label>Social Media</label>
    <nameField>
        <label>Social Media</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Social Medias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Social_Media_Sends__c/Social_Media_Sends__c.object-meta.xml
<CustomObject>
    <label>Social Media Send</label>
    <nameField>
        <displayFormat>SMS-{000000}</displayFormat>
        <label>Social Media Sends Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Social Media Sends</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Social_Media_Sends__c/fields/Social_Destination__c.field-meta.xml
<CustomField>
    <fullName>Social_Destination__c</fullName>
    <label>Social Destination</label>
    <referenceTo>Social_Destination__c</referenceTo>
    <relationshipLabel>Social Media Sends</relationshipLabel>
    <relationshipName>Social_Media_Sends</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Social_Media_Sends__c/fields/Social_Media__c.field-meta.xml
<CustomField>
    <fullName>Social_Media__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Social Media</label>
    <referenceTo>Social_Media__c</referenceTo>
    <relationshipLabel>Social Media Sends</relationshipLabel>
    <relationshipName>Social_Media_Sends</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Social_Media_Sends__c/fields/Social_Source__c.field-meta.xml
<CustomField>
    <fullName>Social_Source__c</fullName>
    <label>Social Source</label>
    <referenceTo>Social_Source__c</referenceTo>
    <relationshipLabel>Social Media Sends</relationshipLabel>
    <relationshipName>Social_Media_Sends</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Social_Source__c/Social_Source__c.object-meta.xml
<CustomObject>
    <label>Social Source</label>
    <nameField>
        <label>Hashtags</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Social Source</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SocialPostTriggerTest.cls
@isTest
private class SocialPostTriggerTest {
    private static String TWITTER_HANDLE = 'demotest';
    
    @testSetup
    private static void setupTest() {
        createCitizen();
        insertMarketingCloudSettings();
        createSocialMediaSendsConfiguration();
    } 
    
    @isTest
    private static void testTwitterPost() {
        SocialPost objSocialPost = null;
        
        Test.setMock(HttpCalloutMock.class, new MarketingCloudAPIMock());
        Test.startTest();
        objSocialPost = new SocialPost();
        objSocialPost.Handle = TWITTER_HANDLE;
        objSocialPost.Provider = 'Twitter';
        objSocialPost.MediaProvider = 'Twitter';
        objSocialPost.Name = 'Twitter test';
        objSocialPost.TopicProfileName = '#ListenTestArgentina';        
        insert objSocialPost;
            
        SocialPostController.sendNotifications([SELECT Name, Handle, TopicProfileName, MediaProvider FROM SocialPost]);
            
        Test.stopTest();
    }
    
    private static void createCitizen() {
        Contact objContact = null;
        
        objContact = new Contact();
        objContact.FirstName = 'Juan';
        objContact.LastName = 'Perez';
        objContact.Email = 'matias.rodriguez@prosumia.la';
        objContact.MobilePhone = '541167304156';
        objContact.Usuario_Twitter__c = TWITTER_HANDLE;
        objContact.guid__c = '111';
        objContact.RecordTypeId = [SELECT Id 
                                   FROM RecordType 
                                   WHERE sObjectType = 'Contact' 
                                   LIMIT 1].Id;
        
        insert objContact;        
    }
    
    private static void insertMarketingCloudSettings() {
        Marketing_Cloud_Settings__c objMarketingCloudSettings = null;
        
        System.debug('insertMarketingCloudSettings [] ->'); 
        
        objMarketingCloudSettings = new Marketing_Cloud_Settings__c();
        objMarketingCloudSettings.Name = 'ORG WIDE DEFAULTS';
        objMarketingCloudSettings.ClientId__c = 'b9679b57yusr2z8u0fgbijti';
        objMarketingCloudSettings.ClientSecret__c = 'EiOZQZClpr10wkEiU61Fkx9s';
        objMarketingCloudSettings.Email_Sender_Address__c = 'salesforce@prosumia.la';
        objMarketingCloudSettings.Email_Sender_Name__c = 'Prosumia';
        objMarketingCloudSettings.EmailMessageId__c = 'demoprosumia';
        objMarketingCloudSettings.ShortCode__c = '76767';
        objMarketingCloudSettings.SMSKeyword__c = 'FREETEXT';
        objMarketingCloudSettings.SMSMessageId__c = 'MTIzOjc4OjA';
        objMarketingCloudSettings.SetupOwnerId = UserInfo.getOrganizationId();
        
        insert objMarketingCloudSettings;        
        
        System.debug('insertMarketingCloudSettings [ ' + objMarketingCloudSettings + ' ] <-'); 
    }
    
    @isTest
    private static void createSocialMediaSendsConfiguration() {
        Social_Source__c objSource = null;
        Social_Destination__c objDestination = null;
		Social_Media_Sends__c objSMS = null;
        Social_Media__c objSocialMedia = null;
        
        objSource = new Social_Source__c();
        objSource.Name = '#ListenTestArgentina';
        insert objSource;

        objSocialMedia = new Social_Media__c();
        objSocialMedia.Name = 'Twitter';
        insert objSocialMedia;
        
        objDestination = new Social_Destination__c();
        objDestination.Name = 'Whats App';
        insert objDestination;
        
        objSMS = new Social_Media_Sends__c();
        objSMS.Active__c = true;
        objSMS.Social_Destination__c = objDestination.Id;
        objSMS.Social_Media__c = objSocialMedia.Id;
        objSMS.Social_Source__c = objSource.id;
        insert objSMS;
        
        objDestination = new Social_Destination__c();
        objDestination.Name = 'SMS';
        insert objDestination;
        
        objSMS = new Social_Media_Sends__c();
        objSMS.Active__c = true;
        objSMS.Social_Destination__c = objDestination.Id;
        objSMS.Social_Media__c = objSocialMedia.Id;
        objSMS.Social_Source__c = objSource.id;
        insert objSMS;
        
        objDestination = new Social_Destination__c();
        objDestination.Name = 'Email';
        insert objDestination;
        
        objSMS = new Social_Media_Sends__c();
        objSMS.Active__c = true;
        objSMS.Social_Destination__c = objDestination.Id;
        objSMS.Social_Media__c = objSocialMedia.Id;
        objSMS.Social_Source__c = objSource.id;
        insert objSMS;
    }
    
}