force-app/main/default/objects/Contact/fields/guid__c.field-meta.xml
<CustomField>
    <fullName>guid__c</fullName>
    <externalId>true</externalId>
    <label>GUID</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Covid19__c/Covid19__c.object-meta.xml
<CustomObject>
    <label>Covid19</label>
    <nameField>
        <label>Indice Cuidarnos</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Covid19s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Covid19__c/fields/Archive_Date__c.field-meta.xml
<CustomField>
    <fullName>Archive_Date__c</fullName>
    <label>Fecha Archivado</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Covid19__c/fields/Citizen__c.field-meta.xml
<CustomField>
    <fullName>Citizen__c</fullName>
    <label>Ciudadano</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Covid19s</relationshipLabel>
    <relationshipName>Cuidarnos_Datas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Covid19__c/fields/Contacto_Estrecho__c.field-meta.xml
<CustomField>
    <fullName>Contacto_Estrecho__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contacto Estrecho</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Covid19__c/fields/Contacto_Estrecho_GUID__c.field-meta.xml
<CustomField>
    <fullName>Contacto_Estrecho_GUID__c</fullName>
    <label>Contacto Estrecho GUID</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Covid19__c/fields/Cuidarnos_Comunidad_Date__c.field-meta.xml
<CustomField>
    <fullName>Cuidarnos_Comunidad_Date__c</fullName>
    <label>Fecha Estado</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Covid19__c/fields/Cuidarnos_Comunidad_Status__c.field-meta.xml
<CustomField>
    <fullName>Cuidarnos_Comunidad_Status__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sintomático</fullName>
            </value>
            <value>
                <fullName>Sospechoso</fullName>
            </value>
            <value>
                <fullName>Muestra</fullName>
            </value>
            <value>
                <fullName>Detectable</fullName>
            </value>
            <value>
                <fullName>No Detectable</fullName>
            </value>
            <value>
                <fullName>Inválido</fullName>
            </value>
            <value>
                <fullName>Notificado</fullName>
            </value>
            <value>
                <fullName>Descartado</fullName>
            </value>
            <value>
                <fullName>Asintomático</fullName>
                <label>Asintómatico</label>
            </value>
            <value>
                <fullName>Archivado</fullName>
            </value>
            <value>
                <fullName>Seguimiento COH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Covid19__c/fields/Cuidarnos_Muestra_Result__c.field-meta.xml
<CustomField>
    <fullName>Cuidarnos_Muestra_Result__c</fullName>
    <label>Muestra</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Detectable</fullName>
            </value>
            <value>
                <fullName>No Detectable</fullName>
            </value>
            <value>
                <fullName>Inválido</fullName>
            </value>
            <value>
                <fullName>Invalido</fullName>
                <isActive>false</isActive>
                <label>Invalido</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Covid19__c/fields/Cuidarnos_Muestra_Result_Date__c.field-meta.xml
<CustomField>
    <fullName>Cuidarnos_Muestra_Result_Date__c</fullName>
    <label>Fecha Muestra</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Covid19__c/fields/Estado_Epidemiologico__c.field-meta.xml
<CustomField>
    <fullName>Estado_Epidemiologico__c</fullName>
    <label>Estado Epidemiologico</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Covid19__c/fields/Notificacion_Date__c.field-meta.xml
<CustomField>
    <fullName>Notificacion_Date__c</fullName>
    <label>Fecha Notificado</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/updateCuidarnosContactoEstrecho_Batch.cls
global  without sharing class updateCuidarnosContactoEstrecho_Batch  implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator([
            SELECT Id , Citizen__c, Cuidarnos_Comunidad_Status__c , LastModifiedDate, Cuidarnos_Comunidad_Date__c, Estado_Epidemiologico__c, Contacto_Estrecho__c, Contacto_Estrecho_GUID__c
            FROM Covid19__c
            WHERE Contacto_Estrecho__c = True
        ]);
    }

    global void execute(Database.BatchableContext BC, List<Covid19__c> lstCuidarnosCovid){
        for (Covid19__c objCovid19: lstCuidarnosCovid) {
            try {

                // UPDATE Status to DETECTABLE
                objCovid19.Cuidarnos_Muestra_Result__c = 'Detectable';
                objCovid19.Cuidarnos_Muestra_Result_Date__c = DateTime.now();
                objCovid19.Cuidarnos_Comunidad_Status__c = 'Detectable';
                objCovid19.Cuidarnos_Comunidad_Date__c = DateTime.now();
                
                // NOTIFY User
                PRM_Cuidarnos.saveUserObservationsInSalesforce(objCovid19.Citizen__c, 'El usuario fue notificado');
                PRM_Cuidarnos.publicNotifyUserSMSFuture(objCovid19.Citizen__c);
    
                // UPDATE status to NOTIFICADO
                objCovid19.Cuidarnos_Comunidad_Status__c = 'Notificado';
                objCovid19.Cuidarnos_Comunidad_Date__c = DateTime.now();
                objCovid19.Notificacion_Date__c = DateTime.now();

                // CLEAN Archive Date and Estado Epidemiologico
                objCovid19.Archive_Date__c = null;
                objCovid19.Estado_Epidemiologico__c = null;

                // ADD Observation Message
                String observation = 'Ciudadano en estado DETECTABLE por contacto estrecho.';
                if (!String.isBlank(objCovid19.Contacto_Estrecho_GUID__c)) {
                    List<Contact> lstContactoEstrecho = [SELECT Id, Name FROM Contact WHERE guid__c = :objCovid19.Contacto_Estrecho_GUID__c];
                    if (!lstContactoEstrecho.isEmpty()) {
                        observation = 'Ciudadano en estado DETECTABLE por contacto estrecho con ' + lstContactoEstrecho[0].Name;
                    }
                }
                PRM_Cuidarnos.saveUserObservationsInSalesforce(objCovid19.Citizen__c, observation);

                // CLEAN Contacto Estrecho to FALSE to avoid re-processing
                objCovid19.Contacto_Estrecho__c = false;
                objCovid19.Contacto_Estrecho_GUID__c = null;

                // UPDATE Covid19 Object
                update objCovid19;
                
            } catch (Exception e) {
                System.debug('An exception occurred: ' + e.getMessage());
            }
        }
    }

    global void finish(Database.BatchableContext BC) {
    }
}