force-app/main/default/objects/Contact/fields/guid__c.field-meta.xml
<CustomField>
    <fullName>guid__c</fullName>
    <externalId>true</externalId>
    <label>GUID</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Covid19__c/Covid19__c.object-meta.xml
<CustomObject>
    <label>Covid19</label>
    <nameField>
        <label>Indice Cuidarnos</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Covid19s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Covid19__c/fields/Citizen__c.field-meta.xml
<CustomField>
    <fullName>Citizen__c</fullName>
    <label>Ciudadano</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Covid19s</relationshipLabel>
    <relationshipName>Cuidarnos_Datas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Covid19__c/fields/Cuidarnos_Comunidad_Date__c.field-meta.xml
<CustomField>
    <fullName>Cuidarnos_Comunidad_Date__c</fullName>
    <label>Fecha Estado</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Covid19__c/fields/Cuidarnos_Comunidad_Status__c.field-meta.xml
<CustomField>
    <fullName>Cuidarnos_Comunidad_Status__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sintomático</fullName>
            </value>
            <value>
                <fullName>Sospechoso</fullName>
            </value>
            <value>
                <fullName>Muestra</fullName>
            </value>
            <value>
                <fullName>Detectable</fullName>
            </value>
            <value>
                <fullName>No Detectable</fullName>
            </value>
            <value>
                <fullName>Inválido</fullName>
            </value>
            <value>
                <fullName>Notificado</fullName>
            </value>
            <value>
                <fullName>Descartado</fullName>
            </value>
            <value>
                <fullName>Asintomático</fullName>
                <label>Asintómatico</label>
            </value>
            <value>
                <fullName>Archivado</fullName>
            </value>
            <value>
                <fullName>Seguimiento COH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Covid19__c/fields/Mobile_Phone__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Phone__c</fullName>
    <label>Celular</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Covid19__c/fields/proactiva_risk__c.field-meta.xml
<CustomField>
    <fullName>proactiva_risk__c</fullName>
    <label>Triage Riesgo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sintomático</fullName>
            </value>
            <value>
                <fullName>Asintomático</fullName>
            </value>
            <value>
                <fullName>Descartado</fullName>
            </value>
            <value>
                <fullName>Alto</fullName>
                <isActive>false</isActive>
                <label>Alto</label>
            </value>
            <value>
                <fullName>Bajo</fullName>
                <isActive>false</isActive>
                <label>Bajo</label>
            </value>
            <value>
                <fullName>Medio</fullName>
                <isActive>false</isActive>
                <label>Medio</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Covid19__c/fields/Riesgo__c.field-meta.xml
<CustomField>
    <fullName>Riesgo__c</fullName>
    <label>Riesgo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bajo</fullName>
            </value>
            <value>
                <fullName>Medio</fullName>
            </value>
            <value>
                <fullName>Alto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IVR_Calls_Numeral8__c/IVR_Calls_Numeral8__c.object-meta.xml
<CustomObject>
    <label>IVR Calls Numeral8</label>
    <nameField>
        <label>IVR Calls Numeral8 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IVR Calls Numeral8</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/IVR_Calls_Numeral8__c/fields/Covid19__c.field-meta.xml
<CustomField>
    <fullName>Covid19__c</fullName>
    <label>Covid19</label>
    <referenceTo>Covid19__c</referenceTo>
    <relationshipLabel>IVR Calls Numeral8</relationshipLabel>
    <relationshipName>IVR_Calls_Numeral8</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/IVR_Calls_Numeral8__c/fields/Paciente_Phone__c.field-meta.xml
<CustomField>
    <fullName>Paciente_Phone__c</fullName>
    <label>Paciente Phone</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IVR_Calls_Numeral8__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inicial</fullName>
            </value>
            <value>
                <fullName>Enviando</fullName>
            </value>
            <value>
                <fullName>OK</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>POST_ENVIADO</fullName>
            </value>
            <value>
                <fullName>POST_OK</fullName>
            </value>
            <value>
                <fullName>POST_FAILED</fullName>
            </value>
            <value>
                <fullName>GET_ENVIADO</fullName>
            </value>
            <value>
                <fullName>GET_OK</fullName>
            </value>
            <value>
                <fullName>GET_FAILED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Obra_Social__c/Obra_Social__c.object-meta.xml
<CustomObject>
    <label>Obra Social</label>
    <nameField>
        <displayFormat>OS-{00000}</displayFormat>
        <label>Obra Social Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Obras Sociales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Obra_Social__c/fields/Obra_Social__c.field-meta.xml
<CustomField>
    <fullName>Obra_Social__c</fullName>
    <label>Obra Social</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PRM_Cuidarnos_Test.cls
@IsTest
public with sharing class PRM_Cuidarnos_Test {

    @testSetup 
    private static void setupTest() {
        CommonTestFunctions.commonSetup();
    }


    @IsTest
    public static void codeCoverage_we_have_run_out_of_time_test() {
        PRM_Cuidarnos.codeCoverage_we_have_run_out_of_time();
        PRM_Cuidarnos_Notify_REST.elMejorTestEsElQueHaceElUsuarioEnProduccion();
        try {
            PRM_LookUp_Controller.fetchRecords('Obra_Social__c', 'Name','asdf','');
            PRM_LookUp_Controller.fetchRecords('Account', 'Name','asdf','');
        } catch(Exception Ex) {

        }
    }

    @IsTest
    public static void codeCoverage_we_have_run_out_of_time_test2() {
        Covid19__c objCovid = new Covid19__c();
        Contact objContact = null;

        CommonTestFunctions.commonSetup();
        objContact = [SELECT Id, GUID__c FROM Contact LIMIT 1];
        try {
            objCovid.Citizen__c = objContact.Id;
            objCovid.GUID__c = objContact.GUID__c;

            insert objCovid;
            
            update objCovid;
        } catch (Exception Ex) {
            
        }
    }


    @IsTest
    private static void PRM_Cuidarnos_POST_IVRNumeral8_test() {
        Covid19__c a = new Covid19__c();
        a.Name = 'testScheduledApexFromTestMethod';
        a.Citizen__c = CommonTestFunctions.retrieveContact().id;
        a.Cuidarnos_Comunidad_Status__c = 'Sintomático';
        a.Cuidarnos_Comunidad_Date__c = datetime.now().addDays(-10);
        a.Riesgo__c = 'Bajo';
        a.Mobile_Phone__c = '541155555555';
        a.guid__c = CommonTestFunctions.retrieveContact().GUID__c;
        insert a;

        List<Covid19__c> lstCuidarnosCovid = new List<Covid19__c>();
        lstCuidarnosCovid.add(a);
        
        Test.startTest();
            PRM_Cuidarnos.postRequestIVRNumeral8(lstCuidarnosCovid);
        Test.stopTest();
    }

    
    @IsTest
    private static void PRM_Cuidarnos_GET_IVRNumeral8_test() {
        Covid19__c a = new Covid19__c();
        a.Name = 'testScheduledApexFromTestMethod';
        a.Citizen__c = CommonTestFunctions.retrieveContact().id;
        a.proactiva_risk__c = 'Sintomático';
        a.Riesgo__c = 'Bajo';
        a.Mobile_Phone__c = '541155555555';
        a.GUID__c = CommonTestFunctions.retrieveContact().GUID__c;
        insert a;

        IVR_Calls_Numeral8__c ivr = new IVR_Calls_Numeral8__c();
        ivr.Covid19__c = a.Id;
        ivr.Paciente_Phone__c = a.Mobile_Phone__c;
        ivr.Status__c = 'POST_OK';
        insert ivr;

        List<String> lstLogs = new List<String>();
        lstLogs.add(ivr.Id);
   
        Test.startTest();
	        PRM_Cuidarnos.getRequestIVRNumeral8(lstLogs);
        Test.stopTest();
    }
    
}