force-app/main/default/objects/Contact/fields/guid__c.field-meta.xml
<CustomField>
    <fullName>guid__c</fullName>
    <externalId>true</externalId>
    <label>GUID</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Covid19__c/Covid19__c.object-meta.xml
<CustomObject>
    <label>Covid19</label>
    <nameField>
        <label>Indice Cuidarnos</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Covid19s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Covid19__c/fields/Citizen__c.field-meta.xml
<CustomField>
    <fullName>Citizen__c</fullName>
    <label>Ciudadano</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Covid19s</relationshipLabel>
    <relationshipName>Cuidarnos_Datas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Covid19__c/fields/Notificacion_Date__c.field-meta.xml
<CustomField>
    <fullName>Notificacion_Date__c</fullName>
    <label>Fecha Notificado</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Covid19__c/fields/Notifier_User__c.field-meta.xml
<CustomField>
    <fullName>Notifier_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Usuario actualizador de fecha de notificación</description>
    <label>Notifier User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Covid19s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_BatchCovid19UpdateNotifierUser.cls
@isTest
private class Test_BatchCovid19UpdateNotifierUser {
    @testSetup
    public static void setupTest() {
       CommonTestFunctions.commonSetup();
    }
    
    @isTest
    public static void batchUpdateNotifier() {        
        Covid19__c objCovid = new Covid19__c();
        Contact objContact = null;

        CommonTestFunctions.commonSetup();
        objContact = [SELECT Id, GUID__c FROM Contact LIMIT 1];
        try {
            objCovid.Citizen__c = objContact.Id;
            objCovid.GUID__c = objContact.GUID__c;

            insert objCovid;
            
        } catch (Exception Ex) {
            
        }

        objCovid.Notificacion_Date__c = Datetime.now();

        update objCovid;

        objCovid.Notifier_User__c = null;

        update objCovid;

        Test.startTest();

        Database.executeBatch(new BatchCovid19UpdateNotifierUser());

        Test.stopTest();
    }
}