force-app/main/default/objects/Contact/fields/guid__c.field-meta.xml
<CustomField>
    <fullName>guid__c</fullName>
    <externalId>true</externalId>
    <label>GUID</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SearchCriteria__c.field-meta.xml
<CustomField>
    <fullName>SearchCriteria__c</fullName>
    <label>Search Criteria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Argentino.recordType-meta.xml
<RecordType>
    <fullName>Argentino</fullName>
    <active>true</active>
    <description>Tipo de Registro default para Contactos de Prosumia.</description>
    <label>Argentino</label>
</RecordType>

force-app/main/default/classes/ContactsCSVControllerTest.cls
@isTest
public class ContactsCSVControllerTest {

    @isTest
    static void readFileTestSemicolon() {
        Contact con = new Contact();
        con.SearchCriteria__c = '22/01/2001F609';
        con.LastName = 'Test';
        con.guid__c = '123';
        con.RecordTypeId = [SELECT Id 
                            FROM RecordType 
                            WHERE sObjectType = 'Contact' 
                            AND DeveloperName = 'Argentino' 
                            LIMIT 1].Id;
        insert con;
        ContactsCSVController conCSV = new ContactsCSVController();
        conCSV.selectedSearchCriteria = 'SearchCriteria__c';
        conCSV.contentFile = Blob.valueOf('a;22/01/2001F609\r\n'.repeat(2000));
        conCSV.nameFile = 'test.csv';
        conCSV.ReadFile();
    }
    
    @isTest
    static void readFileTestComma() {
        Contact con = new Contact();
        con.SearchCriteria__c = '22/01/2001F609';
        con.LastName = 'Test';
        con.guid__c = '123';
        con.RecordTypeId = [SELECT Id 
                            FROM RecordType 
                            WHERE sObjectType = 'Contact' 
                            AND DeveloperName = 'Argentino' 
                            LIMIT 1].Id;
        insert con;
        ContactsCSVController conCSV = new ContactsCSVController();
        conCSV.selectedSearchCriteria = 'SearchCriteria__c';
        conCSV.contentFile = Blob.valueOf('a,22/01/2001F609\r\n'.repeat(2000));
        conCSV.nameFile = 'test.csv';
        conCSV.ReadFile();
    }
}