force-app/main/default/objects/Contact/fields/RiverId_cat_socio__c.field-meta.xml
<CustomField>
    <fullName>RiverId_cat_socio__c</fullName>
    <label>Categoría de socio</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/RiverId_fecha_socio__c.field-meta.xml
<CustomField>
    <fullName>RiverId_fecha_socio__c</fullName>
    <label>Fecha de alta de socio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/RiverId_Nro_socio__c.field-meta.xml
<CustomField>
    <fullName>RiverId_Nro_socio__c</fullName>
    <label>Numero de socio</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RiverId__c/RiverId__c.object-meta.xml
<CustomObject>
    <label>RiverId</label>
    <nameField>
        <label>RiverId Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RiverIds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RiverId__c/fields/cat_socio__c.field-meta.xml
<CustomField>
    <fullName>cat_socio__c</fullName>
    <label>Categoría de Socio</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RiverId__c/fields/fecha_socio__c.field-meta.xml
<CustomField>
    <fullName>fecha_socio__c</fullName>
    <label>Fecha de Alta de Socio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RiverId__c/fields/nro_socio__c.field-meta.xml
<CustomField>
    <fullName>nro_socio__c</fullName>
    <label>Numero de Socio</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/RiverId__c/fields/riverid_citizen__c.field-meta.xml
<CustomField>
    <fullName>riverid_citizen__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RiverIdCitizen</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>RiverIds</relationshipLabel>
    <relationshipName>RiverIds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RiverIdBatch.cls
global class RiverIdBatch implements Database.Batchable<sObject>,Database.Stateful {
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator([SELECT Id, nro_socio__c, riverid_citizen__c, fecha_socio__c, cat_socio__c 
                                        FROM RiverId__c]);
    }
    global void execute(Database.BatchableContext BC, List<RiverId__c> scope){
        Map<Id,RiverId__c> riverIdRecord_ByRelatedContactId = new Map<Id,RiverId__c> ();

        for(RiverId__c thisRiverId : scope){
            riverIdRecord_ByRelatedContactId.put(thisRiverId.riverid_citizen__c,thisRiverId);
        }

        List<Contact> relatedContacts = [SELECT id,RiverId_Nro_socio__c,RiverId_fecha_socio__c,RiverId_cat_socio__c 
                                            FROM contact 
                                            WHERE id IN: riverIdRecord_ByRelatedContactId.keySet()];

        List<Contact> contactsToUpdate = new List<Contact> ();

        for(Contact thisContact : relatedContacts){
            RiverId__c riverIdRecord = riverIdRecord_ByRelatedContactId.get(thisContact.Id);
            
            Boolean updateThisContact = false;

            //if (riverIdRecord.nro_socio__c != thisContact.RiverId_Nro_socio__c) {
                thisContact.RiverId_Nro_socio__c = riverIdRecord.nro_socio__c.toplainstring();
                updateThisContact = true;
            //}
            if (riverIdRecord.fecha_socio__c != thisContact.RiverId_fecha_socio__c) {
                thisContact.RiverId_fecha_socio__c = riverIdRecord.fecha_socio__c;
                updateThisContact = true;
            }
            if (riverIdRecord.cat_socio__c != thisContact.RiverId_cat_socio__c) {
                thisContact.RiverId_cat_socio__c = riverIdRecord.cat_socio__c;
                updateThisContact = true;
                
            }
            if(updateThisContact){
                contactsToUpdate.add(thisContact);
            }
        }

        if (contactsToUpdate.size()>0) {
            Update contactsToUpdate;
        }
    }

    global void finish(Database.BatchableContext BC) {
        //:D
    }
}