force-app/main/default/objects/Encuesta__c/Encuesta__c.object-meta.xml
<CustomObject>
    <label>Encuesta</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Encuesta Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Encuestas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Encuesta__c/fields/AdvertinsingID__c.field-meta.xml
<CustomField>
    <fullName>AdvertinsingID__c</fullName>
    <label>AdvertinsingID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Encuesta__c/fields/Number_Of_Questions__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Questions__c</fullName>
    <label>Number Of Questions</label>
    <summaryForeignKey>Survey_Question__c.Survey__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Encuesta__c/fields/Number_of_Questions_VIew__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Questions_VIew__c</fullName>
    <label>Number of Questions (VIew)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Encuesta__c/fields/TituloEncuesta__c.field-meta.xml
<CustomField>
    <fullName>TituloEncuesta__c</fullName>
    <label>TituloEncuesta</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Encuesta__c/fields/TypeformId__c.field-meta.xml
<CustomField>
    <fullName>TypeformId__c</fullName>
    <externalId>true</externalId>
    <label>TypeformId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Setting__mdt/Survey_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Survey Setting</label>
    <pluralLabel>Survey_Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Survey_Setting__mdt/fields/Crypto_Message_Public_Key__c.field-meta.xml
<CustomField>
    <fullName>Crypto_Message_Public_Key__c</fullName>
    <label>Crypto Message Public Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Setting__mdt/fields/Crypto_Message_Secret_Key__c.field-meta.xml
<CustomField>
    <fullName>Crypto_Message_Secret_Key__c</fullName>
    <label>Crypto Message Secret Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Setting__mdt/fields/Facebook_Url__c.field-meta.xml
<CustomField>
    <fullName>Facebook_Url__c</fullName>
    <label>Facebook_Url</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Survey_Setting__mdt/fields/Instagram_Url__c.field-meta.xml
<CustomField>
    <fullName>Instagram_Url__c</fullName>
    <label>Instagram_Url</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Survey_Setting__mdt/fields/Survey_Domain__c.field-meta.xml
<CustomField>
    <fullName>Survey_Domain__c</fullName>
    <label>Survey Domain</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Survey_Setting__mdt/fields/Twitter_Url__c.field-meta.xml
<CustomField>
    <fullName>Twitter_Url__c</fullName>
    <label>Twitter_Url</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Survey_Setting__mdt/fields/TypeForm_Url__c.field-meta.xml
<CustomField>
    <fullName>TypeForm_Url__c</fullName>
    <label>TypeForm_Url</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/Pulso_Home_Controller.cls
public class Pulso_Home_Controller {
    public class PulsoSurveyException extends Exception {} 
    private Survey_Setting__mdt objSurveySettings = null;
     
    public RemotingMessageHelper.Pulso pulso { get; set;}
    public RemotingMessageHelper.PulsoSurvey survey { get; set;}
    public String QSParameters { get; set; }

    public Pulso_Home_Controller() {
        String strSurveyId = null;

        objSurveySettings = HelperFunctions.retrieveSurveySettings('Pulso_CRM');
        strSurveyId = ApexPages.currentPage().getParameters().get('surveyid');
        
        if(String.isNotBlank(strSurveyId)) {
            pulso = retrievePulsoData(objSurveySettings);
            survey = retrieveSurvey(strSurveyId);
            
            QSParameters = retrieveQueryStringParameters(survey);
        } 
    }
    
    public PageReference validateOrRedirect() {
        PageReference objPage = null;
        
        if(survey == NULL) {
            objPage = new PageReference('https://pulso.social');
            objPage.setRedirect(true);
        }
        
        return objPage;
    }
    
    @RemoteAction
    public static String retrieveEncryptData(String strFacebookId) { 
        String strPlainText = null;
        Blob blbEncrypted = null;
        Survey_Setting__mdt objSurveySettings = null;
        
        objSurveySettings = HelperFunctions.retrieveSurveySettings('Pulso_CRM');
        
        strPlainText = String.format('{0}{1}', new String[] { strFacebookId, objSurveySettings.Crypto_Message_Public_Key__c } );
                
        blbEncrypted = Crypto.encrypt('AES128', Blob.valueOf(objSurveySettings.Crypto_Message_Secret_Key__c), Blob.valueOf(objSurveySettings.Crypto_Message_Public_Key__c), Blob.valueOf(strPlainText));
        
        return EncodingUtil.base64Encode(blbEncrypted);
    }
        
    private String retrieveQueryStringParameters(RemotingMessageHelper.PulsoSurvey objSurvey) {
        Set<String> setQSParameter = null;
        String strQS = null;
        
        System.debug('retrieveQueryStringParameters [objSurvey : ' + objSurvey + ']');

        strQS = '';
        if(objSurvey != NULL) {
            setQSParameter = new Set<String>();
            //agrego los parametros que no se pueden sobreescribir
            setQSParameter.add('surveyid');
            setQSParameter.add('fbid');
            setQSParameter.add('mail');
            setQSParameter.add('d');
            setQSParameter.add('pulsohash');
            
            if(ApexPages.currentPage().getParameters() != NULL && ApexPages.currentPage().getParameters().size() > 0) {
                for(String strParameter : ApexPages.currentPage().getParameters().keySet()) {

                    if(!setQSParameter.contains(strParameter) ) {
                        setQSParameter.add(strParameter);
                        strQS += '&' + strParameter + '=' + ApexPages.currentPage().getParameters().get(strParameter);
                    } 
                }
            }
                         
            if(!setQSParameter.contains('f') && String.isNotBlank(objSurvey.advertisingid)) {
                strQS += '&f=' + objSurvey.advertisingid;
            }
            
            strQS += '&d=' +  ApexPages.currentPage().getHeaders().get('X-Salesforce-SIP');    
        }            
        return strQS;
    }
          
    private RemotingMessageHelper.Pulso retrievePulsoData(Survey_Setting__mdt objSurveySettings) {
        RemotingMessageHelper.Pulso objPulso = null;
        
        System.debug('retrievePulsoData [objSurveySettings : ' + objSurveySettings + '] <-');

        objPulso = new RemotingMessageHelper.Pulso();
        
        objPulso.TypeFormUrl = objSurveySettings.TypeForm_Url__c;
        objPulso.TwitterLink = objSurveySettings.Twitter_Url__c;
        objPulso.FacebookLink = objSurveySettings.Facebook_Url__c;
        objPulso.InstagramLink = objSurveySettings.Instagram_Url__c;                        
        objPulso.Domain = objSurveySettings.Survey_Domain__c;
        
        System.debug('retrievePulsoData [' + objPulso + '] <-');
        
        return objPulso;
    }
    
    private RemotingMessageHelper.PulsoSurvey retrieveSurvey(String strSurveyId) {
        List<Encuesta__c> lstSurveys = null;        
        RemotingMessageHelper.PulsoSurvey objSurvey = null;
        
        System.debug('retrieveDefaultSurvey [] <-');
        
        if(String.isNotBlank(strSurveyId)) {
            lstSurveys = [SELECT Id, TituloEncuesta__c, TypeformId__c, Description__c, Slug__c, Number_of_Questions_View__c, Number_Of_Questions__c,AdvertinsingID__c
                            FROM Encuesta__c 
                            WHERE TypeformId__c =: strSurveyId 
                            LIMIT 1];
        } 
        
        if(!lstSurveys.isEmpty()) {  
            objSurvey =  new RemotingMessageHelper.PulsoSurvey(lstSurveys[0]);            
        }
        
        System.debug('retrieveDefaultSurvey [' + objSurvey + '] <-');

        return objSurvey;
    }
    
}