force-app/main/default/objects/Encuesta__c/Encuesta__c.object-meta.xml
<CustomObject>
    <label>Encuesta</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Encuesta Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Encuestas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Encuesta__c/fields/Default_Survey__c.field-meta.xml
<CustomField>
    <fullName>Default_Survey__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default Survey</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Encuesta__c/fields/Number_Of_Answered_Questions__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Answered_Questions__c</fullName>
    <label>Number_Of_Answered_Questions</label>
    <summarizedField>User_Survey__c.Number_Of_Answered_Questions__c</summarizedField>
    <summaryForeignKey>User_Survey__c.Survey__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Encuesta__c/fields/Number_Of_Answering_Users__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Answering_Users__c</fullName>
    <label>Number_Of_Answering_Users</label>
    <summaryForeignKey>User_Survey__c.Survey__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Encuesta__c/fields/Number_Of_Questions__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Questions__c</fullName>
    <label>Number Of Questions</label>
    <summaryForeignKey>Survey_Question__c.Survey__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Encuesta__c/fields/TituloEncuesta__c.field-meta.xml
<CustomField>
    <fullName>TituloEncuesta__c</fullName>
    <label>TituloEncuesta</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Encuesta__c/fields/TypeformId__c.field-meta.xml
<CustomField>
    <fullName>TypeformId__c</fullName>
    <externalId>true</externalId>
    <label>TypeformId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Encuesta__c/fields/TypeformResultsId__c.field-meta.xml
<CustomField>
    <fullName>TypeformResultsId__c</fullName>
    <externalId>true</externalId>
    <label>TypeformResultsId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/Territorio_Administrativo__c.object-meta.xml
<CustomObject>
    <description>Objeto Custom para carga de Territorios de multiples paises, estructurado en 5 niveles</description>
    <label>Territorio</label>
    <nameField>
        <label>Territorio Administrativo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territorios</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Location_UUID__c.field-meta.xml
<CustomField>
    <fullName>Location_UUID__c</fullName>
    <description>Código único de Territorio Metapod</description>
    <externalId>true</externalId>
    <inlineHelpText>Código único de Territorio Metapod</inlineHelpText>
    <label>Location UUID</label>
    <length>24</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Nivel_Administrativo__c.field-meta.xml
<CustomField>
    <fullName>Nivel_Administrativo__c</fullName>
    <label>Nivel Administrativo</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ParentId</label>
    <referenceTo>Territorio_Administrativo__c</referenceTo>
    <relationshipLabel>Territories</relationshipLabel>
    <relationshipName>ChildTerritories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Pulso_Home_ControllerTest.cls
@IsTest
private class Pulso_Home_ControllerTest {
	
    @testSetup
    private static void initializeTest() {
        Territorio_Administrativo__c objTerritoryLevel0 = null;
        Territorio_Administrativo__c objTerritoryLevel1 = null;
        Territorio_Administrativo__c objTerritoryLevel2 = null;
 
        createSurvey();
        objTerritoryLevel0 = createTerritory( 0, 'Level 0', NULL);
        objTerritoryLevel1 = createTerritory( 1, 'Level 1', objTerritoryLevel0.Id);
        objTerritoryLevel2 = createTerritory( 2, 'Level 2', objTerritoryLevel1.Id);
    }
    
    @IsTest
    private static void homePageTest() {
        PageReference objPulsoHomeVF = null;
        Pulso_Home_Controller objPulsoHome = null;
        Encuesta__c objEncuesta = null;
        Territorio_Administrativo__c objTerritoryLevel0 = null;
        Territorio_Administrativo__c objTerritoryLevel1 = null;
        Territorio_Administrativo__c objTerritoryLevel2 = null;
        
        objPulsoHomeVF = Page.PulsoHome;
                        
        objEncuesta = [SELECT Id, Name,TypeformId__c, TituloEncuesta__c, Number_Of_Answered_Questions__c,Number_Of_Answering_Users__c,Number_Of_Questions__c
                       FROM Encuesta__c];

        objPulsoHomeVF.getParameters().put('surveyid',objEncuesta.TypeformId__c);
        Test.setCurrentPage(objPulsoHomeVF);
        objPulsoHome = new Pulso_Home_Controller();
        
        System.assertEquals(objEncuesta.TypeformId__c, objPulsoHome.survey.typeformid);
        System.assertEquals(NULL, objPulsoHome.validateOrRedirect());
        Pulso_Home_Controller.retrieveEncryptData('11111111');
        
        objTerritoryLevel0 = [SELECT Id FROM Territorio_Administrativo__c WHERE Nivel_Administrativo__c = 0];
        objTerritoryLevel1 = [SELECT Id FROM Territorio_Administrativo__c WHERE Nivel_Administrativo__c = 1];
        objTerritoryLevel2 = [SELECT Id FROM Territorio_Administrativo__c WHERE Nivel_Administrativo__c = 2];
        

        System.assertEquals(objTerritoryLevel0.Id, Pulso_Contact_Modal_Controller.retrieveTerritories(0, null)[0].Id);
        System.assertEquals(objTerritoryLevel1.Id, Pulso_Contact_Modal_Controller.retrieveTerritories(1, objTerritoryLevel0.Id)[0].Id);
        System.assertEquals(objTerritoryLevel2.Id, Pulso_Contact_Modal_Controller.retrieveTerritories(2, objTerritoryLevel1.Id)[0].Id);
    }
    
    private static void createSurvey() {
        Encuesta__c objEncuesta = null;
        
        objEncuesta = new Encuesta__c();
        objEncuesta.TituloEncuesta__c = 'Title test';
        objEncuesta.TypeformId__c = 'mytypeformid';
        objEncuesta.Description__c = 'My Survey description'; 
        objEncuesta.Slug__c = 'test';
        objEncuesta.Default_Survey__c = true;
        objEncuesta.TypeformResultsId__c = 'test'; 
            
        insert objEncuesta;
    }
    
    private static Territorio_Administrativo__c createTerritory(Integer intLevel, String strName, String strParentId) {
        Territorio_Administrativo__c objTerritory = null;
        
        objTerritory = new Territorio_Administrativo__c();
        objTerritory.Nivel_Administrativo__c = intLevel;
        objTerritory.Name = strName;
        objTerritory.Location_UUID__c = strName; 
        if(String.isNotBlank(strParentId)) {
            objTerritory.ParentId__c = strParentId;
        }
        
        insert objTerritory;
        
        return objTerritory;
    }
}