force-app/main/default/objects/Encuesta__c/Encuesta__c.object-meta.xml
<CustomObject>
    <label>Encuesta</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Encuesta Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Encuestas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Encuesta__c/fields/Default_Survey__c.field-meta.xml
<CustomField>
    <fullName>Default_Survey__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default Survey</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Encuesta__c/fields/Number_Of_Answered_Questions__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Answered_Questions__c</fullName>
    <label>Number_Of_Answered_Questions</label>
    <summarizedField>User_Survey__c.Number_Of_Answered_Questions__c</summarizedField>
    <summaryForeignKey>User_Survey__c.Survey__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Encuesta__c/fields/Number_Of_Answering_Users__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Answering_Users__c</fullName>
    <label>Number_Of_Answering_Users</label>
    <summaryForeignKey>User_Survey__c.Survey__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Encuesta__c/fields/Number_Of_Questions__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Questions__c</fullName>
    <label>Number Of Questions</label>
    <summaryForeignKey>Survey_Question__c.Survey__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Encuesta__c/fields/TituloEncuesta__c.field-meta.xml
<CustomField>
    <fullName>TituloEncuesta__c</fullName>
    <label>TituloEncuesta</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Encuesta__c/fields/TypeformId__c.field-meta.xml
<CustomField>
    <fullName>TypeformId__c</fullName>
    <externalId>true</externalId>
    <label>TypeformId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Encuesta__c/fields/TypeformResultsId__c.field-meta.xml
<CustomField>
    <fullName>TypeformResultsId__c</fullName>
    <externalId>true</externalId>
    <label>TypeformResultsId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Pulso_Survey_ControllerTest.cls
@IsTest
public class Pulso_Survey_ControllerTest {	
    @testSetup
    private static void initializeTest() {
        createSurvey();
        createLead();
    }
    
    @IsTest
    private static void surveyPageTest() {
        Pulso_Survey_Controller objPulsoSurvey = null;
        Encuesta__c objSurvey = null;
        Lead objLead = null;
        
        objSurvey = [SELECT Id, Name, TituloEncuesta__c, Number_Of_Answered_Questions__c,Number_Of_Answering_Users__c,Number_Of_Questions__c
                       FROM Encuesta__c];
        objLead = [SELECT Id, FirstName, LastName, MobilePhone, Email 
                   FROM Lead];
        
        ApexPages.currentPage().getParameters().put('leadid', objLead.Id);
        ApexPages.currentPage().getParameters().put('survey', objSurvey.Id);

        objPulsoSurvey = new Pulso_Survey_Controller();
        
        //System.assertEquals(objPulsoSurvey.survey.Id, objSurvey.Id);
		
    }
    
    private static void createSurvey() {
        Encuesta__c objEncuesta = null;
        
        objEncuesta = new Encuesta__c();
        objEncuesta.TituloEncuesta__c = 'Title test';
        objEncuesta.TypeformId__c = 'mytypeformid';
        objEncuesta.Description__c = 'My Survey description'; 
        objEncuesta.Slug__c = 'test';
        objEncuesta.Default_Survey__c = true;
        objEncuesta.TypeformResultsId__c = 'test';
        
        insert objEncuesta;
    }       
    
    private static void createLead() {
        Lead objLead = null;
        
        objLead = new Lead();
        objLead.FirstName = 'Juan';
        objLead.LastName = 'Perez';
        objLead.Company = 'SurveyCRM';
        objLead.Email = 'juanperez@salesforce.com';
        objLead.MobilePhone = '11122233';
        
        insert objLead; 
    }
}