force-app/main/default/objects/Encuesta__c/Encuesta__c.object-meta.xml
<CustomObject>
    <label>Encuesta</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Encuesta Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Encuestas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Encuesta__c/fields/TituloEncuesta__c.field-meta.xml
<CustomField>
    <fullName>TituloEncuesta__c</fullName>
    <label>TituloEncuesta</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Encuesta__c/fields/TypeformId__c.field-meta.xml
<CustomField>
    <fullName>TypeformId__c</fullName>
    <externalId>true</externalId>
    <label>TypeformId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Encuesta__c/fields/TypeformResultsId__c.field-meta.xml
<CustomField>
    <fullName>TypeformResultsId__c</fullName>
    <externalId>true</externalId>
    <label>TypeformResultsId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Setting__mdt/Survey_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Survey Setting</label>
    <pluralLabel>Survey_Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Survey_Setting__mdt/fields/UrlRewriterPath__c.field-meta.xml
<CustomField>
    <fullName>UrlRewriterPath__c</fullName>
    <label>UrlRewriterPath</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Setting__mdt/fields/UrlRewriterVF__c.field-meta.xml
<CustomField>
    <fullName>UrlRewriterVF__c</fullName>
    <label>UrlRewriterVF</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/PulsoUrlRewriterTest.cls
@IsTest
private class PulsoUrlRewriterTest {
    @testSetup
    private static void initializeTest() { 
    	Encuesta__c objEncuesta = null;
        
        objEncuesta = new Encuesta__c();
        objEncuesta.Slug__c = 'test';
        objEncuesta.TituloEncuesta__c = 'test'; 
        objEncuesta.TypeformId__c = 'test'; 
        objEncuesta.Description__c = 'test';
        objEncuesta.TypeformResultsId__c = 'test';
        
        insert objEncuesta;
    }
    
    @IsTest
    private static void urlRewriterTest() {
        PageReference objFriendlyPageReference = null;
        PageReference objUglyPageReference = null;
        PulsoUrlRewriter objPulsoUrlRewriter = null;
        Survey_Setting__mdt objSurveySettings = null;
        String strUglyUrl = null;
        List<Encuesta__c> lstSurveys = null;
        List<PageReference> lstPageReferences = null;

        objSurveySettings = HelperFunctions.retrieveSurveySettings('Pulso_CRM');
        lstSurveys = [SELECT TypeformId__c, Slug__c FROM Encuesta__c LIMIT 1]; 

        objFriendlyPageReference = new PageReference(objSurveySettings.UrlRewriterPath__c + lstSurveys[0].Slug__c);
        objPulsoUrlRewriter = new PulsoUrlRewriter();        
        objUglyPageReference = objPulsoUrlRewriter.mapRequestUrl(objFriendlyPageReference);
        
        System.assertEquals(objSurveySettings.UrlRewriterVF__c + lstSurveys[0].TypeformId__c , objUglyPageReference.getUrl());        
        
        lstPageReferences = new  List<PageReference> ();
        lstPageReferences.add(new PageReference(objSurveySettings.UrlRewriterVF__c + lstSurveys[0].TypeformId__c));
        objFriendlyPageReference = objPulsoUrlRewriter.generateUrlFor(lstPageReferences)[0];
        
        System.assertEquals(objSurveySettings.UrlRewriterPath__c + lstSurveys[0].Slug__c , objFriendlyPageReference.getUrl());                
    }
    
    /*
    @IsTest
    private static void urlRewriterTest() {
        PageReference objFriendlyPageReference = null;
        PageReference objUglyPageReference = null;
        PulsoUrlRewriter objPulsoUrlRewriter = null;
        List<PageReference> lstPageReferences = null;
        List<Encuesta__c> lstSurveys = null;
        Survey_Setting__mdt objSurveySettings = null;
        
        objSurveySettings = HelperFunctions.retrieveSurveySettings('Pulso_CRM');
        
        lstPageReferences = new  List<PageReference> ();
        lstSurveys = [SELECT ID FROM Encuesta__c LIMIT 1];
        lstPageReferences.add(new PageReference(objSurveySettings.UrlRewriterVF__c + '?surveyid=' + lstSurveys[0].Id));
        
        objFriendlyPageReference = new PageReference(objSurveySettings.UrlRewriterPath__c + '/test/');
        objPulsoUrlRewriter = new PulsoUrlRewriter();        
        objUglyPageReference = objPulsoUrlRewriter.mapRequestUrl(objFriendlyPageReference);
        
        System.assert(condition)
        objPulsoUrlRewriter.generateUrlFor(lstPageReferences);
    }*/
}