force-app/main/default/objects/Encuesta__c/Encuesta__c.object-meta.xml
<CustomObject>
    <label>Encuesta</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Encuesta Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Encuestas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Encuesta__c/fields/TypeformId__c.field-meta.xml
<CustomField>
    <fullName>TypeformId__c</fullName>
    <externalId>true</externalId>
    <label>TypeformId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateTypeFormResponses_Schedulable.cls
global class UpdateTypeFormResponses_Schedulable  implements Schedulable {
    global void execute(SchedulableContext objSchedulableContext) { 
    	List<Encuesta__c> lstSurvey = null;
        String strToken = null;
        String strLastHour = null;
        String strNowHour = null;
        
        lstSurvey = [SELECT Id, TypeformId__c 
                     FROM Encuesta__c
                     LIMIT 1000];
        
        if(!lstSurvey.IsEmpty()) {
            strToken = TypeformAPI.retrieveToken();
            strLastHour = DateTime.now().addHours(-1).formatGMT('yyyy-MM-dd\'T\'HH:mm:ss');
            strNowHour = DateTime.now().formatGMT('yyyy-MM-dd\'T\'HH:mm:ss');
            if(String.isNotBlank(strToken)) {
                for(Encuesta__c objSurvey : lstSurvey) {
                    TypeformAPI.retrieveTypeformSurvey(objSurvey.TypeformId__c);
                    TypeformAPI.retrieveTypeformAnswers(strToken, objSurvey.TypeformId__c,strLastHour, strNowHour);
                }
            }
        }
    }
}