force-app/main/default/objects/Territorio_Administrativo__c/Territorio_Administrativo__c.object-meta.xml
<CustomObject>
    <description>Objeto Custom para carga de Territorios de multiples paises, estructurado en 5 niveles</description>
    <label>Territorio</label>
    <nameField>
        <label>Territorio Administrativo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territorios</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Territorio_Administrativo__c/fields/RiverId_Etario_Baby_Boomers_Female__c.field-meta.xml
<CustomField>
    <fullName>RiverId_Etario_Baby_Boomers_Female__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RiverId_Etario_Baby_Boomers_Female</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/RiverId_Etario_Baby_Boomers_Male__c.field-meta.xml
<CustomField>
    <fullName>RiverId_Etario_Baby_Boomers_Male__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RiverId_Etario_Baby_Boomers_Male</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/RiverId_Etario_Centennials_Female__c.field-meta.xml
<CustomField>
    <fullName>RiverId_Etario_Centennials_Female__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RiverId_Etario_Centennials_Female</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/RiverId_Etario_Centennials_Male__c.field-meta.xml
<CustomField>
    <fullName>RiverId_Etario_Centennials_Male__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RiverId_Etario_Centennials_Male</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/RiverId_Etario_Generacion_Silenciosa_F__c.field-meta.xml
<CustomField>
    <fullName>RiverId_Etario_Generacion_Silenciosa_F__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RiverId_Etario_Generacion_Silenciosa_F</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/RiverId_Etario_Generacion_Silenciosa_M__c.field-meta.xml
<CustomField>
    <fullName>RiverId_Etario_Generacion_Silenciosa_M__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RiverId_Etario_Generacion_Silenciosa_M</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/RiverId_Etario_Generacion_X_Female__c.field-meta.xml
<CustomField>
    <fullName>RiverId_Etario_Generacion_X_Female__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RiverId_Etario_Generacion_X_Female</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/RiverId_Etario_Generacion_X_Male__c.field-meta.xml
<CustomField>
    <fullName>RiverId_Etario_Generacion_X_Male__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RiverId_Etario_Generacion_X_Male</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/RiverId_Etario_Millennials_Female__c.field-meta.xml
<CustomField>
    <fullName>RiverId_Etario_Millennials_Female__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RiverId_Etario_Millennials_Female</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/RiverId_Etario_Millennials_Male__c.field-meta.xml
<CustomField>
    <fullName>RiverId_Etario_Millennials_Male__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RiverId_Etario_Millennials_Male</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/RiverId_Etario_Sub_16_Female__c.field-meta.xml
<CustomField>
    <fullName>RiverId_Etario_Sub_16_Female__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RiverId_Etario_Sub_16_Female</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/RiverId_Etario_Sub_16_Male__c.field-meta.xml
<CustomField>
    <fullName>RiverId_Etario_Sub_16_Male__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RiverId_Etario_Sub_16_Male</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/RiverId_Total_Ciudadanos__c.field-meta.xml
<CustomField>
    <fullName>RiverId_Total_Ciudadanos__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RiverId_Total_Ciudadanos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/RiverId_Total_Edu_Primary__c.field-meta.xml
<CustomField>
    <fullName>RiverId_Total_Edu_Primary__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RiverId_Total_Edu_Primary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/RiverId_Total_Edu_Secondary__c.field-meta.xml
<CustomField>
    <fullName>RiverId_Total_Edu_Secondary__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RiverId_Total_Edu_Secondary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/RiverId_Total_Edu_Tertiary__c.field-meta.xml
<CustomField>
    <fullName>RiverId_Total_Edu_Tertiary__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RiverId_Total_Edu_Tertiary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/RiverId_Total_Edu_University__c.field-meta.xml
<CustomField>
    <fullName>RiverId_Total_Edu_University__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RiverId_Total_Edu_University</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/RiverId_Total_Number_of_Females__c.field-meta.xml
<CustomField>
    <fullName>RiverId_Total_Number_of_Females__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RiverId_Total_Number_of_Females</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/RiverId_Total_Number_of_Males__c.field-meta.xml
<CustomField>
    <fullName>RiverId_Total_Number_of_Males__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RiverId_Total_Number_of_Males</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/RiverId_TotEco_Activities__c.field-meta.xml
<CustomField>
    <fullName>RiverId_TotEco_Activities__c</fullName>
    <defaultValue>(&quot;{}&quot;)</defaultValue>
    <description>Guarda un JSON de actividades agrupadas, pares string:decimal</description>
    <label>RiverId_TotEco_Activities</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/RiverId_TotInc_High__c.field-meta.xml
<CustomField>
    <fullName>RiverId_TotInc_High__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RiverId_TotInc_High</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/RiverId_TotInc_Low__c.field-meta.xml
<CustomField>
    <fullName>RiverId_TotInc_Low__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RiverId_TotInc_Low</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/RiverId_TotInc_Medium__c.field-meta.xml
<CustomField>
    <fullName>RiverId_TotInc_Medium__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RiverId_TotInc_Medium</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/RiverId_TotInc_Very_High__c.field-meta.xml
<CustomField>
    <fullName>RiverId_TotInc_Very_High__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RiverId_TotInc_Very_High</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/RiverId_TotInc_Very_Low__c.field-meta.xml
<CustomField>
    <fullName>RiverId_TotInc_Very_Low__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RiverId_TotInc_Very_Low</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/RiverId_TotOccu_Not_Declared__c.field-meta.xml
<CustomField>
    <fullName>RiverId_TotOccu_Not_Declared__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RiverId_TotOccu_Not_Declared</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/RiverId_TotOccu_Retired__c.field-meta.xml
<CustomField>
    <fullName>RiverId_TotOccu_Retired__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RiverId_TotOccu_Retired</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/RiverId_TotOccu_Self_Employed__c.field-meta.xml
<CustomField>
    <fullName>RiverId_TotOccu_Self_Employed__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RiverId_TotOccu_Self_Employed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/RiverId_TotOccu_Wage__c.field-meta.xml
<CustomField>
    <fullName>RiverId_TotOccu_Wage__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RiverId_TotOccu_Wage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TerritoryBatch_ClearFields.cls
global class TerritoryBatch_ClearFields implements Database.Batchable<sObject>,Database.Stateful {

    public Boolean doChain;

    global TerritoryBatch_ClearFields() {
        this.doChain = true;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){

        return Database.getQueryLocator([SELECT Id FROM Territorio_Administrativo__c]);

    }

    global void execute(Database.BatchableContext BC, List<Territorio_Administrativo__c> scope){
        List<Territorio_Administrativo__c> territoriosToUpdate = new List<Territorio_Administrativo__c>();
        for(Territorio_Administrativo__c thisTerritorio : scope){
            Territorio_Administrativo__c temTerritory = new Territorio_Administrativo__c();
            temTerritory.id = thisTerritorio.id;
            temTerritory.RiverId_Etario_Sub_16_Male__c = 0;
            temTerritory.RiverId_Etario_Centennials_Male__c = 0;
            temTerritory.RiverId_Etario_Millennials_Male__c = 0;
            temTerritory.RiverId_Etario_Generacion_X_Male__c = 0;
            temTerritory.RiverId_Etario_Baby_Boomers_Male__c = 0;
            temTerritory.RiverId_Etario_Generacion_Silenciosa_M__c = 0;

            temTerritory.RiverId_Etario_Sub_16_Female__c = 0;
            temTerritory.RiverId_Etario_Centennials_Female__c = 0;
            temTerritory.RiverId_Etario_Millennials_Female__c = 0;
            temTerritory.RiverId_Etario_Generacion_X_Female__c = 0;
            temTerritory.RiverId_Etario_Baby_Boomers_Female__c = 0;
            temTerritory.RiverId_Etario_Generacion_Silenciosa_F__c = 0;

            temTerritory.RiverId_Total_Ciudadanos__c = 0;
            temTerritory.RiverId_Total_Number_of_Males__c = 0;
            temTerritory.RiverId_Total_Number_of_Females__c = 0;
            
            temTerritory.RiverId_TotInc_Very_Low__c = 0;
            temTerritory.RiverId_TotInc_Low__c = 0;
            temTerritory.RiverId_TotInc_Medium__c = 0;
            temTerritory.RiverId_TotInc_High__c = 0;
            temTerritory.RiverId_TotInc_Very_High__c = 0;

            temTerritory.RiverId_TotOccu_Wage__c = 0;
            temTerritory.RiverId_TotOccu_Self_Employed__c = 0;
            temTerritory.RiverId_TotOccu_Retired__c = 0;
            temTerritory.RiverId_TotOccu_Not_Declared__c = 0;

            temTerritory.RiverId_Total_Edu_Primary__c = 0;
            temTerritory.RiverId_Total_Edu_Secondary__c = 0;
            temTerritory.RiverId_Total_Edu_Tertiary__c = 0;
            temTerritory.RiverId_Total_Edu_University__c = 0;

            temTerritory.RiverId_TotEco_Activities__c = '{}';

            territoriosToUpdate.add(temTerritory);
        }

        Update territoriosToUpdate;
    }

    global void finish(Database.BatchableContext BC) {
        //call batch que empieze a actualizar los territorios a los que los citizens pertenezcan. TerritoryBatch_AcumCitizens
        if(this.doChain) {
            TerritoryBatch_AcumCitizens batch = new TerritoryBatch_AcumCitizens();
            database.executeBatch(batch, 2000);
        }
    }


}