force-app/main/default/objects/Territorio_Administrativo__c/Territorio_Administrativo__c.object-meta.xml
<CustomObject>
    <description>Objeto Custom para carga de Territorios de multiples paises, estructurado en 5 niveles</description>
    <label>Territorio</label>
    <nameField>
        <label>Territorio Administrativo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territorios</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Nivel_Administrativo__c.field-meta.xml
<CustomField>
    <fullName>Nivel_Administrativo__c</fullName>
    <label>Nivel Administrativo</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ParentId</label>
    <referenceTo>Territorio_Administrativo__c</referenceTo>
    <relationshipLabel>Territories</relationshipLabel>
    <relationshipName>ChildTerritories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Pulso_Contact_Modal_Controller.cls
public class Pulso_Contact_Modal_Controller {
    @RemoteAction
    public static List<RemotingMessageHelper.Territory> retrieveTerritories(Integer intLevel, String strParentId) {
        List<RemotingMessageHelper.Territory> lstTerritories = null;
        List<Territorio_Administrativo__c> lstTerritoriesC = null;
         
        System.debug('retrieveTerritories [intLevel : ' + intLevel + ' - strParentId : ' + strParentId + '] ->');

        if(String.isNotBlank(strParentId)) {
            lstTerritoriesC = [SELECT Id, Name, Nivel_Administrativo__c 
                              FROM Territorio_Administrativo__c 
                              WHERE Nivel_Administrativo__c =: intLevel 
                              AND ParentId__c =: strParentId];
        } else {
            lstTerritoriesC = [SELECT Id, Name, Nivel_Administrativo__c 
                              FROM Territorio_Administrativo__c 
                              WHERE Nivel_Administrativo__c =: intLevel];
        }
        
        lstTerritories = new List<RemotingMessageHelper.Territory>();
        for(Territorio_Administrativo__c objTerritoryC : lstTerritoriesC) {
            lstTerritories.add(new RemotingMessageHelper.Territory(objTerritoryC));
        }
        
        System.debug('retrieveTerritories [' + lstTerritories + '] <-');

        return lstTerritories;
    }
    
    @RemoteAction
    public static void saveContact(String strJSON) {
        RemotingMessageHelper.PulsoContact objPulsoContact = null;
        Lead objLead = null;
        
        try {
            if(String.isNotBlank(strJSON)) {
                objPulsoContact = (RemotingMessageHelper.PulsoContact)JSON.deserialize(strJSON, RemotingMessageHelper.PulsoContact.class);
                objLead = objPulsoContact.toLead();
                
                upsert objLead Email;
            }            
        } catch(Exception Ex) {
            HelperFunctions.handleRuntimeException(Ex);
        }
    }
}