force-app/main/default/objects/Territorio_Administrativo__c/Territorio_Administrativo__c.object-meta.xml
<CustomObject>
    <description>Objeto Custom para carga de Territorios de multiples paises, estructurado en 5 niveles</description>
    <label>Territorio</label>
    <nameField>
        <label>Territorio Administrativo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territorios</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Etario_Baby_Boomers_Female__c.field-meta.xml
<CustomField>
    <fullName>Etario_Baby_Boomers_Female__c</fullName>
    <label>Etario_Baby_Boomers_Female</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Etario_Baby_Boomers_Male__c.field-meta.xml
<CustomField>
    <fullName>Etario_Baby_Boomers_Male__c</fullName>
    <label>Etario_Baby_Boomers_Male</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Etario_Baby_Boomers_Total__c.field-meta.xml
<CustomField>
    <fullName>Etario_Baby_Boomers_Total__c</fullName>
    <label>Etario_Baby_Boomers_Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Etario_Centennials_Female__c.field-meta.xml
<CustomField>
    <fullName>Etario_Centennials_Female__c</fullName>
    <label>Etario_Centennials_Female</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Etario_Centennials_Male__c.field-meta.xml
<CustomField>
    <fullName>Etario_Centennials_Male__c</fullName>
    <label>Etario_Centennials_Male</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Etario_Centennials_Total__c.field-meta.xml
<CustomField>
    <fullName>Etario_Centennials_Total__c</fullName>
    <label>Etario_Centennials_Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Etario_Generacion_Silenciosa_Female__c.field-meta.xml
<CustomField>
    <fullName>Etario_Generacion_Silenciosa_Female__c</fullName>
    <label>Etario_Generacion_Silenciosa_Female</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Etario_Generacion_Silenciosa_Male__c.field-meta.xml
<CustomField>
    <fullName>Etario_Generacion_Silenciosa_Male__c</fullName>
    <label>Etario_Generacion_Silenciosa_Male</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Etario_Generacion_Silenciosa_Total__c.field-meta.xml
<CustomField>
    <fullName>Etario_Generacion_Silenciosa_Total__c</fullName>
    <label>Etario_Generacion_Silenciosa-Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Etario_Generacion_X_Female__c.field-meta.xml
<CustomField>
    <fullName>Etario_Generacion_X_Female__c</fullName>
    <label>Etario_Generacion_X_Female</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Etario_Generacion_X_Male__c.field-meta.xml
<CustomField>
    <fullName>Etario_Generacion_X_Male__c</fullName>
    <label>Etario_Generacion_X_Male</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Etario_Generacion_X_Total__c.field-meta.xml
<CustomField>
    <fullName>Etario_Generacion_X_Total__c</fullName>
    <label>Etario_Generacion_X_Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Etario_Millennials_Female__c.field-meta.xml
<CustomField>
    <fullName>Etario_Millennials_Female__c</fullName>
    <label>Etario_Millennials_Female</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Etario_Millennials_Male__c.field-meta.xml
<CustomField>
    <fullName>Etario_Millennials_Male__c</fullName>
    <label>Etario_Millennials_Male</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Etario_Millennials_Total__c.field-meta.xml
<CustomField>
    <fullName>Etario_Millennials_Total__c</fullName>
    <label>Etario_Millennials_Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Etario_Sub_16_Female__c.field-meta.xml
<CustomField>
    <fullName>Etario_Sub_16_Female__c</fullName>
    <label>Etario_Sub_16_Female</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Etario_Sub_16_Male__c.field-meta.xml
<CustomField>
    <fullName>Etario_Sub_16_Male__c</fullName>
    <label>Etario_Sub_16_Male</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Etario_Sub_16_Total__c.field-meta.xml
<CustomField>
    <fullName>Etario_Sub_16_Total__c</fullName>
    <label>Etario_Sub_16_Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Nivel_Administrativo__c.field-meta.xml
<CustomField>
    <fullName>Nivel_Administrativo__c</fullName>
    <label>Nivel Administrativo</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ParentId</label>
    <referenceTo>Territorio_Administrativo__c</referenceTo>
    <relationshipLabel>Territories</relationshipLabel>
    <relationshipName>ChildTerritories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Total_Ciudadanos__c.field-meta.xml
<CustomField>
    <fullName>Total_Ciudadanos__c</fullName>
    <label>People</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Total_de_Hombres_de_0_a_15__c.field-meta.xml
<CustomField>
    <fullName>Total_de_Hombres_de_0_a_15__c</fullName>
    <label>Total de Hombres de 0 a 15</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Total_de_Hombres_de_16_a_17__c.field-meta.xml
<CustomField>
    <fullName>Total_de_Hombres_de_16_a_17__c</fullName>
    <label>Total de Hombres de 16 a 17</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Total_de_Hombres_de_18_a_24__c.field-meta.xml
<CustomField>
    <fullName>Total_de_Hombres_de_18_a_24__c</fullName>
    <label>Total de Hombres de 18 a 24</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Total_de_Hombres_de_25_a_39__c.field-meta.xml
<CustomField>
    <fullName>Total_de_Hombres_de_25_a_39__c</fullName>
    <label>Total de Hombres de 25 a 39</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Total_de_Hombres_de_40_a_64__c.field-meta.xml
<CustomField>
    <fullName>Total_de_Hombres_de_40_a_64__c</fullName>
    <label>Total de Hombres de 40 a 64</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Total_Emails__c.field-meta.xml
<CustomField>
    <fullName>Total_Emails__c</fullName>
    <label>Emails</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Total_Facebook__c.field-meta.xml
<CustomField>
    <fullName>Total_Facebook__c</fullName>
    <label>Facebook</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Total_Hombres_de_65plus__c.field-meta.xml
<CustomField>
    <fullName>Total_Hombres_de_65plus__c</fullName>
    <label>Total Hombres de +65</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Total_Instagram__c.field-meta.xml
<CustomField>
    <fullName>Total_Instagram__c</fullName>
    <label>Instagram</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Total_Linkedin__c.field-meta.xml
<CustomField>
    <fullName>Total_Linkedin__c</fullName>
    <label>Linkedin</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Total_Moviles__c.field-meta.xml
<CustomField>
    <fullName>Total_Moviles__c</fullName>
    <label>Mobiles</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Total_Mujeres_de_0_a_15__c.field-meta.xml
<CustomField>
    <fullName>Total_Mujeres_de_0_a_15__c</fullName>
    <label>Total Mujeres de 0 a 15</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Total_Mujeres_de_16_a_17__c.field-meta.xml
<CustomField>
    <fullName>Total_Mujeres_de_16_a_17__c</fullName>
    <label>Total Mujeres de 16 a 17</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Total_Mujeres_de_18_a_24__c.field-meta.xml
<CustomField>
    <fullName>Total_Mujeres_de_18_a_24__c</fullName>
    <label>Total Mujeres de 18 a 24</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Total_Mujeres_de_25_a_39__c.field-meta.xml
<CustomField>
    <fullName>Total_Mujeres_de_25_a_39__c</fullName>
    <label>Total Mujeres de 25 a 39</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Total_Mujeres_de_40_a_64__c.field-meta.xml
<CustomField>
    <fullName>Total_Mujeres_de_40_a_64__c</fullName>
    <label>Total Mujeres de 40 a 64</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Total_Mujeres_de_65Plus__c.field-meta.xml
<CustomField>
    <fullName>Total_Mujeres_de_65Plus__c</fullName>
    <label>Total Mujeres de +65</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Total_Number_of_00_15_year_olds__c.field-meta.xml
<CustomField>
    <fullName>Total_Number_of_00_15_year_olds__c</fullName>
    <description>Campo de número agregado de Ciudadanos de 0 a 15 Años</description>
    <label>Número de Ciudadanos  entre 0 y 15 Años</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Total_Number_of_16_17_year_olds__c.field-meta.xml
<CustomField>
    <fullName>Total_Number_of_16_17_year_olds__c</fullName>
    <description>Campo Agregado de Ciudadanos de 16 y 17 años</description>
    <label>Número de Ciudadanos  entre 16 y 17 Años</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Total_Number_of_18_24_year_olds__c.field-meta.xml
<CustomField>
    <fullName>Total_Number_of_18_24_year_olds__c</fullName>
    <description>CAmpo Agregadop de ciudadanos de 18 a 24 años</description>
    <label>Número de Ciudadanos entre 18 y 24 años</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Total_Number_of_25_39_year_olds__c.field-meta.xml
<CustomField>
    <fullName>Total_Number_of_25_39_year_olds__c</fullName>
    <description>Total de Ciudadanos de entre 25 y 39 años x Territorio</description>
    <inlineHelpText>Total de Ciudadanos de entre 25 y 39 años x Territorio</inlineHelpText>
    <label>Número de CIudadanos entre 25 y 39 años</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Total_Number_of_40_64_year_olds__c.field-meta.xml
<CustomField>
    <fullName>Total_Number_of_40_64_year_olds__c</fullName>
    <description>Campo Agregado de Ciudadanos de 40 a 64 Años</description>
    <inlineHelpText>Numero de CIudadanos de entre 40 y 64 años x Territorio</inlineHelpText>
    <label>Número de Ciudadanos entre 40 y 64 años</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Total_Number_of_65_year_olds__c.field-meta.xml
<CustomField>
    <fullName>Total_Number_of_65_year_olds__c</fullName>
    <description>Campo Agregado de Ciudadanos de mas de 65 Años</description>
    <inlineHelpText>CIudadanos de Mas de 65 Años x Territorio</inlineHelpText>
    <label>Número de Ciudadanos de más de 65 Años</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Total_Telefonos_FIjos__c.field-meta.xml
<CustomField>
    <fullName>Total_Telefonos_FIjos__c</fullName>
    <label>Landlines</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Total_Twitter__c.field-meta.xml
<CustomField>
    <fullName>Total_Twitter__c</fullName>
    <label>Twitter</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SchdUpdateTerritories.cls
global with sharing class SchdUpdateTerritories implements Schedulable{

    private String levelOName;

    global SchdUpdateTerritories(String levelOName){
        this.levelOName = levelOName;
    }

    global void execute(SchedulableContext ctx) {
    	runUpdate(2, levelOName);
    }

    global static void start(String levelOName){
        start('20', 'SUN', levelOName);
    }

    global static void start(String hour, String day, String levelOName){
        System.schedule('Update Territories', '0 0 ' + hour + ' ? * ' + day, new SchdUpdateTerritories(levelOName));
    }

    global static void runUpdate(Integer adminLevel, String levelOName){

        resetParentsTerritories(adminLevel-1, levelOName);
        
        List<Territorio_Administrativo__c> territories = new List<Territorio_Administrativo__c>();

        for(Territorio_Administrativo__c territory : [SELECT Id, Name, Nivel_Administrativo__c, ParentId__c, Total_Emails__c, Total_Ciudadanos__c, Total_Facebook__c, Total_Instagram__c, Total_Telefonos_FIjos__c, Total_Linkedin__c,
                                                            Total_Moviles__c, Total_Twitter__c, Etario_Generacion_Silenciosa_Male__c, Etario_Generacion_Silenciosa_Female__c, Etario_Generacion_Silenciosa_Total__c,
                                                            Etario_Baby_Boomers_Male__c, Etario_Baby_Boomers_Female__c, Etario_Baby_Boomers_Total__c, Etario_Generacion_X_Male__c, Etario_Generacion_X_Female__c,
                                                            Etario_Generacion_X_Total__c, Etario_Millennials_Male__c, Etario_Millennials_Female__c, Etario_Millennials_Total__c, Etario_Centennials_Male__c,
                                                            Etario_Centennials_Female__c, Etario_Centennials_Total__c, Etario_Sub_16_Male__c, Etario_Sub_16_Female__c, Etario_Sub_16_Total__c,
                                                            Total_de_Hombres_de_0_a_15__c, Total_Mujeres_de_0_a_15__c, Total_Number_of_00_15_year_olds__c, Total_de_Hombres_de_16_a_17__c,
                                                            Total_Mujeres_de_16_a_17__c, Total_Number_of_16_17_year_olds__c, Total_de_Hombres_de_18_a_24__c, Total_Mujeres_de_18_a_24__c, Total_Number_of_18_24_year_olds__c,
                                                            Total_de_Hombres_de_25_a_39__c, Total_Mujeres_de_25_a_39__c, Total_Number_of_25_39_year_olds__c, Total_de_Hombres_de_40_a_64__c,
                                                            Total_Mujeres_de_40_a_64__c, Total_Number_of_40_64_year_olds__c, Total_Hombres_de_65plus__c, Total_Mujeres_de_65plus__c,
                                                            Total_Number_of_65_year_olds__c, Total_Number_of_Males__c, Total_Number_of_Females__c, Total_Income_Range_Very_Low__c,
                                                            Total_Income_Range_Low__c, Total_Income_Range_Medium__c, Total_Income_Range_High__c, Total_Income_Range_Very_High__c, Total_Education_Level_University_Degree__c,
                                                            Total_Education_Level_Primary__c, Total_Education_Level_Secondary__c, Total_Education_Level_Tertiary__c, Total_Occupation_Type_Not_Declared__c,
                                                            Total_Occupation_Type_Retired__c, Total_Occupation_Type_Self_Employed__c, Total_Occupation_Type_Wage_Earned__c,
                                                            Total_Economic_Activities__c 
                                    FROM Territorio_Administrativo__c WHERE Nivel_Administrativo__c = :adminLevel AND Level0Name__c = :levelOName]){
            
            territories.add(territory);

            if(territories.size() == 10){
                BatchUpdateTerritories batch = new BatchUpdateTerritories(territories, adminLevel, levelOName, true);
    	        database.executeBatch(batch, 2000);
                territories.clear();
            }
        }

        if(!territories.isEmpty()){
            BatchUpdateTerritories batch = new BatchUpdateTerritories(territories, adminLevel, levelOName, true);
            database.executeBatch(batch, 2000);
        }
        
    }
    
    private static void resetParentsTerritories(Integer adminLevel, String levelOName){

        List<Territorio_Administrativo__c> territories = [SELECT Id, Name, Nivel_Administrativo__c, ParentId__c, Total_Emails__c, Total_Ciudadanos__c, Total_Facebook__c, Total_Instagram__c, Total_Telefonos_FIjos__c, Total_Linkedin__c,
                                                                    Total_Moviles__c, Total_Twitter__c, Etario_Generacion_Silenciosa_Male__c, Etario_Generacion_Silenciosa_Female__c, Etario_Generacion_Silenciosa_Total__c,
                                                                    Etario_Baby_Boomers_Male__c, Etario_Baby_Boomers_Female__c, Etario_Baby_Boomers_Total__c, Etario_Generacion_X_Male__c, Etario_Generacion_X_Female__c,
                                                                    Etario_Generacion_X_Total__c, Etario_Millennials_Male__c, Etario_Millennials_Female__c, Etario_Millennials_Total__c, Etario_Centennials_Male__c,
                                                                    Etario_Centennials_Female__c, Etario_Centennials_Total__c, Etario_Sub_16_Male__c, Etario_Sub_16_Female__c, Etario_Sub_16_Total__c,
                                                                    Total_de_Hombres_de_0_a_15__c, Total_Mujeres_de_0_a_15__c, Total_Number_of_00_15_year_olds__c, Total_de_Hombres_de_16_a_17__c,
                                                                    Total_Mujeres_de_16_a_17__c, Total_Number_of_16_17_year_olds__c, Total_de_Hombres_de_18_a_24__c, Total_Mujeres_de_18_a_24__c, Total_Number_of_18_24_year_olds__c,
                                                                    Total_de_Hombres_de_25_a_39__c, Total_Mujeres_de_25_a_39__c, Total_Number_of_25_39_year_olds__c, Total_de_Hombres_de_40_a_64__c,
                                                                    Total_Mujeres_de_40_a_64__c, Total_Number_of_40_64_year_olds__c, Total_Hombres_de_65plus__c, Total_Mujeres_de_65plus__c,
                                                                    Total_Number_of_65_year_olds__c, Total_Number_of_Males__c, Total_Number_of_Females__c, Total_Income_Range_Very_Low__c,
                                                                    Total_Income_Range_Low__c, Total_Income_Range_Medium__c, Total_Income_Range_High__c, Total_Income_Range_Very_High__c, Total_Education_Level_University_Degree__c,
                                                                    Total_Education_Level_Primary__c, Total_Education_Level_Secondary__c, Total_Education_Level_Tertiary__c, Total_Occupation_Type_Not_Declared__c,
                                                                    Total_Occupation_Type_Retired__c, Total_Occupation_Type_Self_Employed__c, Total_Occupation_Type_Wage_Earned__c,
                                                                    Total_Economic_Activities__c 
                                                                FROM Territorio_Administrativo__c WHERE Nivel_Administrativo__c <= :adminLevel AND Level0Name__c = :levelOName];

                                                        


        for(Territorio_Administrativo__c territory : territories){
            resetTerritory(territory);
        }

        update territories;

        BatchUpdateTerritories batch = new BatchUpdateTerritories(territories, adminLevel, levelOName);
        database.executeBatch(batch, 2000);

    }

    private static void resetTerritory(Territorio_Administrativo__c territory){
        territory.Total_Emails__c = 0;
        territory.Etario_Baby_Boomers_Female__c = 0;
        territory.Etario_Baby_Boomers_Male__c = 0;
        territory.Etario_Baby_Boomers_Total__c = 0;
        territory.Etario_Centennials_Female__c = 0;
        territory.Etario_Centennials_Male__c = 0;
        territory.Etario_Centennials_Total__c = 0;
        territory.Etario_Generacion_Silenciosa_Total__c = 0;
        territory.Etario_Generacion_Silenciosa_Female__c = 0;
        territory.Etario_Generacion_Silenciosa_Male__c = 0;
        territory.Etario_Generacion_X_Female__c = 0;
        territory.Etario_Generacion_X_Male__c = 0;
        territory.Etario_Generacion_X_Total__c = 0;
        territory.Etario_Millennials_Female__c = 0;
        territory.Etario_Millennials_Male__c = 0;
        territory.Etario_Millennials_Total__c = 0;
        territory.Etario_Sub_16_Female__c = 0;
        territory.Etario_Sub_16_Male__c = 0;
        territory.Etario_Sub_16_Total__c = 0;
        territory.Total_Facebook__c = 0;
        territory.Total_Instagram__c = 0;
        territory.Total_Telefonos_FIjos__c = 0;
        territory.Total_Linkedin__c = 0;
        territory.Total_Moviles__c = 0;
        territory.Total_Number_of_00_15_year_olds__c = 0;
        territory.Total_Number_of_16_17_year_olds__c = 0;
        territory.Total_Number_of_65_year_olds__c = 0;
        territory.Total_Number_of_18_24_year_olds__c = 0;
        territory.Total_Number_of_25_39_year_olds__c = 0;
        territory.Total_Number_of_40_64_year_olds__c = 0;
        territory.Total_Number_of_Males__c = 0;
        territory.Total_Number_of_Females__c= 0;
        territory.Total_Ciudadanos__c = 0;
        territory.Total_Education_Level_University_Degree__c = 0;
        territory.Total_de_Hombres_de_0_a_15__c = 0;
        territory.Total_de_Hombres_de_16_a_17__c = 0;
        territory.Total_de_Hombres_de_18_a_24__c = 0;
        territory.Total_de_Hombres_de_25_a_39__c = 0;
        territory.Total_de_Hombres_de_40_a_64__c = 0;
        territory.Total_Education_Level_Primary__c = 0;
        territory.Total_Education_Level_Secondary__c = 0;
        territory.Total_Education_Level_Tertiary__c = 0;
        territory.Total_Hombres_de_65plus__c = 0;
        territory.Total_Income_Range_High__c = 0;
        territory.Total_Income_Range_Low__c = 0;
        territory.Total_Income_Range_Medium__c = 0;
        territory.Total_Income_Range_Very_High__c = 0;
        territory.Total_Income_Range_Very_Low__c = 0;
        territory.Total_Mujeres_de_65Plus__c = 0;
        territory.Total_Mujeres_de_0_a_15__c = 0;
        territory.Total_Mujeres_de_16_a_17__c = 0;
        territory.Total_Mujeres_de_18_a_24__c = 0;
        territory.Total_Mujeres_de_25_a_39__c = 0;
        territory.Total_Mujeres_de_40_a_64__c = 0;
        territory.Total_Occupation_Type_Not_Declared__c = 0;
        territory.Total_Occupation_Type_Retired__c = 0;
        territory.Total_Occupation_Type_Self_Employed__c = 0;
        territory.Total_Occupation_Type_Wage_Earned__c = 0;
        territory.Total_Twitter__c = 0;

        territory.Total_Economic_Activities__c = '';

    }
}