force-app/main/default/objects/Territorio_Administrativo__c/Territorio_Administrativo__c.object-meta.xml
<CustomObject>
    <description>Objeto Custom para carga de Territorios de multiples paises, estructurado en 5 niveles</description>
    <label>Territorio</label>
    <nameField>
        <label>Territorio Administrativo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territorios</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Territorio_Administrativo__c/fields/DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>DeveloperName__c</fullName>
    <formula>SUBSTITUTE(
 SUBSTITUTE(
  SUBSTITUTE( 
   SUBSTITUTE( 
    SUBSTITUTE( 
     SUBSTITUTE(
      SUBSTITUTE(
       SUBSTITUTE(
        SUBSTITUTE(
         SUBSTITUTE( Name ,&apos;á&apos;,&apos;a&apos;),&apos;é&apos;,&apos;e&apos;),&apos;í&apos;,&apos;i&apos;),&apos;ó&apos;,&apos;o&apos;),&apos;ú&apos;,&apos;u&apos;),&apos;Á&apos;,&apos;A&apos;), &apos;É&apos;, &apos;E&apos;) ,&apos;Í&apos;,&apos;I&apos;) ,&apos;Ó&apos;,&apos;O&apos;),&apos;Ú&apos;,&apos;U&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DeveloperName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Flag__c.field-meta.xml
<CustomField>
    <fullName>Flag__c</fullName>
    <label>Flag</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/IsRole__c.field-meta.xml
<CustomField>
    <fullName>IsRole__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsRole</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Level0Name__c.field-meta.xml
<CustomField>
    <fullName>Level0Name__c</fullName>
    <formula>IF(Nivel_Administrativo__c == 0, Name, ( 
IF(Nivel_Administrativo__c == 1 ,ParentId__r.Name, 
IF(Nivel_Administrativo__c == 2, ParentId__r.ParentId__r.Name, 
IF(Nivel_Administrativo__c == 3, ParentId__r.ParentId__r.ParentId__r.Name,
IF(Nivel_Administrativo__c == 4, ParentId__r.ParentId__r.ParentId__r.ParentId__r.Name,NULL)	
) 
) 
) 
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Level0Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Level1Name__c.field-meta.xml
<CustomField>
    <fullName>Level1Name__c</fullName>
    <formula>IF(Nivel_Administrativo__c == 1, Name, (
IF(Nivel_Administrativo__c == 2 ,ParentId__r.Name,
IF(Nivel_Administrativo__c == 3, ParentId__r.ParentId__r.Name,
IF(Nivel_Administrativo__c == 4, ParentId__r.ParentId__r.ParentId__r.Name,NULL)	
) 
)
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Level1Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Level2Name__c.field-meta.xml
<CustomField>
    <fullName>Level2Name__c</fullName>
    <formula>IF(Nivel_Administrativo__c == 2, Name, (
IF(Nivel_Administrativo__c == 3 ,ParentId__r.Name,
IF(Nivel_Administrativo__c == 4, ParentId__r.ParentId__r.Name, NULL)	
) 
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Level2Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Level3Name__c.field-meta.xml
<CustomField>
    <fullName>Level3Name__c</fullName>
    <formula>IF(Nivel_Administrativo__c == 3, Name, (
IF(Nivel_Administrativo__c == 4 ,ParentId__r.Name, NULL)	
) 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Level3Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territorio_Administrativo__c/fields/Nivel_Administrativo__c.field-meta.xml
<CustomField>
    <fullName>Nivel_Administrativo__c</fullName>
    <label>Nivel Administrativo</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CountrySelectorController.cls
public without sharing class CountrySelectorController {
    @AuraEnabled
    public static List<RemotingMessageHelper.Territory> retrieveTerritories() {
    	User objUser = NULL;    
        List<Territorio_Administrativo__c> lstTerritoriesC = null;
        List<RemotingMessageHelper.Territory> lstTerritories = null;
        RemotingMessageHelper.Territory objTerritory = null;
        
        System.debug('retrieveTerritories [] ->');
        try {                    
            lstTerritories = new List<RemotingMessageHelper.Territory>();
            
            objUser = [SELECT UserRole.DeveloperName
                       FROM User 
                       WHERE Id =: UserInfo.getUserId()]; 
            
            
            lstTerritoriesC = [SELECT Id, Name, Flag__c, Nivel_Administrativo__c, DeveloperName__c
                               FROM Territorio_Administrativo__c
                               WHERE IsRole__c = TRUE
                               ORDER BY Level0Name__c, Level1Name__c, Level2Name__c, Level3Name__c, Nivel_Administrativo__c];
            
            for(Territorio_Administrativo__c objTerritoryC : lstTerritoriesC) {
                objTerritory = new RemotingMessageHelper.Territory(objTerritoryC, (objUser.UserRole.DeveloperName == objTerritoryC.DeveloperName__c));
                
                lstTerritories.add(objTerritory);
            }
            
            Reports.ReportManager.runReport('00O6A000005duRoUAI', true);
        } catch (Exception Ex) {
            System.debug('retrieveTerritories [Ex : ' + Ex + ']');
        }
        System.debug('retrieveTerritories [' + lstTerritories + '] <-');
        
        return lstTerritories;
    } 
    
	@AuraEnabled
    public static Boolean changeTerritory(String strTerritory) {
    	User objUser = NULL;    
        UserRole objUserRole = NULL;    
        Boolean boolResult = false;
        
        System.debug('changeTerritory [strTerritory : ' + strTerritory + '] ->');
                   
        objUserRole = [SELECT Id 
                       FROM UserRole 
                       WHERE DeveloperName =: strTerritory];
        
        objUser = [SELECT UserRoleId 
                   FROM User 
                   WHERE Id =: UserInfo.getUserId()];    
        
        
        objUser.UserRoleId = objUserRole.Id;            
        update objUser;
        
        boolResult = true;
        //Reports.ReportManager.runReport('00O0n000000K1QVEA0', true);
        
        System.debug('changeTerritory [] <-');
        
        return boolResult;
    } 
}