force-app/main/default/objects/rptobj__c/rptobj__c.object-meta.xml
<CustomObject>
    <label>rptobj</label>
    <nameField>
        <label>rptobj Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>rptobj</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/rptobj__c/fields/reporttrigger__c.field-meta.xml
<CustomField>
    <fullName>reporttrigger__c</fullName>
    <label>reporttrigger</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CSVStream_Test.cls
@IsTest
private class CSVStream_Test {
    static testMethod void testMethod1(){
        CSVStream cs = new CSVStream();
        cs.getCSVStream();
        
        rptobj__c r = new rptobj__c();
        r.Name = 'ThisReport';
        r.reporttrigger__c = 0;
        insert r;
        
        String sch = '0 0 23 * * ?'; 
        IncrementReport sh1 = new IncrementReport();
		system.schedule('Test Check', sch, sh1); 
    }

}