force-app/main/default/objects/RiverId__c/RiverId__c.object-meta.xml
<CustomObject>
    <label>RiverId</label>
    <nameField>
        <label>RiverId Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RiverIds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RiverId__c/fields/guid__c.field-meta.xml
<CustomField>
    <fullName>guid__c</fullName>
    <externalId>true</externalId>
    <label>Guid</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RiverId_Polls__c/RiverId_Polls__c.object-meta.xml
<CustomObject>
    <label>RiverId Poll</label>
    <nameField>
        <displayFormat>RiverIdPol-{0000000}</displayFormat>
        <label>RiverId Polls Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RiverId Polls</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RiverId_Polls__c/fields/guid__c.field-meta.xml
<CustomField>
    <fullName>guid__c</fullName>
    <label>Guid</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RiverId_Polls__c/fields/River_Name__c.field-meta.xml
<CustomField>
    <fullName>River_Name__c</fullName>
    <label>River Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RiverId_Polls__c/fields/RiverId_SFID__c.field-meta.xml
<CustomField>
    <fullName>RiverId_SFID__c</fullName>
    <label>RiverId_SFID</label>
    <referenceTo>RiverId__c</referenceTo>
    <relationshipLabel>RiverId Polls</relationshipLabel>
    <relationshipName>RiverId_Polls</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RiverId_Polls__c/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <externalId>true</externalId>
    <label>Token</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RiverEncuestasControllerTest.cls
@isTest
public class RiverEncuestasControllerTest {
    @isTest
    public static void RiverEncuestasControllerTest() {
        RiverId__c rvid = new RiverId__c();
        Insert rvid;

        List<RiverId_Polls__c> rvPolls = new List<RiverId_Polls__c> ();
        rvPolls.add(new RiverId_Polls__c(
            RiverId_SFID__c = rvid.id,
            River_Name__c = 'Encuesta 1',
            Token__c = 'token1',
            guid__c = 'guid1'
        ));
        rvPolls.add(new RiverId_Polls__c(
            RiverId_SFID__c = rvid.id,
            River_Name__c = 'Encuesta 1',
            Token__c = 'token2',
            guid__c = 'guid2'
        ));
        rvPolls.add(new RiverId_Polls__c(
            RiverId_SFID__c = rvid.id,
            River_Name__c = 'Encuesta 2',
            Token__c = 'token3',
            guid__c = 'guid3'
        ));
        Insert rvPolls;
        Test.startTest();
        List<AggregateResult> resutls = RiverEncuestasController.getGroupedEncuestas();
        Test.stopTest();
        System.debug(resutls);
    }
}