force-app/main/default/objects/RiverId__c/RiverId__c.object-meta.xml
<CustomObject>
    <label>RiverId</label>
    <nameField>
        <label>RiverId Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RiverIds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RiverId__c/fields/riverid_citizen__c.field-meta.xml
<CustomField>
    <fullName>riverid_citizen__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RiverIdCitizen</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>RiverIds</relationshipLabel>
    <relationshipName>RiverIds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RiverId_Polls__c/RiverId_Polls__c.object-meta.xml
<CustomObject>
    <label>RiverId Poll</label>
    <nameField>
        <displayFormat>RiverIdPol-{0000000}</displayFormat>
        <label>RiverId Polls Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RiverId Polls</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RiverId_Polls__c/fields/Abonos__c.field-meta.xml
<CustomField>
    <fullName>Abonos__c</fullName>
    <label>Abonos</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RiverId_Polls__c/fields/Beneficios__c.field-meta.xml
<CustomField>
    <fullName>Beneficios__c</fullName>
    <label>Beneficios</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RiverId_Polls__c/fields/Estadio__c.field-meta.xml
<CustomField>
    <fullName>Estadio__c</fullName>
    <label>Estadio</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RiverId_Polls__c/fields/Fecha_Respuesta__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Respuesta__c</fullName>
    <label>Fecha Respuesta</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RiverId_Polls__c/fields/Futbol__c.field-meta.xml
<CustomField>
    <fullName>Futbol__c</fullName>
    <label>Futbol</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RiverId_Polls__c/fields/Instalaciones__c.field-meta.xml
<CustomField>
    <fullName>Instalaciones__c</fullName>
    <label>Instalaciones</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RiverId_Polls__c/fields/RiverId_SFID__c.field-meta.xml
<CustomField>
    <fullName>RiverId_SFID__c</fullName>
    <label>RiverId_SFID</label>
    <referenceTo>RiverId__c</referenceTo>
    <relationshipLabel>RiverId Polls</relationshipLabel>
    <relationshipName>RiverId_Polls</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CommunitiesRiverController.cls
public with sharing class CommunitiesRiverController {
    
    @AuraEnabled(cacheable=true)
    public static List<RiverId_Polls__c> retrieveInfoPollsFromCitizenId(Id contactId) {
        try {
            RiverId__c river_id = [SELECT Id FROM RiverId__c WHERE riverid_citizen__c =: contactId LIMIT 1];
            if (river_id != null) {
                List<RiverId_Polls__c> polls = [SELECT Abonos__c, Beneficios__c, Estadio__c, Futbol__c, Instalaciones__c, Fecha_Respuesta__c FROM RiverId_Polls__c WHERE RiverId_SFID__c =: river_id.Id];
                return polls;
            }
        } catch (System.QueryException e) {
            system.debug('===error===>'+e);
            return null;
        }

        return null;
    }
}